local E, _, V, P, G = unpack(ElvUI); --Import: Engine, Locales, PrivateDB, ProfileDB, GlobalDB
local C, L = unpack(select(2, ...))
local B = E:GetModule("Blizzard")

E.Options.args.skins = {
	type = "group",
	name = L["Skins"],
	childGroups = "tab",
	order = 2,
	args = {
		intro = {
			order = 0,
			type = "description",
			name = L["SKINS_DESC"],
		},
		general = {
			order = 1,
			type = 'multiselect',
			name = L["General"],
			get = function(info, key) return E.private.skins.blizzard[key] end,
			set = function(info, key, value) E.private.skins.blizzard[key] = value; E:StaticPopup_Show("PRIVATE_RL") end,
			sortByValue = true,
			values = {
				blizzardEnable = L["Blizzard"],
				ace3 = "Ace3",
				checkBoxSkin = L["CheckBox Skin"],
				parchmentRemover = L["Parchment Remover"],
				cleanBossButton = L["Clean Boss Button"],
			},
		},
		talkingHead = {
			order = 2,
			type = 'group',
			guiInline = true,
			name = L["TalkingHead"],
			args = {
				talkingHeadFrameScale = {
					order = 24,
					type = "range",
					name = L["Talking Head Scale"],
					isPercent = true,
					min = 0.5, max = 2, step = 0.01,
					get = function(info) return E.db.general.talkingHeadFrameScale end,
					set = function(info, value) E.db.general.talkingHeadFrameScale = value; B:ScaleTalkingHeadFrame() end,
				},
				talkingHeadFrameBackdrop = {
					order = 25,
					type = "toggle",
					name = L["Talking Head Backdrop"],
					get = function(info) return E.db.general.talkingHeadFrameBackdrop end,
					set = function(info, value) E.db.general.talkingHeadFrameBackdrop = value; E:StaticPopup_Show("CONFIG_RL") end
				},
			},
		},
		blizzard = {
			order = 3,
			type = 'multiselect',
			name = L["Blizzard"],
			get = function(info, key) return E.private.skins.blizzard[key] end,
			set = function(info, key, value) E.private.skins.blizzard[key] = value; E:StaticPopup_Show("PRIVATE_RL") end,
			disabled = function() return not E.private.skins.blizzard.enable end,
			sortByValue = true,
			values = {
				deathRecap = L["DEATH_RECAP_TITLE"],
				garrison = L["GARRISON_LOCATION_TOOLTIP"],
				bmah = L["BLACK_MARKET_AUCTION_HOUSE"],
				transmogrify = L["TRANSMOGRIFY"],
				encounterjournal = L["ENCOUNTER_JOURNAL"],
				calendar = L["Calendar Frame"],
				achievement = L["ACHIEVEMENTS"],
				lfguild = L["LF Guild Frame"],
				inspect = L["INSPECT"],
				binding = L["KEY_BINDINGS"],
				gbank = L["GUILD_BANK"],
				archaeology = L["Archaeology Frame"],
				guildcontrol = L["Guild Control Frame"],
				guild = L["GUILD"],
				tradeskill = L["TRADESKILLS"],
				raid = L["Raid Frame"],
				talent = L["TALENTS"],
				auctionhouse = L["AUCTIONS"],
				timemanager = L["TIMEMANAGER_TITLE"],
				barber = L["BARBERSHOP"],
				macro = L["MACROS"],
				debug = L["Debug Tools"],
				trainer = L["Trainer Frame"],
				socket = L["Socket Frame"],
				alertframes = L["Alert Frames"],
				loot = L["Loot Frames"],
				bgscore = L["BG Score"],
				merchant = L["Merchant Frame"],
				mail = L["Mail Frame"],
				help = L["Help Frame"],
				trade = L["TRADE"],
				gossip = L["Gossip Frame"],
				worldmap = L["WORLD_MAP"],
				taxi = L["FLIGHT_MAP"],
				tooltip = L["Tooltip"],
				lfg = L["LFG_TITLE"],
				collections = L["COLLECTIONS"],
				quest = L["Quest Frames"],
				petition = L["Petition Frame"],
				dressingroom = L["DRESSUP_FRAME"],
				pvp = L["PvP Frames"],
				nonraid = L["Non-Raid Frame"],
				friends = L["FRIENDS"],
				spellbook = L["SPELLBOOK"],
				character = L["Character Frame"],
				misc = L["Misc Frames"],
				tabard = L["Tabard Frame"],
				guildregistrar = L["Guild Registrar"],
				bags = L["Bags"],
				stable = L["Stable"],
				bgmap = L["BG Map"],
				petbattleui = L["Pet Battle"],
				losscontrol = L["LOSS_OF_CONTROL"],
				voidstorage = L["VOID_STORAGE"],
				itemUpgrade = L["Item Upgrade"],
				questChoice = L["Quest Choice"],
				addonManager = L["AddOn Manager"],
				mirrorTimers = L["Mirror Timers"],
				objectiveTracker = L["OBJECTIVES_TRACKER_LABEL"],
				orderhall = L["Orderhall"],
				artifact = L["ITEM_QUALITY6_DESC"],
				talkinghead = L["TalkingHead"],
				AdventureMap = L["ADVENTURE_MAP_TITLE"],
				Obliterum = L["OBLITERUM_FORGE_TITLE"],
				Contribution = L["Contribution"],
				BlizzardOptions = L["INTERFACE_OPTIONS"],
				Warboard = L["Warboard"],
				AlliedRaces = L["Allied Races"],
				Channels  = L["CHANNELS"],
				AzeriteUI = L["AzeriteUI"],
				Communities = L["COMMUNITIES"],
				Scrapping = L["SCRAP_BUTTON"],
				IslandsPartyPose = L["Island Party Pose"],
				IslandQueue = L["ISLANDS_HEADER"],
				AzeriteRespec = L["AZERITE_RESPEC_TITLE"],
				GMChat = L["GM Chat"],
				AzeriteEssence = L["Azerite Essence"],
				Tutorials = L["Tutorials"],
				ItemInteraction = L["Item Interaction"],
			},
		},
	},
}
