-- 简体翻译 <a href="mailto:cadcamzy@hotmail.com">cadcamzy@hotmail.com</a>
if TukuiDB.client == "zhCN" then
	tukuilocal.disband = "Disbanding group."

	tukuilocal.datatext_guild = "公会"
	tukuilocal.datatext_noguild = "没有公会"
	tukuilocal.datatext_bags = "背包: "
	tukuilocal.datatext_friends = "好友"
	tukuilocal.datatext_online = "线上: "
	tukuilocal.datatext_armor = "耐久度"
	tukuilocal.datatext_earned = "赚取:"
	tukuilocal.datatext_spent = "花费:"
	tukuilocal.datatext_deficit = "赤字:"
	tukuilocal.datatext_profit = "利润:"
	tukuilocal.datatext_wg = "距离下一次冬握湖:"
	tukuilocal.datatext_friendlist = "好友名单:"
	tukuilocal.datatext_playersp = "法伤"
	tukuilocal.datatext_playerap = "强度"
	tukuilocal.datatext_playerhaste = "加速"
	tukuilocal.datatext_dps = "dps"
	tukuilocal.datatext_hps = "hps"
	tukuilocal.datatext_playerarp = "破甲"
	tukuilocal.datatext_session = "本次概况: "
	tukuilocal.datatext_character = "角色: "
	tukuilocal.datatext_server = "服务器: "
	tukuilocal.datatext_totalgold = "总额: "
	tukuilocal.datatext_savedraid = "已有进度的团队副本"
	tukuilocal.datatext_currency = "兑换通货:"
	tukuilocal.datatext_fps = " fps & "
	tukuilocal.datatext_ms = " ms"
	tukuilocal.datatext_playercrit = "% 爆击"
	tukuilocal.datatext_playerheal = " 治疗"
	tukuilocal.datatext_avoidancebreakdown = "免伤分析"
	tukuilocal.datatext_lvl = "等级"
	tukuilocal.datatext_boss = "首领"
	tukuilocal.datatext_miss = "未击中"
	tukuilocal.datatext_dodge = "闪躲"
	tukuilocal.datatext_block = "格档"
	tukuilocal.datatext_parry = "招架"
	tukuilocal.datatext_playeravd = "免伤: "
	tukuilocal.datatext_servertime = "服务器时间: "
	tukuilocal.datatext_localtime = "本地时间: "
	tukuilocal.datatext_mitigation = "等级缓和: "
	tukuilocal.datatext_healing = "治疗: "
	tukuilocal.datatext_damage = "伤害: "
	tukuilocal.datatext_honor = "荣誉: "
	tukuilocal.datatext_killingblows = "击杀 : "
	tukuilocal.datatext_ttstatsfor = "状态 "
	tukuilocal.datatext_ttkillingblows = "击杀:"
	tukuilocal.datatext_tthonorkills = "荣誉击杀:"
	tukuilocal.datatext_ttdeaths = "死亡:"
	tukuilocal.datatext_tthonorgain = "获得荣誉:"
	tukuilocal.datatext_ttdmgdone = "伤害输出:"
	tukuilocal.datatext_tthealdone = "治疗输出:"
	tukuilocal.datatext_basesassaulted = "基地突袭:"
	tukuilocal.datatext_basesdefended = "基地防御:"
	tukuilocal.datatext_towersassaulted = "哨塔突袭:"
	tukuilocal.datatext_towersdefended = "哨塔防御:"
	tukuilocal.datatext_flagscaptured = "占领旗帜:"
	tukuilocal.datatext_flagsreturned = "交还旗帜:"
	tukuilocal.datatext_graveyardsassaulted = "墓地突袭:"
	tukuilocal.datatext_graveyardsdefended = "墓地防守:"
	tukuilocal.datatext_demolishersdestroyed = "石毁车摧毁:"
	tukuilocal.datatext_gatesdestroyed = "大门摧毁:"
	tukuilocal.datatext_totalmemusage = "总共内存使用:"
	tukuilocal.datatext_control = "Controlled by:"
	
	tukuilocal.Slots = {
		[1] = {1, "头部", 1000},
		[2] = {3, "肩部", 1000},
		[3] = {5, "胸部", 1000},
		[4] = {6, "腰部", 1000},
		[5] = {9, "手腕", 1000},
		[6] = {10, "手", 1000},
		[7] = {7, "腿部", 1000},
		[8] = {8, "脚", 1000},
		[9] = {16, "主手", 1000},
		[10] = {17, "副手", 1000},
		[11] = {18, "远程", 1000}
	}
 
	tukuilocal.popup_disableui = "Tukui并不支援此分辨率, 你想要停用Tukui吗? (若果您想要尝试其他分辨率, 请按取消)"
	tukuilocal.popup_install = "这个角色首次使用Tukui V10.60+, 您必需先重载界面以完成设定"
	tukuilocal.popup_clique = "Your clique settings are not setup with Tukui, would you like to set them up?"
	
	tukuilocal.merchant_repairnomoney = "您没有足够的金钱来修理!"
	tukuilocal.merchant_repaircost = "您的装备已修理, 花费了"
	tukuilocal.merchant_trashsell = "您背包内的粗糙物品已被自动卖出, 您赚取了"
 
	tukuilocal.goldabbrev = "|cffffd700g|r"
	tukuilocal.silverabbrev = "|cffc7c7cfs|r"
	tukuilocal.copperabbrev = "|cffeda55fc|r"
 
	tukuilocal.error_noerror = "没有错误"
 
	tukuilocal.unitframes_ouf_offline = "离线"
	tukuilocal.unitframes_ouf_dead = "死亡"
	tukuilocal.unitframes_ouf_ghost = "鬼魂"
	tukuilocal.unitframes_ouf_lowmana = "法力过低"
	tukuilocal.unitframes_ouf_threattext = "Threat:"
	tukuilocal.unitframes_ouf_offlinedps = "离线"
	tukuilocal.unitframes_ouf_deaddps = "死亡"
	tukuilocal.unitframes_ouf_ghostheal = "鬼魂"
	tukuilocal.unitframes_ouf_deadheal = "死亡"
	tukuilocal.unitframes_ouf_gohawk = "切换为雄鹰守护"
	tukuilocal.unitframes_ouf_goviper = "切换为蝰蛇守护"
	tukuilocal.unitframes_disconnected = "断线"
 
	tukuilocal.tooltip_targetyou = "|cffff4444>>获得仇恨<<|r"
	tukuilocal.tooltip_count = "Count"
 
	tukuilocal.priest_wsdebuff = "虚弱灵魂"
	tukuilocal.priest_ifbuff = "心灵之火"
 
	tukuilocal.bags_noslots = "不能再购买更多的背包栏位!"
	tukuilocal.bags_costs = "花费: %.2f 金"
	tukuilocal.bags_buyslots = "输入 /bags purchase yes 以购买银行背包栏位"
	tukuilocal.bags_openbank = "您需要先造访您的银行"
	tukuilocal.bags_sort = "将背包或银行内的物品分类及排序"
	tukuilocal.bags_stack = "将背包或银行内的不完整的物品堆叠重新堆叠"
	tukuilocal.bags_buybankslot = "购买银行背包栏位. (需要造访银行)"
	tukuilocal.bags_search = "搜寻"
	tukuilocal.bags_sortmenu = "分类及排序"
	tukuilocal.bags_sortspecial = "分类及排序特殊物品"
	tukuilocal.bags_stackmenu = "堆叠"
	tukuilocal.bags_stackspecial = "堆叠特殊物品"
	tukuilocal.bags_showbags = "显示背包"
	tukuilocal.bags_sortingbags = "分类及排序完成"
	tukuilocal.bags_nothingsort= "不需要分类"
	tukuilocal.bags_bids = "使用背包: "
	tukuilocal.bags_stackend = "重新堆叠完成"
 
	tukuilocal.chat_invalidtarget = "无效的目标"
 
	tukuilocal.mount_wintergrasp = "冬握湖"
 
	tukuilocal.playermenu_freeforall = "自由拾取"
	tukuilocal.playermenu_group = "|cff1eff00队伍分配|r"
	tukuilocal.playermenu_master = "|cff0070dd队长分配|r"
	tukuilocal.playermenu_global_needbeforegreed = "分配: %s需求优先|r"
	tukuilocal.playermenu_global_freeforall = "分配: %s自由拾取|r"
	tukuilocal.playermenu_global_group = "分配: %s队伍分配|r"
	tukuilocal.playermenu_global_master = "分配: %s队长分配|r"
	tukuilocal.playermenu_normal = "5 |cffffff50普通|r"
	tukuilocal.playermenu_heroic = "5 |cffff5050英雄|r"
	tukuilocal.playermenu_raid10 = "10 |cffffff50普通|r"
	tukuilocal.playermenu_raid25 = "25 |cffffff50普通|r"
	tukuilocal.playermenu_raid10h = "10 |cffff5050英雄|r"
	tukuilocal.playermenu_raid25h = "25 |cffff5050英雄|r"
 
	tukuilocal.core_autoinv_enable = "启用自动邀请: invite"
	tukuilocal.core_autoinv_enable_c = "自动邀请功能已启用: "
	tukuilocal.core_autoinv_disable = "自动邀请功能已关闭"
	tukuilocal.core_wf_unlock = "解锁任务追踪"
	tukuilocal.core_wf_lock = "锁定任务追踪"
	tukuilocal.core_welcome1 = "欢迎使用 |cffC495DDTukui|r "
	tukuilocal.core_welcome2 = "输入 |cff00FFFF/uihelp|r 以获得更多信息"
 
	tukuilocal.core_uihelp1 = "|cff00ff00基本指令|r"
	tukuilocal.core_uihelp2 = "|cffFF0000/tracker|r - Tukui 竞技场敌方冷却监视器 - 一个精简的PvP冷却监视器 (Icon only)"
	tukuilocal.core_uihelp3 = "|cffFF0000/rl|r - 重载您的使用者界面"
	tukuilocal.core_uihelp4 = "|cffFF0000/gm|r - 联系GM或开启魔兽世界帮助讯息"
	tukuilocal.core_uihelp5 = "|cffFF0000/frame|r - 侦测您滑鼠位置上的框架名称 (对于lua编制者非常有帮助)"
	tukuilocal.core_uihelp6 = "|cffFF0000/heal|r - 启用治疗的ouf界面"
	tukuilocal.core_uihelp7 = "|cffFF0000/dps|r - 启用Dps/Tank的ouf界面"
	tukuilocal.core_uihelp8 = "|cffFF0000/uf|r - 启用或停用可移动ouf框架"
	tukuilocal.core_uihelp9 = "|cffFF0000/bags|r - 分类及排序背包, 购买银行背包栏位或重新堆叠背包/银行内的物品"
	tukuilocal.core_uihelp10 = "|cffFF0000/resetui|r - 重置Tukui的设定"
	tukuilocal.core_uihelp11 = "|cffFF0000/rd|r - 解散团队"
	tukuilocal.core_uihelp12 = "|cffFF0000/hb|r - set keybinds to your action buttons."
	tukuilocal.core_uihelp13 = "|cffFF0000/mss|r - 移动变形条和图腾条"
	tukuilocal.core_uihelp14 = "(向上滚动以获得更多命令 ...)"
	tukuilocal.core_uihelp16 = "|cffFF0000/resetgold|r - reset the gold datatext"
	
	tukuilocal.core_uihelp15 = "|cffFF0000/ainv|r - 输入关键字(预设:/ainv)以启用密语自动邀请, 您可以自行设定关键字, 指令为/ainv 关键字"
 
	tukuilocal.symbol_CLEAR = "清除"
	tukuilocal.symbol_SKULL = "骷髅"
	tukuilocal.symbol_CROSS = "十字"
	tukuilocal.symbol_SQUARE = "方块"
	tukuilocal.symbol_MOON = "月亮"
	tukuilocal.symbol_TRIANGLE = "三角"
	tukuilocal.symbol_DIAMOND = "菱形"
	tukuilocal.symbol_CIRCLE = "大饼"
	tukuilocal.symbol_STAR = "星星"
 
	tukuilocal.bind_combat = "您不能在战斗中设定快捷键"
	tukuilocal.bind_saved = "所有快捷键修改已保存"
	tukuilocal.bind_discard = "这次的快捷键修改已重设为上一次修改"
	tukuilocal.bind_instruct = "将鼠标指向动作条上以绑定快捷键, 您可以按ESC或以右键点击快捷条上任何一格以清除该位置的设定"
	tukuilocal.bind_save = "保存"
	tukuilocal.bind_discardbind = "放弃"
 
	tukuilocal.hunter_unhappy = "你的宠物感到不高兴!"
	tukuilocal.hunter_content = "你的宠物感到满足!"
	tukuilocal.hunter_happy = "你的宠物感到高兴!"
	
	tukuilocal.teleport = "Teleport: "
	tukuilocal.portal = "Portal: "

	tukuilocal.dalaran = "Dalaran"
	tukuilocal.shattrath = "Shattrath"
		
	tukuilocal.orgrimmar = "Orgrimmar"
	tukuilocal.undercity = "Undercity"
	tukuilocal.thunder_bluff = "Thunder Bluff"
	tukuilocal.silvermoon = "Silvermoon"
	tukuilocal.stonard = "Stonard"
		
	tukuilocal.ironforge = "Ironforge"
	tukuilocal.stormwind = "Stormwind"
	tukuilocal.darnassus = "Darnassus"
	tukuilocal.exodar = "Exodar"
	tukuilocal.theramore = "Theramore"
end