if TukuiDB.client == "frFR" then

	tukuilocal.chat_BATTLEGROUND_GET = "[BG]"
	tukuilocal.chat_BATTLEGROUND_LEADER_GET = "[BG]"
	tukuilocal.chat_BN_WHISPER_GET = "De"
	tukuilocal.chat_GUILD_GET = "[G]"
	tukuilocal.chat_OFFICER_GET = "[O]"
	tukuilocal.chat_PARTY_GET = "[G]"
	tukuilocal.chat_PARTY_GUIDE_GET = "[G]"
	tukuilocal.chat_PARTY_LEADER_GET = "[G]"
	tukuilocal.chat_RAID_GET = "[R]"
	tukuilocal.chat_RAID_LEADER_GET = "[R]"
	tukuilocal.chat_RAID_WARNING_GET = "[W]"
	tukuilocal.chat_WHISPER_GET = "De"
	tukuilocal.chat_FLAG_AFK = "[AFK]"
	tukuilocal.chat_FLAG_DND = "[DND]"
	tukuilocal.chat_FLAG_GM = "[MJ]"
	tukuilocal.chat_ERR_FRIEND_ONLINE_SS = "est maintenant |cff298F00en ligne|r"
	tukuilocal.chat_ERR_FRIEND_OFFLINE_S = "est maintenant |cffff0000déconnecté|r"

	tukuilocal.disband = "Dissoudre le groupe"

	tukuilocal.datatext_guild = "Guilde"
	tukuilocal.datatext_noguild = "Pas de Guilde"
	tukuilocal.datatext_bags = "Sacs: "
	tukuilocal.datatext_friends = "Amis"
	tukuilocal.datatext_online = "En ligne: "
	tukuilocal.datatext_armor = "Armure"
	tukuilocal.datatext_earned = "Gagné:"
	tukuilocal.datatext_spent = "Depensé:"
	tukuilocal.datatext_deficit = "Déficit:"
	tukuilocal.datatext_profit = "Profit:"
	tukuilocal.datatext_timeto = "Temps restant"
	tukuilocal.datatext_friendlist = "Liste d'amis:"
	tukuilocal.datatext_playersp = "sp"
	tukuilocal.datatext_playerap = "ap"
	tukuilocal.datatext_playerhaste = "hâte"
	tukuilocal.datatext_dps = "dps"
	tukuilocal.datatext_hps = "hps"
	tukuilocal.datatext_playerarp = "arp"
	tukuilocal.datatext_session = "Session: "
	tukuilocal.datatext_character = "Personnage: "
	tukuilocal.datatext_server = "Serveur: "
	tukuilocal.datatext_totalgold = "Total: "
	tukuilocal.datatext_savedraid = "Raid(s) enregistré(s)"
	tukuilocal.datatext_currency = "Monnaie:"
	tukuilocal.datatext_fps = " fps & "
	tukuilocal.datatext_ms = " ms"
	tukuilocal.datatext_playercrit = " crit"
	tukuilocal.datatext_playerheal = " heal"
	tukuilocal.datatext_avoidancebreakdown = "Évitement"
	tukuilocal.datatext_lvl = "lvl"
	tukuilocal.datatext_boss = "boss"
	tukuilocal.datatext_miss = "Coup raté"
	tukuilocal.datatext_dodge = "Esquive"
	tukuilocal.datatext_block = "Bloquer"
	tukuilocal.datatext_parry = "Parade"
	tukuilocal.datatext_playeravd = "avd: "
	tukuilocal.datatext_servertime = "Heure Serveur: "
	tukuilocal.datatext_localtime = "Heure Locale: "
	tukuilocal.datatext_mitigation = "Mitigation par Level: "
	tukuilocal.datatext_healing = "Soins : "
	tukuilocal.datatext_damage = "Dégâts : "
	tukuilocal.datatext_honor = "Honneur : "
	tukuilocal.datatext_killingblows = "Coups fatals : "
	tukuilocal.datatext_ttstatsfor = "Statistiques pour "
	tukuilocal.datatext_ttkillingblows = "Coups fatals:"
	tukuilocal.datatext_tthonorkills = "Victoires honorables:"
	tukuilocal.datatext_ttdeaths = "Morts:"
	tukuilocal.datatext_tthonorgain = "Points d'honneur gagnés:"
	tukuilocal.datatext_ttdmgdone = "Dégâts effectués:"
	tukuilocal.datatext_tthealdone = "Soins prodigués:"
	tukuilocal.datatext_basesassaulted = "Bases Attaquées:"
	tukuilocal.datatext_basesdefended = "Bases Défendues:"
	tukuilocal.datatext_towersassaulted = "Tours Attaquées:"
	tukuilocal.datatext_towersdefended = "Tours Défendues:"
	tukuilocal.datatext_flagscaptured = "Drapeaux Capturés:"
	tukuilocal.datatext_flagsreturned = "Drapeaux Récupérés:"
	tukuilocal.datatext_graveyardsassaulted = "Cimetières Attaqués:"
	tukuilocal.datatext_graveyardsdefended = "Cimetières Défendus:"
	tukuilocal.datatext_demolishersdestroyed = "Démolisseurs Détruits:"
	tukuilocal.datatext_gatesdestroyed = "Portes Détruites:"
	tukuilocal.datatext_totalmemusage = "Utilisation Totale de la Mémoire:"
	tukuilocal.datatext_control = "Controllé par:"

	tukuilocal.Slots = {
	  [1] = {1, "Tête", 1000},
	  [2] = {3, "Épaule", 1000},
	  [3] = {5, "Plastron", 1000},
	  [4] = {6, "Ceinture", 1000},
	  [5] = {9, "Bracelet", 1000},
	  [6] = {10, "Mains", 1000},
	  [7] = {7, "Jambes", 1000},
	  [8] = {8, "Bottes", 1000},
	  [9] = {16, "Main droite", 1000},
	  [10] = {17, "Main gauche", 1000},
	  [11] = {18, "À Distance", 1000}
	}

	tukuilocal.popup_disableui = "Tukui ne fonctionne pas avec cette résolution, voulez-vous désactiver Tukui? (Annuler si vous souhaitez essayer une autre résolution)"
	tukuilocal.popup_install = "Première fois sur Tukui V12 avec ce personnage. Vous devez recharger l'interface utilisateur afin de configurer les barres d'action, les variables et les cadres de Chat."
	tukuilocal.popup_2raidactive = "2 modèles de raid sont activés, merci d'en choisir un."

	tukuilocal.merchant_repairnomoney = "Vous n'avez pas assez d'argent pour réparer!"
	tukuilocal.merchant_repaircost = "Tous les objets ont été réparés pour"
	tukuilocal.merchant_trashsell = "Votre vente d’objets gris a été vendu et vous avez gagné" --

	tukuilocal.goldabbrev = "|cffffd700o|r"
	tukuilocal.silverabbrev = "|cffc7c7cfa|r"
	tukuilocal.copperabbrev = "|cffeda55fc|r"

	tukuilocal.error_noerror = "pas d'erreur pour le moment."

	tukuilocal.unitframes_ouf_offline = "Hors ligne"
	tukuilocal.unitframes_ouf_dead = "Mort"
	tukuilocal.unitframes_ouf_ghost = "Fantome"
	tukuilocal.unitframes_ouf_lowmana = "MANA FAIBLE"
	tukuilocal.unitframes_ouf_threattext = "Menace sur la cible actuelle:"
	tukuilocal.unitframes_ouf_offlinedps = "Hors ligne"
	tukuilocal.unitframes_ouf_deaddps = "|cffff0000[MORT]|r"
	tukuilocal.unitframes_ouf_ghostheal = "FANTOME"
	tukuilocal.unitframes_ouf_deadheal = "MORT"
	tukuilocal.unitframes_ouf_gohawk = "GO FAUCON"
	tukuilocal.unitframes_ouf_goviper = "GO VIPÈRE"
	tukuilocal.unitframes_disconnected = "Déco"

	tukuilocal.tooltip_count = "Total"

	tukuilocal.bags_noslots = "Vous ne pouvez pas acheter plus de place!"
	tukuilocal.bags_costs = "Prix: %.2f or"
	tukuilocal.bags_buyslots = "Acheter un nouvel emplacement avec /bags"
	tukuilocal.bags_openbank = "Vous devez d'abord ouvrir votre banque."
	tukuilocal.bags_sort = "Trier vos sacs ou votre banque, si elle est ouverte."
	tukuilocal.bags_stack = "Empile vos objets  dans votre sac ou en banque, si elle est ouverte."
	tukuilocal.bags_buybankslot = "Acheter une place à la banque. (nécessite d'avoir votre banque ouverte)"
	tukuilocal.bags_search = "Recherche"
	tukuilocal.bags_sortmenu = "Trier"
	tukuilocal.bags_sortspecial = "Tri personnalisé"
	tukuilocal.bags_stackmenu = "Empiler"
	tukuilocal.bags_stackspecial = "Empilage personnalisé"
	tukuilocal.bags_showbags = "Montrer les sacs"
	tukuilocal.bags_sortingbags = "Tri terminé."
	tukuilocal.bags_nothingsort= "Rien à trier."
	tukuilocal.bags_bids = "Emplacements utilisés: "
	tukuilocal.bags_stackend = "Empilage terminé."
	tukuilocal.bags_rightclick_search = "Click-droit pour rechercher."

	tukuilocal.chat_invalidtarget = "Cible non valide"

	tukuilocal.mount_wintergrasp = "Joug-d'hiver"

	tukuilocal.core_autoinv_enable = "Invitation automatique: invite"
	tukuilocal.core_autoinv_enable_c = "Invitation automatique activée: "
	tukuilocal.core_autoinv_disable = "Invitation automatique désactivée"
	tukuilocal.core_wf_unlock = "Fenêtre des quêtes déverrouillée"
	tukuilocal.core_wf_lock = "Fenêtre des quêtes verrouillée"
	tukuilocal.core_welcome1 = "Bienvenue sur |cffC495DDTukui|r, version "
	tukuilocal.core_welcome2 = "Tapez |cff00FFFF/uihelp|r pour plus de détails ou visitez www.tukui.org"

	tukuilocal.core_uihelp1 = "|cff00ff00Commandes générales|r"
	tukuilocal.core_uihelp2 = "|cffFF0000/tracker|r - Traqueur de bijoux pour arêne - Traqueur de bijoux pour arêne - Basse mémoire. (Icone seulement)"
	tukuilocal.core_uihelp3 = "|cffFF0000/rl|r - Rechargez votre interface."
	tukuilocal.core_uihelp4 = "|cffFF0000/gm|r - Formuler une requête pour parler à un MJ."
	tukuilocal.core_uihelp5 = "|cffFF0000/frame|r - Affiche la fenêtre qui cible votre souris. (Très pratique pour l'édition des lua)"
	tukuilocal.core_uihelp6 = "|cffFF0000/heal|r - Active la fenêtre HEAL."
	tukuilocal.core_uihelp7 = "|cffFF0000/dps|r - Active la fenêtre DPS / Tank."
	tukuilocal.core_uihelp8 = "|cffFF0000/uf|r - Vérrouille ou déverrouille les fenêtres."
	tukuilocal.core_uihelp9 = "|cffFF0000/bags|r - pour trier, achter un slot de banque ou empiler les objets de vos sacs."
	tukuilocal.core_uihelp10 = "|cffFF0000/resetui|r - Réinitialise cVar et la fenêtre de Chat."
	tukuilocal.core_uihelp11 = "|cffFF0000/rd|r - Dissoudre le raid."
	tukuilocal.core_uihelp12 = "|cffFF0000/wf|r - Déverrouille la fenêtre de quêtes."
	tukuilocal.core_uihelp13 = "|cffFF0000/mss|r - Bouge la bar des auras / Totems"
	tukuilocal.core_uihelp15 = "|cffFF0000/ainv|r - Active l'invitation automatique via le chuchotement. Vous pouvez personnalisez la commande en tapant `/ainv myword`"
	tukuilocal.core_uihelp14 = "(Descendez pour afficher plus d'options...)"
	
	tukuilocal.symbol_CLEAR = "Aucun"
	tukuilocal.symbol_SKULL = "Crâne"
	tukuilocal.symbol_CROSS = "Croix"
	tukuilocal.symbol_SQUARE = "Carré"
	tukuilocal.symbol_MOON = "Lune"
	tukuilocal.symbol_TRIANGLE = "Triangle"
	tukuilocal.symbol_DIAMOND = "Losange"
	tukuilocal.symbol_CIRCLE = "Cercle"
	tukuilocal.symbol_STAR = "Etoile"
	
	tukuilocal.bind_combat = "Vous ne pouvez pas assigner une touche en combat."
	tukuilocal.bind_saved = "Vos assignations de touches ont été sauvegardées."
	tukuilocal.bind_discard = "Vos nouvelles assignations de touches n'ont été sauvegardées."
	tukuilocal.bind_instruct = "Passez votre souris sur la barre d'action pour l'assigner. Appuyez sur la touche échappe ou faites un clic droit pour effacer le bouton d'action en cours."
	tukuilocal.bind_save = "Sauvegarder les assignations."
	tukuilocal.bind_discardbind = "Annuler les assignations."
	
	tukuilocal.hunter_unhappy = "Votre familier n'est pas heureux!"
	tukuilocal.hunter_content = "Votre familier est heureux!"
	tukuilocal.hunter_happy = "Votre familier est très heureux!"
end