if TukuiDB.client == "deDE" then

	tukuilocal.chat_BATTLEGROUND_GET = "[B]"
	tukuilocal.chat_BATTLEGROUND_LEADER_GET = "[B]"
	tukuilocal.chat_BN_WHISPER_GET = "Von"
	tukuilocal.chat_GUILD_GET = "[G]"
	tukuilocal.chat_OFFICER_GET = "[O]"
	tukuilocal.chat_PARTY_GET = "[P]"
	tukuilocal.chat_PARTY_GUIDE_GET = "[P]"
	tukuilocal.chat_PARTY_LEADER_GET = "[P]"
	tukuilocal.chat_RAID_GET = "[R]"
	tukuilocal.chat_RAID_LEADER_GET = "[R]"
	tukuilocal.chat_RAID_WARNING_GET = "[W]"
	tukuilocal.chat_WHISPER_GET = "Von"
	tukuilocal.chat_FLAG_AFK = "[AFK]"
	tukuilocal.chat_FLAG_DND = "[DND]"
	tukuilocal.chat_FLAG_GM = "[GM]"
	tukuilocal.chat_ERR_FRIEND_ONLINE_SS = "ist jetzt |cff298F00online|r"
	tukuilocal.chat_ERR_FRIEND_OFFLINE_S = "ist jetzt |cffff0000offline|r"
	
	tukuilocal.disband = "Gruppe wird aufgelöst."  
 
	tukuilocal.datatext_guild = "Gilde"
	tukuilocal.datatext_noguild = "Keine Gilde"
	tukuilocal.datatext_bags = "Tasche: "
	tukuilocal.datatext_friends = "Freunde"
	tukuilocal.datatext_online = "Online: "
	tukuilocal.datatext_armor = "Rüstung"
	tukuilocal.datatext_earned = "Erhalten:"
	tukuilocal.datatext_spent = "Ausgegeben:"
	tukuilocal.datatext_deficit = "Differenz:"
	tukuilocal.datatext_profit = "Gewinn:"
	tukuilocal.datatext_timeto = "Zeit bis"
	tukuilocal.datatext_friendlist = "Freundesliste:"
	tukuilocal.datatext_playersp = "sp"
	tukuilocal.datatext_playerap = "ap"
	tukuilocal.datatext_playerhaste = "haste"
	tukuilocal.datatext_dps = "dps"
	tukuilocal.datatext_hps = "hps"
	tukuilocal.datatext_playerarp = "arp"
	tukuilocal.datatext_session = "Sitzung: "  
	tukuilocal.datatext_character = "Charakter: "
	tukuilocal.datatext_server = "Server: "
	tukuilocal.datatext_totalgold = "Gesamt: "
	tukuilocal.datatext_savedraid = "Instanz ID(s)"
	tukuilocal.datatext_currency = "Währung:"
	tukuilocal.datatext_fps = " fps & "
	tukuilocal.datatext_ms = " ms"
	tukuilocal.datatext_playercrit = " crit"
	tukuilocal.datatext_playerheal = " heal"
	tukuilocal.datatext_avoidancebreakdown = "Vermeidungsübersicht" 
	tukuilocal.datatext_lvl = "lvl"
	tukuilocal.datatext_boss = "boss"
	tukuilocal.datatext_miss = "Verfehlen" 
	tukuilocal.datatext_dodge = "Ausweichen"  
	tukuilocal.datatext_block = "Blocken" 
	tukuilocal.datatext_parry = "Parieren" 
	tukuilocal.datatext_playeravd = "avd: "
	tukuilocal.datatext_servertime = "Server Zeit: "
	tukuilocal.datatext_localtime = "Lokale Zeit: "
	tukuilocal.datatext_mitigation = "Schadensverringerung nach Level: " 
	tukuilocal.datatext_healing = "Heilung : "
	tukuilocal.datatext_damage = "Schaden : "
	tukuilocal.datatext_honor = "Ehre : "
	tukuilocal.datatext_killingblows = "Todesstöße : "
	tukuilocal.datatext_ttstatsfor = "Stats für "
	tukuilocal.datatext_ttkillingblows = "Todesstöße:"
	tukuilocal.datatext_tthonorkills = "Ehrenhafte Siege:"
	tukuilocal.datatext_ttdeaths = "Tode:"
	tukuilocal.datatext_tthonorgain = "Ehre erhalten:"
	tukuilocal.datatext_ttdmgdone = "Schaden verursacht:"
	tukuilocal.datatext_tthealdone = "Heilung verursacht:"
	tukuilocal.datatext_basesassaulted = "Basen angegriffen:"
	tukuilocal.datatext_basesdefended = "Basen verteidigt:"
	tukuilocal.datatext_towersassaulted = "Türme angegriffen:"
	tukuilocal.datatext_towersdefended = "Türme verteidigt:"
	tukuilocal.datatext_flagscaptured = "Flaggen eingenommen:"
	tukuilocal.datatext_flagsreturned = "Flaggen zurückgebracht:"
	tukuilocal.datatext_graveyardsassaulted = "Friedhöfe angegriffen:"
	tukuilocal.datatext_graveyardsdefended = "Friedhöfe verteidigt:"
	tukuilocal.datatext_demolishersdestroyed = "Verwüster zerstört:"
	tukuilocal.datatext_gatesdestroyed = "Tore zerstört:"
	tukuilocal.datatext_totalmemusage = "Gesamte Speichernutzung:"
	tukuilocal.datatext_control = "Kontrolliert von:"
 
	tukuilocal.Slots = {
		[1] = {1, "Kopf", 1000},
		[2] = {3, "Schulter", 1000},
		[3] = {5, "Brust", 1000},
		[4] = {6, "Gürtel", 1000},
		[5] = {9, "Handgelenke", 1000},
		[6] = {10, "Hände", 1000},
		[7] = {7, "Beine", 1000},
		[8] = {8, "Füße", 1000},
		[9] = {16, "Main Hand", 1000},
		[10] = {17, "Off Hand", 1000},
		[11] = {18, "Fernkampf", 1000}
	}
 
	tukuilocal.popup_disableui = "Tukui funktioniert nicht mit deiner Auflösung, möchtest du Tukui ausschalten? (Drücke Abbrechen, falls du eine andere Auflösung testen willst.)"
	tukuilocal.popup_install = "Dies ist das erste mal mit Tukui V12 mit diesem Charakter. Du musst dein UI neuladen um Aktionsleisten, Variabeln und den Chat einzustellen."   
 
	tukuilocal.merchant_repairnomoney = "Du hast nicht genügend Gold zum Reparieren!" 
	tukuilocal.merchant_repaircost = "Deine Rüstung wurde repariert für"
	tukuilocal.merchant_trashsell = "Dein Trash wurde verkauft und du erhälst"
 
	tukuilocal.goldabbrev = "|cffffd700g|r"
	tukuilocal.silverabbrev = "|cffc7c7cfs|r"
	tukuilocal.copperabbrev = "|cffeda55fk|r"
 
	tukuilocal.error_noerror = "Kein Fehler bis jetzt."
 
	tukuilocal.unitframes_ouf_offline = "Offline"
	tukuilocal.unitframes_ouf_dead = "Tod"
	tukuilocal.unitframes_ouf_ghost = "Geist"
	tukuilocal.unitframes_ouf_lowmana = "WENIG MANA"
	tukuilocal.unitframes_ouf_threattext = "Bedrohung am aktuellen Ziel:"
	tukuilocal.unitframes_ouf_offlinedps = "Offline"
	tukuilocal.unitframes_ouf_deaddps = "|cffff0000[TOD]|r"
	tukuilocal.unitframes_ouf_ghostheal = "GEIST"
	tukuilocal.unitframes_ouf_deadheal = "TOD"
	tukuilocal.unitframes_ouf_gohawk = "GO FALKE"
	tukuilocal.unitframes_ouf_goviper = "GO VIPER"
	tukuilocal.unitframes_disconnected = "D/C"
 
	tukuilocal.tooltip_count = "Anzahl"  
 
	tukuilocal.bags_noslots = "Kann keine weiteren Taschenplätze kaufen!"
	tukuilocal.bags_costs = "Kosten: %.2f Gold"  
	tukuilocal.bags_buyslots = "Kaufe neuen Platz mit /bags purchase yes"
	tukuilocal.bags_openbank = "Du musst erst das Bankfach öffnen."
	tukuilocal.bags_sort = "Sortiert deine Taschen oder die Bank, falls geöffnet."  
	tukuilocal.bags_stack = "Stapelt Items neu in deinen Taschen und der Bank, falls geöffnet."  
	tukuilocal.bags_buybankslot = "Kaufe Bankplatz. (Bank muss geöffnet sein)" 
	tukuilocal.bags_search = "Suchen"
	tukuilocal.bags_sortmenu = "Sortieren"
	tukuilocal.bags_sortspecial = "Sortieren Spezialtasche"  
	tukuilocal.bags_stackmenu = "Stapeln"
	tukuilocal.bags_stackspecial = "Stapeln Spezialtasche" 
	tukuilocal.bags_showbags = "Zeige Taschen"
	tukuilocal.bags_sortingbags = "Sortieren abgeschlossen."  
	tukuilocal.bags_nothingsort= "Nichts zu sortieren."
	tukuilocal.bags_bids = "Benutze Taschen: "
	tukuilocal.bags_stackend = "Neu stapeln abgeschlossen."  
	tukuilocal.bags_rightclick_search = "Rechtsklick um zu suchen." 
 
	tukuilocal.chat_invalidtarget = "Falsches Ziel"
 
	tukuilocal.mount_wintergrasp = "Tausendwinter"
 
	tukuilocal.core_autoinv_enable = "Autoinvite AN: invite"  
	tukuilocal.core_autoinv_enable_c = "Autoinvite AN: "   
	tukuilocal.core_autoinv_disable = "Autoinvite AUS"   
	tukuilocal.core_wf_unlock = "Quest Tracker entriegelt"
	tukuilocal.core_wf_lock = "Quest Tracker verriegelt" 
	tukuilocal.core_welcome1 = "Willkommen bei |cffC495DDTukui|r Version " 
	tukuilocal.core_welcome2 = "Tippe |cff00FFFF/uihelp|r für mehr Informationen"
 
	tukuilocal.core_uihelp1 = "|cff00ff00Allgemeine Slash Befehle|r"
	tukuilocal.core_uihelp2 = "|cffFF0000/tracker|r - Tukui Arena Gegner Cooldown Tracker - Low-memory Gegner PVP cooldown tracker. (Icon only)"
	tukuilocal.core_uihelp3 = "|cffFF0000/rl|r - User Interface neu laden."
	tukuilocal.core_uihelp4 = "|cffFF0000/gm|r - Schicke GM Tickets oder öffnet die WoW Ingame Hilfe."
	tukuilocal.core_uihelp5 = "|cffFF0000/frame|r - Zeigt im Chat den Namen des Fensters über dem sich die Maus befindet. (Hilfreich für Lua Editoren)"
	tukuilocal.core_uihelp6 = "|cffFF0000/heal|r - Aktiviert Heiler Raid Layout." 
	tukuilocal.core_uihelp7 = "|cffFF0000/dps|r - Aktiviert DPS/Tank Raid Layout."
	tukuilocal.core_uihelp8 = "|cffFF0000/uf|r - Aktiviert oder Deaktiviert das Bewegen der Unitframes."  
	tukuilocal.core_uihelp9 = "|cffFF0000/bags|r - Zum Sortieren, Kaufen von Bankplätzen oder neu Stapeln von Gegenständen in deiner Tasche." 
	tukuilocal.core_uihelp10 = "|cffFF0000/resetui|r - Wiederherstellung der ursprünglichen Tukui Einstellungen." 
	tukuilocal.core_uihelp11 = "|cffFF0000/rd|r - Raid auflösen."
	tukuilocal.core_uihelp12 = "|cffFF0000/wf|r - Befehl um den Blizzard Quest Tracker frei zu verschieben."
	tukuilocal.core_uihelp13 = "|cffFF0000/mss|r - Befehl um die Haltungs-(Krieger), Präsenz-(Todesritter), Auren-(Paladin), Formen-(Druide), Schattengestalt-(Priester) und Totem-(Schamane) Leisten zu bewegen." 
	tukuilocal.core_uihelp15 = "|cffFF0000/ainv|r - Aktiviere autoinvite per Flüsterschlüsselwort. Du kannst durch Tippen von <code>/ainv meinwort</code> dein eigenes Schlüsselwort setzen."  
	tukuilocal.core_uihelp14 = "(Scrolle hoch für weitere Befehle ...)"
 
	tukuilocal.symbol_CLEAR = "Entfernen" 
	tukuilocal.symbol_SKULL = "Schädel"
	tukuilocal.symbol_CROSS = "Kreuz"
	tukuilocal.symbol_SQUARE = "Quadrat"
	tukuilocal.symbol_MOON = "Mond"
	tukuilocal.symbol_TRIANGLE = "Grün"
	tukuilocal.symbol_DIAMOND = "Diamant"
	tukuilocal.symbol_CIRCLE = "Kreis"
	tukuilocal.symbol_STAR = "Stern"
 
	tukuilocal.bind_combat = "Du kannst keine Tasten im Kampf belegen."
	tukuilocal.bind_saved = "Alle Tastenbelegungen wurden gespeichert."
	tukuilocal.bind_discard = "Alle grade neu belegten Tastenbelegungen wurden verworfen."
	tukuilocal.bind_instruct = "Bewege deine Maus über einen Aktionsbutton um ihn mit einem Hotkey zu belegen. Drücke Escape oder Rechte Maustaste um die aktuelle Tastenbelegeung des Buttons zu löschen."  
	tukuilocal.bind_save = "Tastenbelegung speichern"
	tukuilocal.bind_discardbind = "Tastenbelegung verwerfen"
 
	tukuilocal.hunter_unhappy = "Dein Begleiter ist unzufrieden!"
	tukuilocal.hunter_content = "Dein Begleiter ist zufrieden!"
	tukuilocal.hunter_happy = "Dein Begleiter ist glücklich!" 
end