if TukuiDB.client == "esES" then

	tukuilocal.chat_BATTLEGROUND_GET = "[B]"
	tukuilocal.chat_BATTLEGROUND_LEADER_GET = "[B]"
	tukuilocal.chat_BN_WHISPER_GET = "From"
	tukuilocal.chat_GUILD_GET = "[G]"
	tukuilocal.chat_OFFICER_GET = "[O]"
	tukuilocal.chat_PARTY_GET = "[P]"
	tukuilocal.chat_PARTY_GUIDE_GET = "[P]"
	tukuilocal.chat_PARTY_LEADER_GET = "[P]"
	tukuilocal.chat_RAID_GET = "[R]"
	tukuilocal.chat_RAID_LEADER_GET = "[R]"
	tukuilocal.chat_RAID_WARNING_GET = "[W]"
	tukuilocal.chat_WHISPER_GET = "From"
	tukuilocal.chat_FLAG_AFK = "[AFK]"
	tukuilocal.chat_FLAG_DND = "[DND]"
	tukuilocal.chat_FLAG_GM = "[GM]"
	tukuilocal.chat_ERR_FRIEND_ONLINE_SS = "is now |cff298F00online|r"
	tukuilocal.chat_ERR_FRIEND_OFFLINE_S = "is now |cffff0000offline|r"
	
	tukuilocal.disband = "Desacer grupo."
 
	tukuilocal.datatext_guild = "Hermandad"
	tukuilocal.datatext_noguild = "Sin Hermandad"
	tukuilocal.datatext_bags = "Bolsas: "
	tukuilocal.datatext_friends = "Amigos"
	tukuilocal.datatext_online = "Conectados: "
	tukuilocal.datatext_armor = "Armadura"
	tukuilocal.datatext_earned = "Ganado:"
	tukuilocal.datatext_spent = "Gastado:"
	tukuilocal.datatext_deficit = "Balance:"
	tukuilocal.datatext_profit = "Beneficios:"
	tukuilocal.datatext_timeto = "Time to"
	tukuilocal.datatext_friendlist = "Lista de Amigos:"
	tukuilocal.datatext_playersp = "sp"
	tukuilocal.datatext_playerap = "ap"
	tukuilocal.datatext_playerhaste = "haste"
	tukuilocal.datatext_dps = "dps"
	tukuilocal.datatext_hps = "hps"
	tukuilocal.datatext_playerarp = "arp"
	tukuilocal.datatext_session = "Sesión: "
	tukuilocal.datatext_character = "Personaje: "
	tukuilocal.datatext_server = "Reino: "
	tukuilocal.datatext_totalgold = "Total: "
	tukuilocal.datatext_savedraid = "Mazmorras Registradas"
	tukuilocal.datatext_currency = "Moneda:"
	tukuilocal.datatext_fps = " fps & "
	tukuilocal.datatext_ms = " ms"
	tukuilocal.datatext_playercrit = " crit"
	tukuilocal.datatext_playerheal = " heal"
	tukuilocal.datatext_avoidancebreakdown = "Breakdown de Evitación"
	tukuilocal.datatext_lvl = "nivel"
	tukuilocal.datatext_boss = "boss"
	tukuilocal.datatext_miss = "Fallo"
	tukuilocal.datatext_dodge = "Esquiva"
	tukuilocal.datatext_block = "Bloqueo"
	tukuilocal.datatext_parry = "Parada"
	tukuilocal.datatext_playeravd = "avd: "
	tukuilocal.datatext_servertime = "Hora del servidor: "
	tukuilocal.datatext_localtime = "Hora Local: "
	tukuilocal.datatext_mitigation = "Mitigación por Nivel: "
	tukuilocal.datatext_healing = "Curación : "
	tukuilocal.datatext_damage = "Daño : "
	tukuilocal.datatext_honor = "Honor : "
	tukuilocal.datatext_killingblows = "Golpes de Gracia : "
	tukuilocal.datatext_ttstatsfor = "Estadísticas para "
	tukuilocal.datatext_ttkillingblows = "Golpes de Gracia :"
	tukuilocal.datatext_tthonorkills = "Golpes de Gracia con Honor :"
	tukuilocal.datatext_ttdeaths = "Muertes :"
	tukuilocal.datatext_tthonorgain = "Honor Ganado :"
	tukuilocal.datatext_ttdmgdone = "Daño Realizado :"
	tukuilocal.datatext_tthealdone = "Sanación Realizada :"
	tukuilocal.datatext_basesassaulted = "Bases Asaltadas:"
	tukuilocal.datatext_basesdefended = "Bases Defendidas:"
	tukuilocal.datatext_towersassaulted = "Torres Asaltadas:"
	tukuilocal.datatext_towersdefended = "Torres Defendidas:"
	tukuilocal.datatext_flagscaptured = "Banderas Capturadas:"
	tukuilocal.datatext_flagsreturned = "Banderas Devueltas:"
	tukuilocal.datatext_graveyardsassaulted = "Cementerios Asaltados:"
	tukuilocal.datatext_graveyardsdefended = "Cementerios Defendidos:"
	tukuilocal.datatext_demolishersdestroyed = "Catapultas Destruidas:"
	tukuilocal.datatext_gatesdestroyed = "Puertas Destruidas:"
	tukuilocal.datatext_totalmemusage = "Memoria Total Usada:"
	tukuilocal.datatext_control = "Controlado por:"
 
	tukuilocal.Slots = {
		[1] = {1, "Cabeza", 1000},
		[2] = {3, "Hombro", 1000},
		[3] = {5, "Pecho", 1000},
		[4] = {6, "Cintura", 1000},
		[5] = {9, "Muñeca", 1000},
		[6] = {10, "Manos", 1000},
		[7] = {7, "Piernas", 1000},
		[8] = {8, "Pies", 1000},
		[9] = {16, "Mano Derecha", 1000},
		[10] = {17, "Mano Izquierda", 1000},
		[11] = {18, "A Distancia", 1000}
	}
 
	tukuilocal.popup_disableui = "Tukui no funciona con esta resolución, ¿Quieres desactivar Tukui? (Pulsa cancelar si quieres probar otra resolución)"
	tukuilocal.popup_install = "Es la primera vez que usas Tukui V12 con este personaje. Debes recargar la Interfaz para ajustar las barras de acción, las variables y los marcos de chat."
	tukuilocal.popup_2raidactive = "Hay activos 2 estilos para banda, por favor selecciona uno."
 
	tukuilocal.merchant_repairnomoney = "¡No tienes suficiente dinero para reparar!"
	tukuilocal.merchant_repaircost = "Tus objetos han sido reparados por"
	tukuilocal.merchant_trashsell = "Has vendido toda la basura a cambio de"
 
	tukuilocal.goldabbrev = "|cffffd700g|r"
	tukuilocal.silverabbrev = "|cffc7c7cfs|r"
	tukuilocal.copperabbrev = "|cffeda55fc|r"
 
	tukuilocal.error_noerror = "Aún sin errores."
 
	tukuilocal.unitframes_ouf_offline = "Desconectado"
	tukuilocal.unitframes_ouf_dead = "Muerto"
	tukuilocal.unitframes_ouf_ghost = "Fantasma"
	tukuilocal.unitframes_ouf_lowmana = "Mana Bajo"
	tukuilocal.unitframes_ouf_threattext = "Amenaza en el objetivo:"
	tukuilocal.unitframes_ouf_offlinedps = "Desconectado"
	tukuilocal.unitframes_ouf_deaddps = "|cffff0000[Muerto]|r"
	tukuilocal.unitframes_ouf_ghostheal = "FANTASMA"
	tukuilocal.unitframes_ouf_deadheal = "MUERTO"
	tukuilocal.unitframes_ouf_gohawk = "GO HAWK"
	tukuilocal.unitframes_ouf_goviper = "GO VIPER"
	tukuilocal.unitframes_disconnected = "D/C"
 
	tukuilocal.tooltip_count = "Count"
 
	tukuilocal.bags_noslots = "¡no puedes comprar más espacios!"
	tukuilocal.bags_costs = "Costo: %.2f oro"
	tukuilocal.bags_buyslots = "Compra un nuevo espacio mediante /bags purchase yes"
	tukuilocal.bags_openbank = "Necesitas abrir primero el banco."
	tukuilocal.bags_sort = "Ordena tu bolsa, o tu banco si está abierto."
	tukuilocal.bags_stack = "Llena los montones incompletos en tu bolsa, o en tu banco si está abierto"
	tukuilocal.bags_buybankslot = "Compra un espacio en el banco. (Necesitas tener el banco abierto)"
	tukuilocal.bags_search = "Buscar"
	tukuilocal.bags_sortmenu = "Ordenar"
	tukuilocal.bags_sortspecial = "Orden Especial"
	tukuilocal.bags_stackmenu = "Amontonar"
	tukuilocal.bags_stackspecial = "Montón Especial"
	tukuilocal.bags_showbags = "Mostrar Bolsas"
	tukuilocal.bags_sortingbags = "Se ha acabado de ordenar."
	tukuilocal.bags_nothingsort= "No hay nada que ordenar."
	tukuilocal.bags_bids = "Usando las bolsas: "
	tukuilocal.bags_stackend = "Se ha acabado de amontonar."
	tukuilocal.bags_rightclick_search = "Right-click to search."
 
	tukuilocal.chat_invalidtarget = "Objetivo Invalido"
 
	tukuilocal.mount_wintergrasp = "Conquista De Invierno"
 
	tukuilocal.core_autoinv_enable = "Auto Invitar ON: invite"
	tukuilocal.core_autoinv_enable_c = "Auto Invitar ON: "
	tukuilocal.core_autoinv_disable = "Auto Invitar OFF"
	tukuilocal.core_wf_unlock = "Registro de Misiones Desbloqueado"
	tukuilocal.core_wf_lock = "Registro de Misiones Bloqueado"
	tukuilocal.core_welcome1 = "Bienvenido a |cffC495DDTukui|r versión "
	tukuilocal.core_welcome2 = "Escribe |cff00FFFF/uihelp|r para más información"
 
	tukuilocal.core_uihelp1 = "|cff00ff00Comandos Generales|r"
	tukuilocal.core_uihelp2 = "|cffFF0000/tracker|r - Tukui Arena Enemy Cooldown Tracker - Rastreador de Habilidades de enemigo para PVP, use poce memoria. (Icono solo)"
	tukuilocal.core_uihelp3 = "|cffFF0000/rl|r - Recarga la interfaz de usuario."
	tukuilocal.core_uihelp4 = "|cffFF0000/gm|r - Envía un ticket a un MJ o abre la ayuda."
	tukuilocal.core_uihelp5 = "|cffFF0000/frame|r - Detecta el marco bajo el cursor. (muy útil para editar Lua)"
	tukuilocal.core_uihelp6 = "|cffFF0000/heal|r - Activa el estilo de Sanador para Bandas."
	tukuilocal.core_uihelp7 = "|cffFF0000/dps|r - Activa el estilo Dps/Tanque para Bandas."
	tukuilocal.core_uihelp8 = "|cffFF0000/uf|r - Activa o desactiva los marcos móviles."
	tukuilocal.core_uihelp9 = "|cffFF0000/bags|r - Para ordenar, comprar espacios en el banco o amontonar objetos de tu inventario."
	tukuilocal.core_uihelp10 = "|cffFF0000/resetui|r - Restablece la configuración de Tukui de las cVar y el marco de chat."
	tukuilocal.core_uihelp11 = "|cffFF0000/rd|r - Desarmar Banda."
	tukuilocal.core_uihelp12 = "|cffFF0000/wf|r - Desbloquea el Registro de Misiones para moverlo."
	tukuilocal.core_uihelp13 = "|cffFF0000/mss|r - Mueve la barra de estados o totems."
	tukuilocal.core_uihelp15 = "|cffFF0000/ainv|r - Activa el Auto Invitar mediante una palabra. Puedes configurar tu propia palabra mediante el comando <code>/ainv mipalabra</code>"
	tukuilocal.core_uihelp14 = "(Desliza la rueda del ratón hacia arriba para ver los demás comandos)"
 
	tukuilocal.symbol_CLEAR = "Nada"
	tukuilocal.symbol_SKULL = "Calavera"
	tukuilocal.symbol_CROSS = "Cruz"
	tukuilocal.symbol_SQUARE = "Cuadrado"
	tukuilocal.symbol_MOON = "Luna"
	tukuilocal.symbol_TRIANGLE = "Triangulo"
	tukuilocal.symbol_DIAMOND = "Diamante"
	tukuilocal.symbol_CIRCLE = "Circulo"
	tukuilocal.symbol_STAR = "Estrella"
 
	tukuilocal.bind_combat = "No puedes asignar teclas en combate."
	tukuilocal.bind_saved = "La configuración de las teclas ha sido guardada."
	tukuilocal.bind_discard = "Se han descartado los cambios en la configuración de las teclas."
	tukuilocal.bind_instruct = "Coloca el cursor encima de cualquier botón para asignar una tecla. Presiona la tecla ESC o el botón derecho del ratón para quitar la asignación actual."
	tukuilocal.bind_save = "Guardar los cambios"
	tukuilocal.bind_discardbind = "Descargar los cambios"
 
	tukuilocal.hunter_unhappy = "Tu mascota está descontenta!"
	tukuilocal.hunter_content = "Tu mascota está contenta!"
	tukuilocal.hunter_happy = "Tu mascota está feliz!"
end