if TukuiDB.client == "zhTW" then

	tukuilocal.chat_BATTLEGROUND_GET = "[B]"
	tukuilocal.chat_BATTLEGROUND_LEADER_GET = "[B]"
	tukuilocal.chat_BN_WHISPER_GET = "From"
	tukuilocal.chat_GUILD_GET = "[G]"
	tukuilocal.chat_OFFICER_GET = "[O]"
	tukuilocal.chat_PARTY_GET = "[P]"
	tukuilocal.chat_PARTY_GUIDE_GET = "[P]"
	tukuilocal.chat_PARTY_LEADER_GET = "[P]"
	tukuilocal.chat_RAID_GET = "[R]"
	tukuilocal.chat_RAID_LEADER_GET = "[R]"
	tukuilocal.chat_RAID_WARNING_GET = "[W]"
	tukuilocal.chat_WHISPER_GET = "From"
	tukuilocal.chat_FLAG_AFK = "[AFK]"
	tukuilocal.chat_FLAG_DND = "[DND]"
	tukuilocal.chat_FLAG_GM = "[GM]"
	tukuilocal.chat_ERR_FRIEND_ONLINE_SS = "is now |cff298F00online|r"
	tukuilocal.chat_ERR_FRIEND_OFFLINE_S = "is now |cffff0000offline|r"
	
	tukuilocal.disband = "正在解散隊伍."
 
	tukuilocal.datatext_guild = "公會"
	tukuilocal.datatext_noguild = "沒有公會"
	tukuilocal.datatext_bags = "背包: "
	tukuilocal.datatext_friends = "好友"
	tukuilocal.datatext_online = "線上: "
	tukuilocal.datatext_armor = "耐久度"
	tukuilocal.datatext_earned = "賺取:"
	tukuilocal.datatext_spent = "花費:"
	tukuilocal.datatext_deficit = "赤字:"
	tukuilocal.datatext_profit = "利潤:"
	tukuilocal.datatext_timeto = "Time to"
	tukuilocal.datatext_friendlist = "好友名單:"
	tukuilocal.datatext_playersp = "法傷"
	tukuilocal.datatext_playerap = "強度"
	tukuilocal.datatext_playerhaste = "加速"
	tukuilocal.datatext_dps = "dps"
	tukuilocal.datatext_hps = "hps"
	tukuilocal.datatext_playerarp = "護甲穿透"
	tukuilocal.datatext_session = "本次概況: "
	tukuilocal.datatext_character = "角色: "
	tukuilocal.datatext_server = "伺服器: "
	tukuilocal.datatext_totalgold = "總額: "
	tukuilocal.datatext_savedraid = "已有進度的團隊副本"
	tukuilocal.datatext_currency = "兌換通貨:"
	tukuilocal.datatext_fps = " fps & "
	tukuilocal.datatext_ms = " ms"
	tukuilocal.datatext_playercrit = "% 致命"
	tukuilocal.datatext_playerheal = " 治療"
	tukuilocal.datatext_avoidancebreakdown = "免傷分析"
	tukuilocal.datatext_lvl = "等級"
	tukuilocal.datatext_boss = "首領"
	tukuilocal.datatext_miss = "未擊中"
	tukuilocal.datatext_dodge = "閃躲"
	tukuilocal.datatext_block = "格檔"
	tukuilocal.datatext_parry = "招架"
	tukuilocal.datatext_playeravd = "免傷: "
	tukuilocal.datatext_servertime = "伺服器時間: "
	tukuilocal.datatext_localtime = "本地時間: "
	tukuilocal.datatext_mitigation = "等級緩和: "
	tukuilocal.datatext_healing = "治療: "
	tukuilocal.datatext_damage = "傷害: "
	tukuilocal.datatext_honor = "榮譽: "
	tukuilocal.datatext_killingblows = "擊殺 : "
	tukuilocal.datatext_ttstatsfor = "狀態 "
	tukuilocal.datatext_ttkillingblows = "擊殺:"
	tukuilocal.datatext_tthonorkills = "榮譽擊殺:"
	tukuilocal.datatext_ttdeaths = "死亡:"
	tukuilocal.datatext_tthonorgain = "獲得榮譽:"
	tukuilocal.datatext_ttdmgdone = "傷害輸出:"
	tukuilocal.datatext_tthealdone = "治療輸出:"
	tukuilocal.datatext_basesassaulted = "基地突襲:"
	tukuilocal.datatext_basesdefended = "基地防禦:"
	tukuilocal.datatext_towersassaulted = "哨塔突襲:"
	tukuilocal.datatext_towersdefended = "哨塔防禦:"
	tukuilocal.datatext_flagscaptured = "佔領旗幟:"
	tukuilocal.datatext_flagsreturned = "交還旗幟:"
	tukuilocal.datatext_graveyardsassaulted = "墓地突襲:"
	tukuilocal.datatext_graveyardsdefended = "墓地防守:"
	tukuilocal.datatext_demolishersdestroyed = "石毀車摧毀:"
	tukuilocal.datatext_gatesdestroyed = "大門摧毀:"
	tukuilocal.datatext_totalmemusage = "總共記憶體使用:"
	tukuilocal.datatext_control = "Controlled by:"
 
	tukuilocal.Slots = {
		[1] = {1, "頭部", 1000},
		[2] = {3, "肩部", 1000},
		[3] = {5, "胸部", 1000},
		[4] = {6, "腰部", 1000},
		[5] = {9, "手腕", 1000},
		[6] = {10, "手", 1000},
		[7] = {7, "腿部", 1000},
		[8] = {8, "腳", 1000},
		[9] = {16, "主手", 1000},
		[10] = {17, "副手", 1000},
		[11] = {18, "遠程", 1000}
	}
 
	tukuilocal.popup_disableui = "Tukui並不支援此解析度, 你想要停用Tukui嗎? (若果您想要嘗試其他解析度, 請按取消)"
	tukuilocal.popup_install = "這個角色首次使用Tukui V12, 您必需先重載介面以完成設定"
 
	tukuilocal.merchant_repairnomoney = "您沒有足夠的金錢來修理!"
	tukuilocal.merchant_repaircost = "您的裝備已修理, 花費了"
	tukuilocal.merchant_trashsell = "您背包內的粗糙物品已被自動賣出, 您賺取了"
 
	tukuilocal.goldabbrev = "|cffffd700g|r"
	tukuilocal.silverabbrev = "|cffc7c7cfs|r"
	tukuilocal.copperabbrev = "|cffeda55fc|r"
 
	tukuilocal.error_noerror = "沒有錯誤"
 
	tukuilocal.unitframes_ouf_offline = "離線"
	tukuilocal.unitframes_ouf_dead = "死亡"
	tukuilocal.unitframes_ouf_ghost = "鬼魂"
	tukuilocal.unitframes_ouf_lowmana = "法力過低"
	tukuilocal.unitframes_ouf_threattext = "當前目標的仇恨:"
	tukuilocal.unitframes_ouf_offlinedps = "離線"
	tukuilocal.unitframes_ouf_deaddps = "|cffff0000[死亡]|r"
	tukuilocal.unitframes_ouf_ghostheal = "鬼魂"
	tukuilocal.unitframes_ouf_deadheal = "死亡"
	tukuilocal.unitframes_ouf_gohawk = "切換為雄鷹守護"
	tukuilocal.unitframes_ouf_goviper = "切換為蝮蛇守護"
	tukuilocal.unitframes_disconnected = "斷線"
 
	tukuilocal.tooltip_count = "數量"
 
	tukuilocal.bags_noslots = "不能再購買更多的背包欄位!"
	tukuilocal.bags_costs = "花費: %.2f 金"
	tukuilocal.bags_buyslots = "輸入 /bags purchase yes 以購買銀行背包欄位"
	tukuilocal.bags_openbank = "您需要先造訪您的銀行"
	tukuilocal.bags_sort = "將背包或銀行內的物品分類及排序"
	tukuilocal.bags_stack = "將背包或銀行內的不完整的物品堆疊重新堆疊"
	tukuilocal.bags_buybankslot = "購買銀行背包欄位. (需要造訪銀行)"
	tukuilocal.bags_search = "搜尋"
	tukuilocal.bags_sortmenu = "分類及排序"
	tukuilocal.bags_sortspecial = "分類及排序特殊物品"
	tukuilocal.bags_stackmenu = "堆疊"
	tukuilocal.bags_stackspecial = "堆疊特殊物品"
	tukuilocal.bags_showbags = "顯示背包"
	tukuilocal.bags_sortingbags = "分類及排序完成"
	tukuilocal.bags_nothingsort= "不需要分類"
	tukuilocal.bags_bids = "使用背包: "
	tukuilocal.bags_stackend = "重新堆疊完成"
	tukuilocal.bags_rightclick_search = "點擊右鍵以搜尋物品."
 
	tukuilocal.chat_invalidtarget = "無效的目標"
 
	tukuilocal.mount_wintergrasp = "冬握湖"
 
	tukuilocal.core_autoinv_enable = "啟用自動邀請: invite"
	tukuilocal.core_autoinv_enable_c = "自動邀請功能已啟用: "
	tukuilocal.core_autoinv_disable = "自動邀請功能已關閉"
	tukuilocal.core_wf_unlock = "解鎖任務追蹤"
	tukuilocal.core_wf_lock = "鎖定任務追蹤"
	tukuilocal.core_welcome1 = "歡迎使用 |cffC495DDTukui|r "
	tukuilocal.core_welcome2 = "輸入 |cff00FFFF/uihelp|r 以獲得更多資訊"
 
	tukuilocal.core_uihelp1 = "|cff00ff00基本指令|r"
	tukuilocal.core_uihelp2 = "|cffFF0000/tracker|r - Tukui 競技場敵方冷卻監視器 - 一個精簡的PvP冷卻監視器 (Icon only)"
	tukuilocal.core_uihelp3 = "|cffFF0000/rl|r - 重載您的使用者介面"
	tukuilocal.core_uihelp4 = "|cffFF0000/gm|r - 聯繫GM或開啟魔獸世界幫助訊息"
	tukuilocal.core_uihelp5 = "|cffFF0000/frame|r - 偵測您滑鼠位置上的框架名稱 (對於lua編制者非常有幫助)"
	tukuilocal.core_uihelp6 = "|cffFF0000/heal|r - 啟用治療的ouf介面"
	tukuilocal.core_uihelp7 = "|cffFF0000/dps|r - 啟用Dps/Tank的ouf介面"
	tukuilocal.core_uihelp8 = "|cffFF0000/uf|r - 啟用或停用可移動ouf框架"
	tukuilocal.core_uihelp9 = "|cffFF0000/bags|r - 分類及排序背包, 購買銀行背包欄位或重新堆疊背包/銀行內的物品"
	tukuilocal.core_uihelp10 = "|cffFF0000/resetui|r - 重置Tukui的設定"
	tukuilocal.core_uihelp11 = "|cffFF0000/rd|r - 解散團隊"
	tukuilocal.core_uihelp12 = "|cffFF0000/wf|r - 解鎖任務追蹤框架"
	tukuilocal.core_uihelp13 = "|cffFF0000/mss|r - 移動變形列和圖騰列"
	tukuilocal.core_uihelp14 = "(向上滾動以獲得更多命令 ...)"
	tukuilocal.core_uihelp15 = "|cffFF0000/ainv|r - 輸入關鍵字(預設:/ainv)以啟用密語自動邀請, 您可以自行設定關鍵字, 指令為/ainv 關鍵字"
 
	tukuilocal.symbol_CLEAR = "清除"
	tukuilocal.symbol_SKULL = "頭顱"
	tukuilocal.symbol_CROSS = "十字"
	tukuilocal.symbol_SQUARE = "方形"
	tukuilocal.symbol_MOON = "月亮"
	tukuilocal.symbol_TRIANGLE = "三角"
	tukuilocal.symbol_DIAMOND = "鑽石"
	tukuilocal.symbol_CIRCLE = "圈圈"
	tukuilocal.symbol_STAR = "星星"
 
	tukuilocal.bind_combat = "您不能在戰鬥中設定快捷鍵"
	tukuilocal.bind_saved = "所有快捷鍵修改已儲存"
	tukuilocal.bind_discard = "這次的快捷鍵修改已重設為上一次修改"
	tukuilocal.bind_instruct = "將滑鼠指向動作列上以綁定快捷鍵, 您可以按ESC或以右鍵點擊快捷列上任何一格以清除該位置的設定"
	tukuilocal.bind_save = "儲存"
	tukuilocal.bind_discardbind = "放棄"
 
	tukuilocal.hunter_unhappy = "你的寵物感到不高興!"
	tukuilocal.hunter_content = "你的寵物感到滿足!"
	tukuilocal.hunter_happy = "你的寵物感到高興!"
end