name: Wrath Bug Report
description: Report a bug in ElvUI for Wrath Classic
title: "[Wrath Bug Report] <Title here>"
labels: [':bug::question: Bug (Needs Investigation)', ':video_game: Wrath']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue you are having?
      description: Describe the issue and what was going on when it happened?
      placeholder: Give us an explaination of what was going on when the issue appeared.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: What do you think the expected behavior should have happened?
      placeholder: Try to explain what you expected the outcome to be.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened?
      description: Please try to be as descriptive as possible.
      placeholder: Try to explain what happened.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution/Workaround
      description: If you have any idea how we could solve it let us know.
      placeholder: "Make sure type the command: /edebug on then test."
    validations:
      required: false
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: If you have any errors, please put them here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: ElvUI Changelog & Troubleshooting
      description: By submitting this issue, you agree you followed our [Troubleshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28)
      options:
        - label: I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
          required: true
        - label: I have verfied ElvUI is up to date by checking /estatus.
          required: true
        - label: I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
          required: true
        - label: I have not read step six and I am just clicking all boxes.
        - label: I have verfied my issue doesn't exist in the default UI.
          required: true
        - label: I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.
          required: true
