ElvuiL = { }

-- general
ElvuiL.option_general = "General"
ElvuiL.option_general_uiscale = "Auto UI Scale"
ElvuiL.option_general_multisample = "Multisample protection (clean 1px border)"
ElvuiL.option_general_customuiscale = "UI Scale (if auto-scale is disabled)"
ElvuiL.option_general_embedright = "Addon to embed to right chat panel (Recount, Omen, Skada)"
ElvuiL.option_general_classtheme = "Class Color Theme"
ElvuiL.option_general_autocustomlagtolerance = "Automatically update the Blizzard Custom Lag Tolerance option to your latency."
ElvuiL.option_general_fontscale = "Master font scale"
ElvuiL.option_general_override = "Force a certain resolution size (Low, High)"
ElvuiL.option_general_layoutoverride = "Force load a unitframe layout, (Defaults: DPS, Heal)"

--Media
ElvuiL.option_media = "Media"
ElvuiL.option_media_font = "Font file path for main font"
ElvuiL.option_media_uffont = "Font file path for UnitFrame fonts"
ElvuiL.option_media_dmgfont = "Font file path for DMG Text font (Requires Restart)"
ElvuiL.option_media_normTex = "Texture file path for unitframe Health/Power texture"
ElvuiL.option_media_glowTex = "Texture file path for glow texture"
ElvuiL.option_media_bubbleTex = "Texture file path for combo point texture (Nameplates)"
ElvuiL.option_media_blank = "Texture file path for main UI Texture"
ElvuiL.option_media_bordercolor = "Color of non-unitframe borders"
ElvuiL.option_media_altbordercolor = "Color of unitframe borders"
ElvuiL.option_media_backdropcolor = "Color of backdrop on all frames"
ElvuiL.option_media_backdropfadecolor = "Color of faded backdrop on certain faded frames"
ElvuiL.option_media_buttonhover = "Texture file path for Button Hover texture on actionbuttons"
ElvuiL.option_media_valuecolor = "Color of Datatext values"
ElvuiL.option_media_raidicons = "Texture file path for raid icons"
ElvuiL.option_media_whisper = "Sound file path for whisper sound"
ElvuiL.option_media_warning = "Warning sound"
ElvuiL.option_media_glossy = "Glossy Bar Texture"
	
-- nameplate
ElvuiL.option_nameplates = "Nameplates"
ElvuiL.option_nameplates_enable = "Enable Nameplates"
ElvuiL.option_nameplates_enhancethreat = "Enable threat feature, automatically changes by your role"
ElvuiL.option_nameplates_showhealth = "Show health on nameplate"
ElvuiL.option_nameplates_combat = "Only show enemy nameplates in-combat"
ElvuiL.option_nameplates_goodcolor = "Good threat color, varies depending if your a tank or dps/heal"
ElvuiL.option_nameplates_badcolor = "Bad threat color, varies depending if your a tank or dps/heal"
ElvuiL.option_nameplates_transitioncolor = "Losing/Gaining threat color"
ElvuiL.option_nameplates_trackauras = "Track 'Your' debuffs on nameplates."
ElvuiL.option_nameplates_trackccauras = "Track 'CC' debuffs on nameplates."

-- addon skins
ElvuiL.option_skin = "Addon Skins"
ElvuiL.option_skin_kle = "KL Encounters"
ElvuiL.option_skin_omen = "Omen"
ElvuiL.option_skin_recount = "Recount"
ElvuiL.option_skin_skada = "Skada"
ElvuiL.option_hookkleright = "Force KLE's top bar anchor to be positioned above right chat frame"
 
-- classtimer
ElvuiL.option_classtimer = "Class Timer"
ElvuiL.option_classtimer_enable = "Enable Classtimer"
ElvuiL.option_classtimer_bar_height = "Bar Height"
ElvuiL.option_classtimer_bar_spacing = "Bar Spacing"
ElvuiL.option_classtimer_icon_position = "Icon Position (0-Left,1-Right,2-Outside Left,3-Outside Right)"
ElvuiL.option_classtimer_layout = "Layout (1-5)"
ElvuiL.option_classtimer_showspark = "Show Spark"
ElvuiL.option_classtimer_cast_suparator = "Cast Seperator"
ElvuiL.option_classtimer_classcolor = "Class Color"
ElvuiL.option_classtimer_debuffcolor = "Debuff Bar Color"
ElvuiL.option_classtimer_buffcolor = "Buff Bar Color"
ElvuiL.option_classtimer_proccolor = "Trinket/Proc Bar Color"

-- datatext
ElvuiL.option_datatext = "Data Text"
ElvuiL.option_datatext_24h = "Enable 24h time"
ElvuiL.option_datatext_localtime = "Use Local Time instead of Server Time"
ElvuiL.option_datatext_bg = "Enable Battleground Stats"
ElvuiL.option_datatext_guild = "Guild position (0 for disabled)"
ElvuiL.option_datatext_mem = "Memory position (0 for disabled)"
ElvuiL.option_datatext_bags = "Bags position (0 for disabled)"
ElvuiL.option_datatext_fontsize = "Font size of text"
ElvuiL.option_datatext_system = "Latency and FPS position (0 for disabled)"
ElvuiL.option_datatext_friend = "Friends position (0 for disabled)"
ElvuiL.option_datatext_time = "Time position (0 for disabled)"
ElvuiL.option_datatext_gold = "Gold position (0 for disabled)"
ElvuiL.option_datatext_dur = "Durability position (0 for disabled)"	
ElvuiL.option_datatext_stat1 = "Stat 1 for your role's position"
ElvuiL.option_datatext_stat2 = "Stat 2 for your role's position"
ElvuiL.option_datatext_hps = "Heal per second position (0 for disabled)"
ElvuiL.option_datatext_dps = "Damage per second position (0 for disabled)"

-- auras
ElvuiL.option_auras = "Auras"
ElvuiL.option_auras_minimapauras = "Enable auras by the minimap"
ElvuiL.option_auras_arenadebuffs = "Show only important debuffs inside arena/bgon party and raid frames"
ElvuiL.option_auras_auratimer = "Enable timer on auras"
ElvuiL.option_auras_targetaura = "Enable target auras"
ElvuiL.option_auras_focusdebuff = "Enable Focus debuffs"
ElvuiL.option_auras_playeraura = "Show auras on playerframe"
ElvuiL.option_auras_aurascale = "Aura text scale on auras"
ElvuiL.option_auras_totdebuffs = "Enable Target of Target debuffs"
ElvuiL.option_auras_playershowonlydebuffs = "Only show debuffs on playerframe (Must have show aura on playerframe)"
ElvuiL.option_auras_playerdebuffsonly = "Show only your debuffs, and CC debuffs on target  (inside auraFilter.lua to config)"
ElvuiL.option_auras_RaidUnitBuffWatch = "Enable buff watch on raid frames"
ElvuiL.option_auras_playtarbuffperrow = "Amount of Buffs/Debuffs in a row on the Player/Target frames"
ElvuiL.option_auras_smallbuffperrow = "Amount of Debuffs in a row on the TargetTarget/Focus frames"
ElvuiL.option_auras_buffindicatorsize = "Size of buff indicator icons on party/raid frames"

-- raidframes
ElvuiL.option_raidframes = "Raid Frames"
ElvuiL.option_raidframes_enable = "Enable Raid Frames"
ElvuiL.option_raidframes_gridonly = "Use 25 man raid frames in party"
ElvuiL.option_raidframes_healcomm = "Enable HealComm (Healer Layout Only)"
ElvuiL.option_raidframes_boss = "Enable Boss Unit Frames"
ElvuiL.option_raidframes_hpvertical = "Show health bar vertically for Grid layout (Healer Layout Only)"
ElvuiL.option_raidframes_enablerange = "Enable party/raid Range alpha display"
ElvuiL.option_raidframes_range = "Alpha on Party/Raid unit out of range"
ElvuiL.option_raidframes_maintank = "Enable Main Tank"
ElvuiL.option_raidframes_mainassist = "Enable Main Assist"
ElvuiL.option_raidframes_playerparty = "Show yourself in party"
ElvuiL.option_raidframes_hidenonmana = "Only show powerbar if unit has mana (Not Party Frames)"
ElvuiL.option_raidframes_fontsize = "Font size on raidframes"
ElvuiL.option_raidframes_scale = "Scale of raidframes (use decimals ex: 0.96)"
ElvuiL.option_raidframes_disableblizz = "Disable blizzard default party and raid frames"
ElvuiL.option_raidframes_griddps = "Display the DPS Layout in grid layout instead of a vertical layout (Not Party)"
ElvuiL.option_raidframes_partytarget = "Display party members target's (DPS Only)"

-- castbar
ElvuiL.option_castbar = "Castbar"
ElvuiL.option_castbar_nointerruptcolor = "Color for castbar if you cannot interrupt"
ElvuiL.option_castbar_castbarcolor = "Color for castbar"
ElvuiL.option_castbar_castbar = "Enable cast bar"
ElvuiL.option_castbar_latency = "Show cast bar latency"
ElvuiL.option_castbar_icon = "Show icons on cast bar"
ElvuiL.option_castbar_castermode = "Enable larger castbar, for casters"
ElvuiL.option_castbar_classcolor = "Color player's castbar by classcolor"

-- unit frames
ElvuiL.option_unitframes_unitframes = "Unit Frames"
ElvuiL.option_unitframes_healthcolor = "Color of Health Bars"
ElvuiL.option_unitframes_combatfeedback = "Combat Feedback on player and target"
ElvuiL.option_unitframes_totalhpmp = "Display total on health/power"
ElvuiL.option_unitframes_aurawatch = "Show buffs in corners"
ElvuiL.option_unitframes_saveperchar = "Save unit frames position per character"
ElvuiL.option_unitframes_playeraggro = "Enable aggro display on yourself"
ElvuiL.option_unitframes_smooth = "Enable smooth bar"
ElvuiL.option_unitframes_portrait = "Enable portraits on player and target"
ElvuiL.option_unitframes_enable = "Enable Elvui Unit Frames"
ElvuiL.option_unitframes_enemypower = "Enable Power display on player only"
ElvuiL.option_unitframes_raidaggro = "Enable aggro display"
ElvuiL.option_unitframes_symbol = "Show symbols on party/raid"
ElvuiL.option_unitframes_threatbar = "Enable threat bar"
ElvuiL.option_unitframes_focus = "Enable Focus target"
ElvuiL.option_unitframes_manalow = "Low mana indicator"
ElvuiL.option_unitframes_classcolor = "Color unitframes by class"
ElvuiL.option_unitframes_SwingBar = "Enable swing bar (DPS Layout Only)"
ElvuiL.option_unitframes_DebuffHighlight = "Color frames by debuff type if dispellable"
ElvuiL.option_unitframes_mendpet = "Show Mend Pet bar on PetFrame (DPS LAYOUT)"
ElvuiL.option_unitframes_fontsize = "Font Size"
ElvuiL.option_unitframes_unitframes_poweroffset = "Offset of the powerbar on the frame (0 for no offset)"
ElvuiL.option_unitframes_classbar = "Enable Classbar (TotemBar, RuneBar, HolyBar, SoulshardBar, EclipseBar)"
ElvuiL.option_unitframes_healthbackdropcolor = "Backdrop color of health on all unitframes"
ElvuiL.option_unitframes_healthcolorbyvalue = "Color Healthbars by Health Remaining"
ElvuiL.option_unitframes_combat = "Fade unitframes while not in-combat"
ElvuiL.option_unitframes_pettarget = "Display your pet's target (DPS Only)"
ElvuiL.option_unitframes_portraitonhealthbar = "Display character portrait overlaying healthbar (Portraits must be on)"

-- frame sizes
ElvuiL.option_framesizes = "UnitFrame Sizes"
ElvuiL.option_framesizes_playtarwidth = "Width of the Player/Target frames"
ElvuiL.option_framesizes_playtarheight = "Height of the Player/Target frames"
ElvuiL.option_framesizes_smallwidth = "Width of the TargetTarget/Focus/FocusTarget/PlayersPet frames"
ElvuiL.option_framesizes_smallheight = "Height of the TargetTarget/Focus/FocusTarget/PlayersPet frames"
ElvuiL.option_framesizes_arenabosswidth = "Width of the Arena/Boss frames"
ElvuiL.option_framesizes_arenabossheight = "Height of the Arena/Boss frames"
ElvuiL.option_framesizes_assisttankwidth = "Width of the MainTank/MainAssist frames"
ElvuiL.option_framesizes_assisttankheight = "Height of the MainTank/MainAssist frames"
	
-- loot
ElvuiL.option_loot = "Loot"
ElvuiL.option_loot_enableloot = "Enable loot window"
ElvuiL.option_loot_autogreed = "Enable auto-greed for green item at max level"
ElvuiL.option_loot_enableroll = "Enable item roll window"
 
-- tooltip
ElvuiL.option_tooltip = "Tooltip"
ElvuiL.option_tooltip_enable = "Enable tooltip"
ElvuiL.option_tooltip_hidecombat = "Hide bottom-right tooltip in combat"
ElvuiL.option_tooltip_hidebutton = "Hide tooltip on action bar buttons"
ElvuiL.option_tooltip_hideuf = "Hide tooltip on unit frames"
ElvuiL.option_tooltip_cursor = "Enable cursor tooltip"
ElvuiL.option_tooltip_combatraid = "Only hide in combat when in a raid"
ElvuiL.option_tooltip_colorreaction = "Always color tooltip border and healthbar by reaction"
ElvuiL.option_tooltip_xOfs = "X-Offset of the tooltip (-x = Left, +x = Right)"
ElvuiL.option_tooltip_yOfs = "Y-Offset of the tooltip (-y = Down, +y = Up)"
ElvuiL.option_tooltip_itemid = "Display Item ID"
ElvuiL.option_tooltip_whotargetting = "Display who is targetting the unit that is in your party/raid."

-- others
ElvuiL.option_others = "Others"
ElvuiL.option_others_bg = "Enable Auto-Release in battleground"
ElvuiL.option_others_autosell = "Auto sell gray items"
ElvuiL.option_others_autorepair = "Auto Repair items"
ElvuiL.option_others_autoinvite = "Enable Auto-Invite (Friends and Guildmates)"
ElvuiL.option_others_enablemap = "Enable Map"
ElvuiL.option_others_errorhide = "Hide spamming error at the middle of your screen"
ElvuiL.option_others_announceinterrupt = "Announce your interrupts in party chat"
ElvuiL.option_others_bagenable = "Enable all in one bag"

-- reminder
ElvuiL.option_reminder = "Aura Warning"
ElvuiL.option_reminder_enable = "Enable player aura warning"
ElvuiL.option_reminder_sound = "Enable a warning sound for aura warning"
ElvuiL.option_reminder_RaidBuffReminder = "Enable RaidBuffReminder Bar below minimap"

-- action bar
ElvuiL.option_actionbar = "Action Bars"
ElvuiL.option_actionbar_hidess = "Hide Shapeshift bar or Totem bar"
ElvuiL.option_actionbar_showgrid = "Always show Grid on action bar"
ElvuiL.option_actionbar_enable = "Enable Elvui action bar"
ElvuiL.option_actionbar_rb = "Enable right bar on mouseover"
ElvuiL.option_actionbar_hk = "Show hotkey on buttons"
ElvuiL.option_actionbar_ssmo = "Shapeshift bar or Totem bar on mouseover"
ElvuiL.option_actionbar_bottompetbar = "Position pet bar below the main actionbar, moves main actionbar up"
ElvuiL.option_actionbar_buttonsize = "Size of the main action buttons"
ElvuiL.option_actionbar_buttonspacing = "Spacing of the main action buttons"
ElvuiL.option_actionbar_petbuttonsize = "Size of the pet/stance action buttons"
ElvuiL.option_actionbar_swaptopbottombar = "Swap the top and bottom actionbar positions"
ElvuiL.option_actionbar_macrotext = "Display macro text on actionbuttons"
ElvuiL.option_actionbar_verticalstance = "Vertical Stance Bar"
ElvuiL.option_actionbar_microbar = "Display MicroBar"
ElvuiL.option_actionbar_mousemicro = "MicroBar on mouseover"

-- arena
ElvuiL.option_arena = "Arena"
ElvuiL.option_arena_st = "Enable enemy spell tracker in arena"
ElvuiL.option_arena_uf = "Enable arena unit frames"
 
-- cooldowns
ElvuiL.option_cooldown = "Cooldowns"
ElvuiL.option_cooldown_enable = "Enable cooldown number on buttons"
ElvuiL.option_cooldown_th = "Turn cooldown number to the expiration color at X value"
ElvuiL.option_cooldown_expiringcolor = "Expiration Color"
ElvuiL.option_cooldown_secondscolor = "Seconds Color"
ElvuiL.option_cooldown_minutescolor = "Minutes Color"
ElvuiL.option_cooldown_hourscolor = "Hours Color"
ElvuiL.option_cooldown_dayscolor = "Days Color"

-- chat
ElvuiL.option_chat = "Chat"
ElvuiL.option_chat_bubbles = "Skin Chat Bubbles"
ElvuiL.option_chat_enable = "Enable Elvui Chat"
ElvuiL.option_chat_whispersound = "Play sound when receiving private message"
ElvuiL.option_chat_chatwidth = "Width of the chat windows"
ElvuiL.option_chat_backdrop = "Show backdrop behind chat window"
ElvuiL.option_chat_chatheight = "Height of chat frames"
ElvuiL.option_chat_fadeoutofuse = "Fade chat text when not in use"
ElvuiL.option_chat_sticky = "Sticky some chat channels when opening new chat edit"
ElvuiL.option_chat_rightchat = "Display right chat window"
ElvuiL.option_chat_combathide = "Slide chatframe out during combat ('Left', 'Right', 'Both', or 'NONE')"

--Debug
ElvuiL.option_debug = "Debug Mode"
ElvuiL.option_debug_enabled = "Enable debug mode, not recommended!"
ElvuiL.option_debug_events = "Print events to chat window"

-- buttons
ElvuiL.option_button_reset = "Reset UI"
ElvuiL.option_button_load = "Apply Changes"
ElvuiL.option_button_close = "Close"
ElvuiL.option_setsavedsetttings = "Set settings Per-Character"
ElvuiL.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
ElvuiL.option_resetall = "Are you sure you want to reset all of your settings to Default?"
ElvuiL.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
ElvuiL.option_makeselection = "You must make a selection before you can continue to config."