if GetLocale() == "frFR" then
	-- general
	ElvuiL.option_general = "Général" --"General"
	ElvuiL.option_general_uiscale = "Echelle automatique de l'UI" --"Auto UI Scale"
	ElvuiL.option_general_multisample = "Protection multicouche (bordure propre de 1px)" --"Multisample protection (clean 1px border)"
	ElvuiL.option_general_customuiscale = "Echelle de l'UI (si l'échelle automatique est désactivée)" --"UI Scale (if auto-scale is disabled)"
	ElvuiL.option_general_embedright = "Addon placé dans le panneau de discussion droit (Recount, Omen, Skada)" --"Addon to embed to right chat panel (Recount, Omen, Skada)"
	ElvuiL.option_general_classtheme = "Bordure de couleur de classe." --"Color border colors to your class"
	ElvuiL.option_general_autocustomlagtolerance = "Ajuste automatiquement la barre de latence Blizzard avec votre propre latence."
 
	--Media
	ElvuiL.option_media = "Media" --"Media"
	ElvuiL.option_media_font = "Police principale" --"Font file path for main font"
	ElvuiL.option_media_uffont = "Police des cadres unités" --"Font file path for UnitFrame fonts"
	ElvuiL.option_media_dmgfont = "Police des dégâts (Requiert de relancer le jeu)" --"Font file path for DMG Text font (Requires Restart)"
	ElvuiL.option_media_normTex = "Texture pour la vie/puissance" --"Texture file path for unitframe Health/Power texture"
	ElvuiL.option_media_glowTex = "Texture brillante" --"Texture file path for glow texture"
	ElvuiL.option_media_bubbleTex = "Texture pour les points de combos (barre de vie)" --"Texture file path for combo point texture (Nameplates)"
	ElvuiL.option_media_blank = "Texture principale" --"Texture file path for main UI Texture"
	ElvuiL.option_media_bordercolor = "Couleur des bordures des cadres hors unité" --"Color of non-unitframe borders"
	ElvuiL.option_media_altbordercolor = "Couleur des bordures des cadres d'unités" --"Color of unitframe borders"
	ElvuiL.option_media_backdropcolor = "Couleur de l'arrière-plan" --"Color of backdrop on all frames"
	ElvuiL.option_media_backdropfadecolor = "Couleur de l'arrière-plan pour les cadres translucides" --"Color of faded backdrop on certain faded frames"
	ElvuiL.option_media_buttonhover = "Texture du passage de la souris sur les barres d'actions." --"Texture file path for Button Hover texture on actionbuttons"
	ElvuiL.option_media_valuecolor = "Couleur des variables textes" --"Color of Datatext values"
	ElvuiL.option_media_raidicons = "Textures des icones de raid" --"Texture file path for raid icons"
	ElvuiL.option_media_whisper = "Alerte son des chuchotements" --"Sound file path for whisper sound"
	ElvuiL.option_media_warning = "Son d'avertissement" --"Warning sound"
	ElvuiL.option_media_glossy = "Glossy Bar Texture"
	
	-- nameplate
	ElvuiL.option_nameplates = "Barres d'info" --"Nameplates"
	ElvuiL.option_nameplates_enable = "Activer les barres d'info des ennemis" --"Enable Nameplates"
	ElvuiL.option_nameplates_enhancethreat = "Activer la gestion d'aggro, change automatiquement selon votre role:" --"Enable threat feature, automatically changes by your roll:  Tank - Green (aggro) Red (noaggro) DPS - Green (noaggro) Red (aggro)"
	ElvuiL.option_nameplates_showhealth = "Montrer la vie sur les barres d'info des ennemis" --"Show health on nameplate"
 	ElvuiL.option_nameplates_combat = "Afficher les barres d'infos des ennemis seulement en combat"
 	ElvuiL.option_nameplates_goodcolor = "Bonne couleur de menace, dépend de si vous êtes un tank ou dps / heal"
	ElvuiL.option_nameplates_badcolor = "Mauvaise couleur de menace, dépend de si vous êtes un tank ou dps / heal"
	ElvuiL.option_nameplates_transitioncolor = "Perte / Gain de couleur de menace"
	
	-- addon skins
	ElvuiL.option_skin = "Skin d'addon" --"Addon Skins"
	ElvuiL.option_skin_kle = "KL Encounters"
	ElvuiL.option_skin_omen = "Omen"
	ElvuiL.option_skin_recount = "Recount"
	ElvuiL.option_skin_skada = "Skada"
 
	-- classtimer
	ElvuiL.option_classtimer = "Class Timer"
	ElvuiL.option_classtimer_enable = "Activer Class timer" --"Enable Classtimer"
	ElvuiL.option_classtimer_bar_height = "Hauteur de la barre" --"Bar Height"
	ElvuiL.option_classtimer_bar_spacing = "Espacement entre les barres" --"Bar Spacing"
	ElvuiL.option_classtimer_icon_position = "Position de l'icone (0-gauche, 1-droite, 2-extérieur gauche, 3-extérieur droit" --"Icon Position (0-Left,1-Right,2-Outside Left,3-Outside Right)"
	ElvuiL.option_classtimer_layout = "Mode (1-5)" --"Layout (1-5)"
	ElvuiL.option_classtimer_showspark = "Montrer une lueur" --"Show Spark"
	ElvuiL.option_classtimer_cast_suparator = "Séparateur de cast" --"Cast Seperator"
	ElvuiL.option_classtimer_classcolor = "Couleur de classe" --"Class Color"
	ElvuiL.option_classtimer_debuffcolor = "Couleur de la barre des debuffs" --"Debuff Bar Color"
	ElvuiL.option_classtimer_buffcolor = "Couleur de la barre des buffs" --"Buff Bar Color"
	ElvuiL.option_classtimer_proccolor = "Couleur de la barre des bijoux/procs" --"Trinket/Proc Bar Color"
 
	-- datatext
	ElvuiL.option_datatext = "Variables textes" --"Data Text"
	ElvuiL.option_datatext_24h = "Activer le mode 24h" --"Enable 24h time"
	ElvuiL.option_datatext_localtime = "Utiliser l'heure locale à la place de l'heure du serveur" --"Use Local Time instead of Server Time"
	ElvuiL.option_datatext_bg = "Activer les statistiques de champ de bataille" --"Enable Battleground Stats"
	ElvuiL.option_datatext_guild = "Position de la guilde (0 pour désactiver)" --"Guild position (0 for disabled)"
	ElvuiL.option_datatext_mem = "Position de la mémoire (0 pour désactiver)" --"Memory position (0 for disabled)"
	ElvuiL.option_datatext_bags = "Position des sacs (0 pour désactiver)" --"Bags position (0 for disabled)"
	ElvuiL.option_datatext_fontsize = "Taille du texte" --"Font size of text"
	ElvuiL.option_datatext_system = "Position de l'IPS et de la latence (0 pour désactiver)" --"Latency and FPS position (0 for disabled)"
	ElvuiL.option_datatext_friend = "Position des amis (0 pour désactiver)" --"Friends position (0 for disabled)"
	ElvuiL.option_datatext_time = "Position de l'heure (0 pour désactiver)" --"Time position (0 for disabled)"
	ElvuiL.option_datatext_gold = "Position de l'or (0 pour désactiver)" --"Gold position (0 for disabled)"
	ElvuiL.option_datatext_dur = "Position de la durabilité (0 pour désactiver)" --"Durability position (0 for disabled)"
	ElvuiL.option_datatext_stat1 = "Position de la statistique principale" --"Stat 1 for your role's position"
	ElvuiL.option_datatext_stat2 = "Position de la statistique secondaire" --"Stat 2 for your role's position"
	ElvuiL.option_datatext_dps = "Position Dégâts par seconde"
	ElvuiL.option_datatext_hps = "Position Heal par seconde"
	
	-- auras
	ElvuiL.option_auras = "Auras"
	ElvuiL.option_auras_minimapauras = "Activer les auras à coté de la minimap" --"Enable auras by the minimap"
	ElvuiL.option_auras_arenadebuffs = "Montrer seulement les debuffs importants en arene/bg" --"Show only important debuffs inside arena/bgon party and raid frames"
	ElvuiL.option_auras_auratimer = "Activer les timers des auras" --"Enable timer on auras"
	ElvuiL.option_auras_targetaura = "Activer les auras de la cible" --"Enable target auras"
	ElvuiL.option_auras_focusdebuff = "Activer les debuffs du focus" --"Enable Focus debuffs"
	ElvuiL.option_auras_playeraura = "Montrer les auras sur le cadre du joueur" --"Show auras on playerframe"
	ElvuiL.option_auras_aurascale = "Taille du texte des auras" --"Aura text scale on auras"
	ElvuiL.option_auras_totdebuffs = "Activer les debuffs de la cible de la cible" --"Enable Target of Target debuffs"
	ElvuiL.option_auras_playershowonlydebuffs = "Montrer uniquement les debuffs sur le cadre du joueur (nécessite d'avoir les auras d'activées sur le cadre du joueur)" --"Only show debuffs on playerframe (Must have show aura on playerframe)"
	ElvuiL.option_auras_playerdebuffsonly = "Montrer seulement vos debuffs et les CC sur la cible  (configuration dans auraFilter.lua)" --"Show only your debuffs, and CC debuffs on target  (inside auraFilter.lua to config)"
	ElvuiL.option_auras_RaidUnitBuffWatch = "Activer l'affichage des buffs sur l'interface de raid." --"Enable buff watch on raid frames"
	ElvuiL.option_auras_playtarbuffperrow = "Nombre de Buffs/Debuffs sur une ligne au dessus des barres d'unités du Joueur/de la Cible"
	ElvuiL.option_auras_smallbuffperrow = "Nombre de Buffs/Debuffs sur une ligne au dessus des barres d'unités de la Cible de la Cible/du Focus"
	
	-- raidframes
	ElvuiL.option_raidframes = "Interface de raid" --"Raid Frames"
	ElvuiL.option_raidframes_enable = "Activer l'interface de raid" --"Enable Raid Frames"
	ElvuiL.option_raidframes_gridonly = "Utiliser l'interface de raid 25 joueurs en groupe" --"Use 25 man raid frames in party"
	ElvuiL.option_raidframes_healcomm = "Activer les soins entrants (Interface heal seulement)" --"Enable HealComm (Healer Layout Only)"
	ElvuiL.option_raidframes_boss = "Activer les cadres des boss" --"Enable Boss Unit Frames"
	ElvuiL.option_raidframes_hpvertical = "Montrer les barres de vies verticalements (Interface heal seulement)" --"Show health bar vertically for Grid layout (Healer Layout Only)"
	ElvuiL.option_raidframes_enablerange = "Activer l'affichage des portées via transparence" --"Enable party/raid Range alpha display"
	ElvuiL.option_raidframes_range = "Transparence sur les unités du groupe/raid hors portée" --"Alpha on Party/Raid unit out of range"
	ElvuiL.option_raidframes_maintank = "Activer les tanks principaux" --"Enable Main Tank"
	ElvuiL.option_raidframes_mainassist = "Activer Soigneurs principaux" --"Enable Main Assist"
	ElvuiL.option_raidframes_playerparty = "Se montrer dans les cadres de groupe" --"Show yourself in party"
	ElvuiL.option_raidframes_hidenonmana = "Montrer la barre de puissance si l'unité à de la mana (pas sur l'interface de groupe)" --"Only show powerbar if unit has mana (Not Party Frames)"
	ElvuiL.option_raidframes_fontsize = "Taille de la police de l'interface de raid" --"Font size on raidframes"
	ElvuiL.option_raidframes_scale = "Echelle de l'interface raid (utiliser des décimaux ex: 0.96)" --"Scale of raidframes (use decimals ex: 0.96)"
	ElvuiL.option_raidframes_disableblizz = "Désactiver l'interface de groupe/raid par défaut de blizzard" --"Disable blizzard default party and raid frames"
 	ElvuiL.option_raidframes_griddps = "Affiche l'interface Heal (en rectangle) au lieu de l'interface DPS ( en ligne). Seulement en mode Raid."
	
	-- castbar
	ElvuiL.option_castbar = "Barre de sort" --"Castbar"
	ElvuiL.option_castbar_nointerruptcolor = "Couleur de la barre de sort si non interruptible" --"Color for castbar if you cannot interrupt"
	ElvuiL.option_castbar_castbarcolor = "Couleur de la barre de sort" --"Color for castbar"
	ElvuiL.option_castbar_castbar = "Activer la barre de sort" --"Enable cast bar"
	ElvuiL.option_castbar_latency = "Montrer la latence sur la barre de sort" --"Show cast bar latency"
	ElvuiL.option_castbar_icon = "Montrer l'icone sur la barre de sort" --"Show icons on cast bar"
	ElvuiL.option_castbar_castermode = "Grande barre de sort, pour les lanceurs de sorts" --"Enable larger castbar, for casters"
	ElvuiL.option_castbar_classcolor = "Barre de sort de la couleur de de classe" --"Color player's castbar by classcolor"
 
	-- unit frames
	ElvuiL.option_unitframes_unitframes = "Cadre d'unité" --"Unit Frames"
	ElvuiL.option_unitframes_healthcolor = "Couleur de la barre de vie" --"Color of Health Bars"
	ElvuiL.option_unitframes_combatfeedback = "Textes de combat sur le joueur et la cible" --"Combat Feedback on player and target"
	ElvuiL.option_unitframes_totalhpmp = "Afficher la vie/puissance totale" --"Display total on health/power"
	ElvuiL.option_unitframes_aurawatch = "Montrer les buffs dans les coins" --"Show buffs in corners"
	ElvuiL.option_unitframes_saveperchar = "Mémoriser la position des cadres par personnage" --"Save unit frames position per character"
	ElvuiL.option_unitframes_playeraggro = "Activer l'affichage de l'aggro sur vous" --"Enable aggro display on yourself"
	ElvuiL.option_unitframes_smooth = "Activer l'effet smooth" --"Enable smooth bar"
	ElvuiL.option_unitframes_portrait = "Activer les portraits sur le joueur et la cible" --"Enable portraits on player and target"
	ElvuiL.option_unitframes_enable = "Activer les cadres d'unités de Elvui" --"Enable Elvui Unit Frames"
	ElvuiL.option_unitframes_enemypower = "Enable Power display on player only" --"Enable Power display on enemy only"
	ElvuiL.option_unitframes_raidaggro = "Activer l'affichage de l'aggro" --"Enable aggro display"
	ElvuiL.option_unitframes_symbol = "Montrer les symboles sur le groupe/raid" --"Show symbols on party/raid"
	ElvuiL.option_unitframes_threatbar = "Activer la barre de menace" --"Enable threat bar"
	ElvuiL.option_unitframes_focus = "Activer la cible du focus" --"Enable Focus target"
	ElvuiL.option_unitframes_manalow = "Avertissement mana faible" --"Low mana indicator"
	ElvuiL.option_unitframes_classcolor = "Cadres de couleur de classe" --"Color unitframes by class"
	ElvuiL.option_unitframes_SwingBar = "Activer la barre de swing (Interface DPS seulement)" --"Enable swing bar (DPS Layout Only)"
	ElvuiL.option_unitframes_DebuffHighlight = "Colorier les cadres par type de débuff si dissipable" --"Color frames by debuff type if dispellable"
	ElvuiL.option_unitframes_mendpet = "Montrer la barre de soin du familier (Interface DPS)" --"Show Mend Pet bar on PetFrame (DPS LAYOUT)"
	ElvuiL.option_unitframes_fontsize = "Taille de la police" --"Font Size"
	ElvuiL.option_unitframes_unitframes_poweroffset = "Décalage de la barre de pouvoir par rapport à la barre d'unité" --"Offset of the powerbar on the frame (0 for no offset)"
	ElvuiL.option_unitframes_classbar = "Active les barres de classes (Barre de totem, Barre de pouvoir runique, Barre Sacrée, Barre des fragments d'âme, Barre d'Eclipse)"
	ElvuiL.option_unitframes_healthbackdropcolor = "Couleur de fond de toutes les barres d'unités" --"Backdrop color of health on all unitframes"
	ElvuiL.option_unitframes_healthcolorbyvalue = "Couleur de la barre de vie selon la vie restante."
	ElvuiL.option_unitframes_combat = "Estomper les portraits d'unités hors-combat"
		
	-- frame sizes
	ElvuiL.option_framesizes = "Taille des barres d'unités"
	ElvuiL.option_framesizes_playtarwidth = "Largeur des barres d'unités du Joueur/de la Cible"
	ElvuiL.option_framesizes_playtarheight = "Hauteur des barres d'unités du Joueur/de la Cible"
	ElvuiL.option_framesizes_smallwidth = "Largeur des barres d'unités de la Cible de la Cible/du Focus/de la Cible du Focus/du Familier du Joueur"
	ElvuiL.option_framesizes_smallheight = "Hauteur des barres d'unités de la Cible de la Cible/du Focus/de la Cible du Focus/du Familier du Joueur"
	ElvuiL.option_framesizes_arenabosswidth = "Largeur des barres d'unités d'Arène/des Boss"
	ElvuiL.option_framesizes_arenabossheight = "Hauteur des barres d'unités d'Arène/des Boss"
	ElvuiL.option_framesizes_assisttankwidth = "Largeur des barres d'unités des Tanks Principaux/des Assists Principaux"
	ElvuiL.option_framesizes_assisttankheight = "Hauteur des barres d'unités des Tanks et des Soigneurs principaux" --"Height of the MainTank/MainAssist frames"
	
	-- loot
	ElvuiL.option_loot = "Loot"
	ElvuiL.option_loot_enableloot = "Activer la fenêtre de loot" --"Enable loot window"
	ElvuiL.option_loot_autogreed = "Auto-cupidité pour les item verts au niveau maximum" --"Enable auto-greed for green item at max level"
	ElvuiL.option_loot_enableroll = "Activer la fenêtre pour le rand d'item" --"Enable item roll window"
 
	-- tooltip
	ElvuiL.option_tooltip = "Infobulles"
	ElvuiL.option_tooltip_enable = "Activer les infobulles" --"Enable tooltip"
	ElvuiL.option_tooltip_hidecombat = "Masquer l'infobulle en bas à droite en combat" --"Hide bottom-right tooltip in combat"
	ElvuiL.option_tooltip_hidebutton = "Masquer l'infobulle des boutons des barres d'actions" --"Hide tooltip on action bar buttons"
	ElvuiL.option_tooltip_hideuf = "Masquer les infobules pour les cadres d'unités" --"Hide tooltip on unit frames"
	ElvuiL.option_tooltip_cursor = "Activer l'infobulle au curseur" --"Enable cursor tooltip"
	ElvuiL.option_tooltip_combatraid = "Masquer seulement en combat et en raid" --"Only hide in combat when in a raid"
	ElvuiL.option_tooltip_colorreaction = "Toujours colorier la bordure de l'infobulle et la barre de vie par réaction" --"Always color tooltip border and healthbar by reaction"
	ElvuiL.option_tooltip_xOfs = "X-Offset de l'infobulle (-x = gauche, +x = droite)" --"X-Offset of the tooltip (-x = Left, +x = Right)"
	ElvuiL.option_tooltip_yOfs = "Y-Offset de l'infobulle (-y = descendre, +y = monter)" --"Y-Offset of the tooltip (-y = Down, +y = Up)"
	ElvuiL.option_tooltip_itemid = "Display Item ID"
	ElvuiL.option_tooltip_itemid = "Affiche l'ID de l'objet"
	
	-- others
	ElvuiL.option_others = "Divers" --"Others"
	ElvuiL.option_others_bg = "Libérer automatiquement en BG" --"Enable Auto-Release in battleground"
	ElvuiL.option_others_autosell = "Vente automatique des objets gris" --"Auto sell gray items"
	ElvuiL.option_others_autorepair = "Réparation automatique" --"Auto Repair items"
	ElvuiL.option_others_autoinvite = "Activer l'auto-invite (Amis et guilde)" --"Enable Auto-Invite (Friends and Guildmates)"
	ElvuiL.option_others_enablemap = "Activer la carte" --"Enable Map"
	ElvuiL.option_others_errorhide = "Masquer les erreurs au milieu de l'écran" --"Hide spamming error at the middle of your screen"
	ElvuiL.option_others_spincam = "Faire pivoter la camera quand absent" --"Spin camera while AFK"
	ElvuiL.option_others_bagenable = "Activer les sacs Elvui" --"Enable all in one bag"
 
	-- reminder
	ElvuiL.option_reminder = "Avertissement des auras" --"Aura Warning"
	ElvuiL.option_reminder_enable = "Activer l'avertissement des auras du joueur" --"Enable player aura warning"
	ElvuiL.option_reminder_sound = "Activer le son pour les avertissement d'aura" --"Enable a warning sound for aura warning"
	ElvuiL.option_reminder_RaidBuffReminder = "Activer la barre de RaidBuffReminder sous la minimap" --"Enable RaidBuffReminder Bar below minimap"
 
	-- action bar
	ElvuiL.option_actionbar = "Barres d'actions" --"Action Bars"
	ElvuiL.option_actionbar_hidess = "Masquer la barre de changeforme / totem" --"Hide Shapeshift bar or Totem bar"
	ElvuiL.option_actionbar_showgrid = "Toujours montrer Grid dans la barre d'action" --"Always show Grid on action bar"
	ElvuiL.option_actionbar_enable = "Activer les barres d'actions de Elvui" --"Enable Elvui action bar"
	ElvuiL.option_actionbar_rb = "Activer l'affichage des barres de droite en mouseover" --"Enable right bar on mouseover"
	ElvuiL.option_actionbar_hk = "Montrer les raccourcis" --"Show hotkey on buttons"
	ElvuiL.option_actionbar_ssmo = "Barre de changeforme et de totem en mouseover" --"Shapeshift bar or Totem bar on mouseover"
	ElvuiL.option_actionbar_bottompetbar = "Positionner la barre de familier sous la barre d'action principale, ceci déplace la barre d'action principale vers le haut"
	ElvuiL.option_actionbar_buttonsize = "Taille des boutons de la barre d'action"
	ElvuiL.option_actionbar_buttonspacing = "Espace entre les boutons de la barre d'action"
	ElvuiL.option_actionbar_petbuttonsize = "Taille de la barre d'action du familier / de position"
	ElvuiL.option_actionbar_swaptopbottombar = "Intervertir les positions des 2 barres d'actions en bas."
	
	-- arena
	ElvuiL.option_arena = "Arène" --"Arena"
	ElvuiL.option_arena_st = "Activer le tracker des sorts ennemis" --"Enable enemy spell tracker in arena"
	ElvuiL.option_arena_uf = "Activer l'interface d'arène" --"Enable arena unit frames"
 
	-- cooldowns
	ElvuiL.option_cooldown = "Cooldowns" --"Cooldowns"
	ElvuiL.option_cooldown_enable = "Activer les cooldowns sur les boutons" --"Enable cooldown number on buttons"
	ElvuiL.option_cooldown_th = "Passer en couleur d'expiration à la valeur X" --"Turn cooldown number to the expiration color at X value"
	ElvuiL.option_cooldown_expiringcolor = "Couleur d'expiration" --"Expiration Color"
	ElvuiL.option_cooldown_secondscolor = "Couleur des secondes" --"Seconds Color"
	ElvuiL.option_cooldown_minutescolor = "Couleur des minutes" --"Minutes Color"
	ElvuiL.option_cooldown_hourscolor = "Couleur des heures" --"Hours Color"
	ElvuiL.option_cooldown_dayscolor = "Couleur des jours" --"Days Color"
 
	-- chat
	ElvuiL.option_chat = "Chat" --"Chat"
	ElvuiL.option_chat_bubbles = "Skin des bulles de discussions" --"Skin Chat Bubbles"
	ElvuiL.option_chat_enable = "Activer le chat de Elvui" --"Enable Elvui Chat"
	ElvuiL.option_chat_whispersound = "Jouer un son quand un chuchotement est reçu" --"Play sound when receiving private message"
	ElvuiL.option_chat_chatwidth = "Largeur de la fenêtre de chat" --"Width of the chat windows"
	ElvuiL.option_chat_backdrop = "Arrière-plan pour les fenêtres de chat" --"Show backdrop behind chat window"
	ElvuiL.option_chat_chatheight = "Hauteur de la fenêtre de chat" --"Height of chat frames"
	ElvuiL.option_chat_fadeoutofuse = "Masquer le chat quand pas utilisé" --"Fade chat text when not in use"
	ElvuiL.option_chat_sticky = "Vérouiller certains cannaux de chat à l'ouverture d'une nouvelle fenêtre." --"Sticky some chat channels when opening new chat edit"
 
	-- buttons
	ElvuiL.option_button_reset = "Réinitialiser" --"Reset UI"
	ElvuiL.option_button_load = "Activer les changements" --"Apply Changes"
	ElvuiL.option_button_close = "Fermer" --"Close"
	ElvuiL.option_setsavedsetttings = "Activer les paramètres par personnage" --"Set settings Per-Character"
	ElvuiL.option_resetchar = "Etes-vous sur de vouloir réinitialiser les paramètres de votre personnage ?" --"Are you sure you want to reset your character's settings to match your default settings?"
	ElvuiL.option_resetall = "Etes vous sur de vouloir tout réinitialiser ?" --"Are you sure you want to reset all of your settings to Default?"
	ElvuiL.option_perchar = "Etes vous sur de vouloir annuler/passer à des paramêtres par personnage ?" --"Are you sure you want to change to or from 'Per Char Settings'?"
	ElvuiL.option_makeselection = "Vous devez faire un choix pour continuer." --"You must make a selection before you can continue to config."
end