if GetLocale() == "deDE" then
	-- general
	ElvuiL.option_general = "Allgemein"
	ElvuiL.option_general_uiscale = "Automatische Interface Skalierung"
	ElvuiL.option_general_multisample = "Multisample Schutz (Saubere 1px Ränder)"
	ElvuiL.option_general_customuiscale = "Interface Skalierung (falls Automatische Interface Skalierung deaktiviert ist)"
	ElvuiL.option_general_embedright = "Addon in den rechten Chat einfügen (Recount, Omen, Skada)"
	ElvuiL.option_general_classtheme = "Rahmenfarbe nach Klasse färben"
	ElvuiL.option_general_autocustomlagtolerance = "Automatische Anpassung der Blizzard Custom Lag Toleranz an deine Latenz."
	ElvuiL.option_general_fontscale = "Hauptschriftskalierung"
	ElvuiL.option_general_override = "Erzwinge eine bestimmte Auflösung (Low, High)"
	ElvuiL.option_general_layoutoverride = "Erzwinge ein bestimmtes Layout der Einheitenfenster, (DPS, Heal)"
	
	--Media
	ElvuiL.option_media = "Medien"
	ElvuiL.option_media_font = "Dateipfad für die Hauptschriftart"
	ElvuiL.option_media_uffont = "Dateipfad für die Einheitenfenster Schrift"
	ElvuiL.option_media_dmgfont = "Dateipfad für die DMG Schrift (benötigt Neustart)"
	ElvuiL.option_media_normTex = "Texturpfad für die Einheitfenster Lebens-/Kraft-Textur"
	ElvuiL.option_media_glowTex = "Texturpfad für die hervorgehobenen Texturen"
	ElvuiL.option_media_bubbleTex = "Texturpfad für die Kombopunkte Textur (Namensplaketten)"
	ElvuiL.option_media_blank = "Texturpfad für die Haupt Interface Textur"
	ElvuiL.option_media_bordercolor = "Farbe der nicht-Einheitenfenster Rahmen"
	ElvuiL.option_media_altbordercolor = "Farbe der Einheitenfenster Rahmen"
	ElvuiL.option_media_backdropcolor = "Hintergrundfarbe für alle Frames"
	ElvuiL.option_unitframes_healthbackdrop = "Aktiviere Farbe für verblassende Hintergründe, andernfalls wird 20% der aktuellen Gesundheitsfarbe verwendet."
	ElvuiL.option_media_backdropfadecolor = "Farbe für verblassende Hintergründe bei einigen verblassten Fenstern"
	ElvuiL.option_media_buttonhover = "Texturpfad für die Mouse-Over-Textur auf den Aktionsknöpfen"
	ElvuiL.option_media_valuecolor = "Farbe der Infotext Werte"
	ElvuiL.option_media_raidicons = "Texturpfad für die Raid Icons"
	ElvuiL.option_media_whisper = "Soundpfad für den Flüsterton"
	ElvuiL.option_media_warning = "Warnton"
	ElvuiL.option_media_glossy = "Glänzende Leistentextur"
 
	-- nameplate
	ElvuiL.option_nameplates = "Namensplaketten"
	ElvuiL.option_nameplates_enable = "Aktiviere Namensplaketten"
	ElvuiL.option_nameplates_enhancethreat = "Aktiviere Bedrohungsanzeige, ändert sich automatisch je nach deiner Rolle"
	ElvuiL.option_nameplates_showhealth = "Zeige Leben auf den Namensplaketten"
 	ElvuiL.option_nameplates_combat = "Zeige gegnerische Namensplaketten nur im Kampf"
 	ElvuiL.option_nameplates_goodcolor = "Bedrohung im grünen Bereich, variiert abhängig davon, ob man Tank oder DPS/Heal ist"
	ElvuiL.option_nameplates_badcolor = "Bedrohung im roten Bereich, variiert abhängig davon, ob man Tank oder DPS/Heal ist"
	ElvuiL.option_nameplates_transitioncolor = "Bedrohung verlieren/erhalten Farbe"
	ElvuiL.option_nameplates_trackauras = "Verfolge 'Deine' debuffs auf den Namensplaketten."
	ElvuiL.option_nameplates_trackccauras = "Verfolge 'CC' debuffs auf den Namensplaketten."
	-- addon skins
	ElvuiL.option_skin = "Addon-Skins"
	ElvuiL.option_skin_kle = "KL Encounters"
	ElvuiL.option_skin_omen = "Omen"
	ElvuiL.option_skin_recount = "Recount"
	ElvuiL.option_skin_skada = "Skada"
	ElvuiL.option_hookkleright = "Erzwingt die Position von KLE am oberem Leistenanker über dem rechten Chatfenster"
 
	-- classtimer
	ElvuiL.option_classtimer = "Klassentimer"
	ElvuiL.option_classtimer_enable = "Aktiviert den Klassentimer"
	ElvuiL.option_classtimer_bar_height = "Leisten Höhe"
	ElvuiL.option_classtimer_bar_spacing = "Leisten Abstand"
	ElvuiL.option_classtimer_icon_position = "Symbol Position (0-Links,1-Rechts,2-Außen Links,3-Außen Rechts)"
	ElvuiL.option_classtimer_layout = "Layout (1-5)"
	ElvuiL.option_classtimer_showspark = "Zeige Funke"
	ElvuiL.option_classtimer_cast_suparator = "Zaubertrenner"
	ElvuiL.option_classtimer_classcolor = "Klassenfarbe"
	ElvuiL.option_classtimer_debuffcolor = "Farbe der Schwächungszauber Leiste"
	ElvuiL.option_classtimer_buffcolor = "Farbe der Stärkungszauber Leiste"
	ElvuiL.option_classtimer_proccolor = "Trinket/Proc Leisten Farbe"
 
	-- datatext
	ElvuiL.option_datatext = "Infotext"
	ElvuiL.option_datatext_24h = "Aktiviere 24-Stunden Zeitanzeige"
	ElvuiL.option_datatext_localtime = "Zeige Lokale Zeit, anstelle von Server Zeit"
	ElvuiL.option_datatext_bg = "Aktiviere Schlachtfeld Anzeige"
	ElvuiL.option_datatext_guild = "Gilden Position (0 zum ausschalten)"
	ElvuiL.option_datatext_mem = "Speichernutzung Position (0 zum ausschalten)"
	ElvuiL.option_datatext_bags = "Taschen Position (0 zum ausschalten)"
	ElvuiL.option_datatext_fontsize = "Schriftgröße des Infotextes"
	ElvuiL.option_datatext_system = "Latenz und FPS Position (0 zum ausschalten)"
	ElvuiL.option_datatext_friend = "Freunde Position (0 zum ausschalten)"
	ElvuiL.option_datatext_time = "Zeit Position (0 zum ausschalten)"
	ElvuiL.option_datatext_gold = "Gold Position (0 zum ausschalten)"
	ElvuiL.option_datatext_dur = "Haltbarkeit Position (0 zum ausschalten)"
	ElvuiL.option_datatext_stat1 = "Stat 1 für die Position deiner Rolle"
	ElvuiL.option_datatext_stat2 = "Stat 2 für die Position deiner Rolle"
	ElvuiL.option_datatext_dps = "Schaden pro Sekunde Position (0 zum ausschalten)"
	ElvuiL.option_datatext_hps = "Heilung pro Sekunde Position (0 zum ausschalten)"
 
	-- auras
	ElvuiL.option_auras = "Stärkungszauber"
	ElvuiL.option_auras_minimapauras = "Aktiviere Stärkungs- und Schwächungszauber an der Minimap"
	ElvuiL.option_auras_arenadebuffs = "Zeige nur wichtige Schwächungszauber in Arena-/Schlachtfeld-, Gruppen- und Schlachtzugsrahmen"
	ElvuiL.option_auras_auratimer = "Aktiviere Dauer auf Stärkungs- und Schwächungszaubern"
	ElvuiL.option_auras_targetaura = "Aktiviere Stärkungs- und Schwächungszauber auf dem Ziel"
	ElvuiL.option_auras_focusdebuff = "Aktiviere Schwächungszauber auf dem Fokusziel"
	ElvuiL.option_auras_playeraura = "Aktiviere Stärkungs- und Schwächungszauber auf dem Spieler Einheitenfenster"
	ElvuiL.option_auras_aurascale = "Text-Skalierung auf  Stärkungs-/Schwächungszaubern"
	ElvuiL.option_auras_totdebuffs = "Aktiviere Ziel vom Ziel Schwächungszauber"
	ElvuiL.option_auras_playershowonlydebuffs = "Zeige nur Debuffs auf dem Spielerframe (Benötigt Auraanzeige auf Spielerframe)"
	ElvuiL.option_auras_playerdebuffsonly = "Zeige nur Deine und CC debuffs auf dem Ziel  (konfigurierbar innerhalb auraFilter.lua)"
	ElvuiL.option_auras_RaidUnitBuffWatch = "Aktiviere die Anzeige für Stärkungszauber auf den Raidframes"
	ElvuiL.option_auras_playtarbuffperrow = "Anzahl von Stärkungs/Schwächungszauber in einer Reihe auf dem Spieler/Ziel Einheitenfenster"
	ElvuiL.option_auras_smallbuffperrow = "Anzahl von Stärkungs/Schwächungszauber in einer Reihe auf dem Ziel des Ziels/Fokus Einheitenfenster"
	ElvuiL.option_auras_buffindicatorsize = "Größe der Buff-Anzeigesymbole auf den Gruppen-/Schlachtzugsfenstern"
	
	-- raidframes
	ElvuiL.option_raidframes = "Schlachtzugsfenster"
	ElvuiL.option_raidframes_enable = "Aktiviere Schlachtzugsfenster"
	ElvuiL.option_raidframes_gridonly = "Aktiviere das 25man Schlachtzugsfenster für  normale Gruppen"
	ElvuiL.option_raidframes_healcomm = "Aktiviere HealComm (Nur Heiler Layout)"
	ElvuiL.option_raidframes_boss = "Aktiviere Bossanzeigen"
	ElvuiL.option_raidframes_hpvertical = "Zeige Lebensleiste vertikal für das Grid-Layout (Nur Heiler Layout)"
	ElvuiL.option_raidframes_enablerange = "Aktivere Reichweiten Anzeige auf Gruppen-/Schlachtzugsfenstern"
	ElvuiL.option_raidframes_range = "Transparenz der Schlachtzug- und Gruppenfenster wenn außer Reichweite"
	ElvuiL.option_raidframes_maintank = "Haupt Tank Anzeige aktivieren"
	ElvuiL.option_raidframes_mainassist = "Hauptassistent Anzeige aktivieren"
	ElvuiL.option_raidframes_playerparty = "Zeige dich selbst in der Gruppe"
	ElvuiL.option_raidframes_hidenonmana = "Kraftleiste nur anzeigen wenn Spieler Mana besitzt (Nicht Gruppen Anzeige)"
	ElvuiL.option_raidframes_fontsize = "Schriftgröße für Schlachtzugsfenster"
	ElvuiL.option_raidframes_scale = "Skalierung der Schlachtzugsfenster (benutze Dezimalstellen z.B.: 0.96)"
	ElvuiL.option_raidframes_disableblizz = "Deaktiviere Standard Blizzard Gruppen und Raidanzeige"
 	ElvuiL.option_raidframes_griddps = "Zeige das DPS-Layout im Grid-Layout anstatt im vertikalen Layout (Nicht Gruppen)"
	ElvuiL.option_raidframes_partytarget = "Ziele der Gruppenmitglieder anzeigen (nur DPS)"
	
	-- castbar
	ElvuiL.option_castbar = "Zauberleiste"
	ElvuiL.option_castbar_nointerruptcolor = "Farbe der Zauberleiste wenn nicht unterbrechbar"
	ElvuiL.option_castbar_castbarcolor = "Farbe für die Zauberleiste"
	ElvuiL.option_castbar_castbar = "Aktiviere Zauberleiste"
	ElvuiL.option_castbar_latency = "Zeige Zauberleisten Latenz"
	ElvuiL.option_castbar_icon = "Zeige Icons auf der Zauberleiste"
	ElvuiL.option_castbar_playerwidth = "Breite der Zauberleiste des Spielers"
	ElvuiL.option_castbar_castermode = "Aktiviere größere Zauberleiste für Zauberklassen"
	ElvuiL.option_castbar_classcolor = "Zauberleistenfarbe nach Klasse färben"
 
	-- unit frames
	ElvuiL.option_unitframes_unitframes = "Einheitenfenster"
	ElvuiL.option_unitframes_healthcolor = "Farbe der Lebensleiste"
	ElvuiL.option_unitframes_combatfeedback = "Kampfmeldungen auf Spieler und Ziel"
	ElvuiL.option_unitframes_totalhpmp = "Zeige gesamtes Leben/Kraft an"
	ElvuiL.option_unitframes_aurawatch = "Zeige Stärkungszauber in den Ecken"
	ElvuiL.option_unitframes_saveperchar = "Speichere Einheitenfenster Position für jeden Charakter"
	ElvuiL.option_unitframes_playeraggro = "Aktiviere Bedrohungsanzeige auf dir selbst"
	ElvuiL.option_unitframes_smooth = "Aktiviere flüssigere Leistenänderungen"
	ElvuiL.option_unitframes_portrait = "Zeige Portraits für Spieler und Ziel an"
	ElvuiL.option_unitframes_enable = "Aktiviere Elvui Einheitenfenster"
	ElvuiL.option_unitframes_enemypower = "Aktiviere Kraftanzeige nur beim Spieler"
	ElvuiL.option_unitframes_raidaggro = "Aktiviere Bedrohungsanzeige auf Raidframes"
	ElvuiL.option_unitframes_symbol = "Zeige Symbole auf Gruppen und Raidframes"
	ElvuiL.option_others_threatbar = "Aktiviere Bedrohungsleiste"
	ElvuiL.option_unitframes_focus = "Aktiviere Fokus Ziel"
	ElvuiL.option_unitframes_manalow = "Wenig Mana Indikator"
	ElvuiL.option_unitframes_classcolor = "Farbe der Einheitenfenster nach Klassenfarbe"
	ElvuiL.option_unitframes_SwingBar = "Aktiviere Schlagtimer (Nur DPS Layout)"
	ElvuiL.option_unitframes_DebuffHighlight = "Einheitenfenster nach Schwächungszauberfarbe färben, wenn entzauberbar"
	ElvuiL.option_unitframes_mendpet = "Zeige Tier Heilen auf Begleiter Frame (DPS Layout)"
	ElvuiL.option_unitframes_fontsize = "Schriftgröße"
	ElvuiL.option_unitframes_unitframes_poweroffset = "Versetzung der Kraftleiste zum Einheitenfenster (0 für keine Versetzung)"
	ElvuiL.option_unitframes_classbar = "Aktiviere Klassenleiste (Totemleiste, Runenleiste, Heiligleiste, Seelensplitterleiste, Finsternisleiste)"
	ElvuiL.option_unitframes_healthbackdropcolor = "Hintergrundfarbe der Gesundheitsleiste aller Einheitenfenster"
 	ElvuiL.option_unitframes_healthcolorbyvalue = "Färbe den Lebensbalken nach verbleibenden Leben"
	ElvuiL.option_unitframes_combat = "Einheitenfenster ausblenden, wenn nicht im Kampf"
	ElvuiL.option_unitframes_pettarget = "Ziel deines Begleiters anzeigen (nur DPS)"
	ElvuiL.option_unitframes_portraitonhealthbar = "Zeige das Portrait über der Gesundheitsleiste an (Portrait muss aktiviert sein)"
	
	-- frame sizes
	ElvuiL.option_framesizes = "Einheitenfenstergrößen"
	ElvuiL.option_framesizes_playtarwidth = "Breite der Spieler/Ziel Einheitenfenster"
	ElvuiL.option_framesizes_playtarheight = "Höhe der Spieler/Ziel Einheitenfenster"
	ElvuiL.option_framesizes_smallwidth = "Breite der Ziel des Ziels/Fokus/Fokus Ziel/Spieler Begleiter Einheitenfenster"
	ElvuiL.option_framesizes_smallheight = "Höhe der Ziel des Ziels/Fokus/Fokus Ziel/Spieler Begleiter Einheitenfenster"
	ElvuiL.option_framesizes_arenabosswidth = "Breite der Arena/Boss Einheitenfenster"
	ElvuiL.option_framesizes_arenabossheight = "Höhe der Arena/Boss Einheitenfenster"
	ElvuiL.option_framesizes_assisttankwidth = "Breite der Haupttank/Hauptassistent Einheitenfenster"
	ElvuiL.option_framesizes_assisttankheight = "Höhe der Haupttank/Hauptassistent Einheitenfenster"
 
	-- loot
	ElvuiL.option_loot = "Beute"
	ElvuiL.option_loot_enableloot = "Aktiviere Beutefenster"
	ElvuiL.option_loot_autogreed = "Aktiviere automatischen Gier-Wurf für grüne Gegenstände auf Maximalen Level"
	ElvuiL.option_loot_enableroll = "Aktiviere Würfelfenster"
 
	-- tooltip
	ElvuiL.option_tooltip = "Tooltip"
	ElvuiL.option_tooltip_enable = "Aktiviere Tooltip"
	ElvuiL.option_tooltip_hidecombat = "Verstecke unteren rechten Tooltip im Kampf"
	ElvuiL.option_tooltip_hidebutton = "Verstecke Tooltips auf Aktionsleisten"
	ElvuiL.option_tooltip_hideuf = "Verstecke Tooltips auf Einheitenfenster"
	ElvuiL.option_tooltip_cursor = "Tooltip am Mauszeiger anzeigen"
	ElvuiL.option_tooltip_combatraid = "Verstecke Tooltip im Kampf nur in einem Schlachtzug"
	ElvuiL.option_tooltip_colorreaction = "Tooltip Rand- und Gesundheitfarbe immer nach Reaktion einstellen"
	ElvuiL.option_tooltip_xOfs = "X-Versatz des Tooltips (-x = Links, +x = Rechts)"
	ElvuiL.option_tooltip_yOfs = "Y-Versatz des Tooltips (-y = Runter, +y = Hoch)"
	ElvuiL.option_tooltip_itemid = "Anzeige der Item ID"
	ElvuiL.option_tooltip_whotargetting = "Zeige an, wer die Eihneit, die in deiner Gruppe/Raid ist, ins Ziel nimmt."
	
	-- others
	ElvuiL.option_others = "Sonstiges"
	ElvuiL.option_others_bg = "Aktiviere automatisches Freilassen im Schlachtfeld"
	ElvuiL.option_others_autosell = "Automatisch graue Gegenstände verkaufen"
	ElvuiL.option_others_autorepair = "Automatisch reparieren"
	ElvuiL.option_others_autoinvite = "Einladungen von Freunden und Gildenmitgliedern automatisch annehmen"
	ElvuiL.option_others_enablemap = "Aktiviere Karte"
	ElvuiL.option_others_errorhide = "Verstecke spam Fehlermeldungen in der Mitte des Bildschirms"
	ElvuiL.option_others_announceinterrupt = "Melde deine verwendeten Unterbrechnungsfähigkeiten im Gruppen-Chat"
	
	ElvuiL.option_others_bagenable = "Aktiviere All-in-one Tasche"
 
	-- reminder
	ElvuiL.option_reminder = "Stärkungszauber Warnung"
	ElvuiL.option_reminder_enable = "Aktiviere Stärkungszauber Warnung auf dem Spieler"
	ElvuiL.option_reminder_sound = "Aktiviere Warnton für die Stärkungszauber Warnung"
	ElvuiL.option_reminder_RaidBuffReminder = "Aktiviere Schlachtzugsbuff-Erinnerungsleiste unter der Minimap"
 
	-- action bar
	ElvuiL.option_actionbar = "Aktionsleisten"
	ElvuiL.option_actionbar_hidess = "Verstecke Gestaltenwandler- oder Totemleiste"
	ElvuiL.option_actionbar_showgrid = "Rahmen auf Aktionsleisten immer anzeigen"
	ElvuiL.option_actionbar_enable = "Aktiviere Elvui Aktionsleisten"
	ElvuiL.option_actionbar_rb = "Aktiviere rechte Aktionsleisten bei Mouseover"
	ElvuiL.option_actionbar_hk = "Zeige Tastenbelegung auf den Buttons"
	ElvuiL.option_actionbar_ssmo = "Gestaltenwandler- oder Totemleiste nur bei Mouseover anzeigen"
	ElvuiL.option_actionbar_bottompetbar = "Setzt die Begleiterleiste unter die Aktionsleiste 1 und schiebt diese nach oben"
	ElvuiL.option_actionbar_buttonsize = "Größe der Aktionsleisten Buttons"
	ElvuiL.option_actionbar_buttonspacing = "Abstand der Aktionsleisten Buttons"
	ElvuiL.option_actionbar_petbuttonsize = "Größe der Begleiter/Haltungs Aktionsleisten Buttons"
	ElvuiL.option_actionbar_swaptopbottombar = "Tausche die untere und obere Aktionsleiste"
	ElvuiL.option_actionbar_macrotext = "Makrotexte auf den Aktionsleisten Buttons anzeigen"
	ElvuiL.option_actionbar_verticalstance ="Vertikale Haltungsleiste"
	ElvuiL.option_actionbar_microbar = "Zeige die MicroBar an"
	ElvuiL.option_actionbar_mousemicro = "Zeige die MicroBar bei mouseover an"
	-- arena
	ElvuiL.option_arena = "Arena"
	ElvuiL.option_arena_st = "Aktiviere gegnerischen Zauberverfolger in der Arena"
	ElvuiL.option_arena_uf = "Aktiviere Elvui-Arena Einheitenfenster"
 
	-- cooldowns
	ElvuiL.option_cooldown = "Abklingzeiten"
	ElvuiL.option_cooldown_enable = "Aktiviere Abklingzeiten Zahlen auf den Buttons"
	ElvuiL.option_cooldown_th = "Färbe Anzeige der Abklingzeiten ab Wert X nach Ablauffarbe"
	ElvuiL.option_cooldown_expiringcolor = "Ablauf Farbe"
	ElvuiL.option_cooldown_secondscolor = "Sekunden Farbe"
	ElvuiL.option_cooldown_minutescolor = "Minuten Farbe"
	ElvuiL.option_cooldown_hourscolor = "Stunden Farbe"
	ElvuiL.option_cooldown_dayscolor = "Tage Farbe"
 
	-- chat
	ElvuiL.option_chat = "Chat"
	ElvuiL.option_chat_bubbles = "Aktiviere den Skin für die Sprechblasen"
	ElvuiL.option_chat_enable = "Aktiviere Elvui Chat"
	ElvuiL.option_chat_whispersound = "Beim Empfang von Flüsternachrichten Ton abspielen"
	ElvuiL.option_chat_chatwidth = "Breite der Chatfenster"
	ElvuiL.option_chat_backdrop = "Zeige Hintergrund hinter dem Chat"
	ElvuiL.option_chat_chatheight = "Höhe der Chat Fenster"
	ElvuiL.option_chat_fadeoutofuse = "Chat Text verblassen lassen"
	ElvuiL.option_chat_sticky = "Behalte einige Chatchannel wenn ein neuer Chat eröffnet wird"
	ElvuiL.option_chat_rightchat = "Rechtes Chatfenster anzeigen"
	ElvuiL.option_chat_combathide = "Chatfenster während des Kampfes rausfahren ('Left', 'Right', 'Both', oder 'None'"
	
	--Debug
	ElvuiL.option_debug = "Debug Mode"
	ElvuiL.option_debug_enabled = "Aktivieren des debug mode, nicht empfohlen!"
	ElvuiL.option_debug_events = "Schreibe die events in das Chatfenster"
	
	-- buttons
	ElvuiL.option_button_reset = "Zurücksetzen"
	ElvuiL.option_button_load = "Anwenden"
	ElvuiL.option_button_close = "Schließen"
	ElvuiL.option_setsavedsetttings = "Einstellungen pro Charakter speichern"
	ElvuiL.option_resetchar = "Bist du sicher, dass du die Einstellungen für diesen Charakter auf Standard zurücksetzen willst?"
	ElvuiL.option_resetall = "Bist du sicher, dass du alle Einstellungen auf Standard zurücksetzen willst?"
	ElvuiL.option_perchar = "Bist du sicher, dass du die Einstellung für 'Einstellungen pro Charakter' wechseln willst?"
	ElvuiL.option_makeselection = "Sie müssen erst eine Auswahl treffen, bevor Sie mit den Einstellungen fortfahren können."
end