if GetLocale() == "esES" then
	-- general
	ElvuiL.option_general = "General"
	ElvuiL.option_general_uiscale = "Escala automática de la interfaz"
	ElvuiL.option_general_multisample = "Protección frente al multimuestreo (borde de 1px limpio)"
	ElvuiL.option_general_customuiscale = "Escala de la interfaz (si la escala automática está desactivada)"
	ElvuiL.option_general_embedright = "Addon que se ajustará en el panel de chat derecho (Recount, Omen, Skada)"
	ElvuiL.option_general_classtheme = "Colorear los bordes del color de tu clase"
	ElvuiL.option_general_autocustomlagtolerance = "Actualizar automaticamente la Tolerancia de Latencia de Blizzard segun tu Latencia."
	ElvuiL.option_general_fontscale = "Escala maestra de Fuente"
	
	--Media
	ElvuiL.option_media = "Medios"
	ElvuiL.option_media_font = "Ruta de la fuente que será usada como fuente principal"
	ElvuiL.option_media_uffont = "Ruta de la fuente que será usada en los marcos de vida/poder"
	ElvuiL.option_media_dmgfont = "Ruta de la fuente que se usará como fuente de daño (requiere reinicio)"
	ElvuiL.option_media_normTex = "Ruta de la textura que se usará en las barras de vida/poder"
	ElvuiL.option_media_glowTex = "Ruta de la textura que se usará como brillo"
	ElvuiL.option_media_bubbleTex = "Ruta de la textura que se usará en los puntos de combo (placas de nombre)"
	ElvuiL.option_media_blank = "Ruta de la textura que se usará como textura principal"
	ElvuiL.option_media_bordercolor = "Color para los bordes generales"
	ElvuiL.option_media_altbordercolor = "Color para los bordes de los marcos de vida/poder"
	ElvuiL.option_media_backdropcolor = "Color para el fondo de todos los marcos"
	ElvuiL.option_media_backdropfadecolor = "Color para los fondos diluídos de ciertos marcos"
	ElvuiL.option_media_buttonhover = "Ruta de la textura que se superpone en los botones de las barras de acción"
	ElvuiL.option_media_valuecolor = "Color de los textos de datos"
	ElvuiL.option_media_raidicons = "Ruta de la textura para los iconos de banda"
	ElvuiL.option_media_whisper = "Archivos de sonido que se usará al recibir un susurro"
	ElvuiL.option_media_warning = "Sonido de alerta"
	ElvuiL.option_media_glossy = "Textura del brillo de las barras"

	-- nameplate
	ElvuiL.option_nameplates = "Placas de nombre"
	ElvuiL.option_nameplates_enable = "Activar placas de nombre"
	ElvuiL.option_nameplates_enhancethreat = "Activar visor de amenaza, cambia automáticamente según tu rol: \n Tanque - Verde (aggro) Rojo (noaggro) DPS - Verde (noaggro) Rojo (aggro)"
	ElvuiL.option_nameplates_showhealth = "Mostrar vida en las placas de nombre"
 	ElvuiL.option_nameplates_combat = "Mostrar las chapas de nombre de los enemigos sólo en combate"
	ElvuiL.option_nameplates_goodcolor = "Color de buena amenaza, dependiendo si eres Tanque, DPS o Healer."
	ElvuiL.option_nameplates_badcolor = "Color de mala amenaza, dependiendo si eres Tanque, DPS o Healer."
	ElvuiL.option_nameplates_transitioncolor = "Color de Perdida o Ganancia de Amenaza"

	-- addon skins
	ElvuiL.option_skin = "Addons"
	ElvuiL.option_skin_kle = "KL Encounters"
	ElvuiL.option_skin_omen = "Omen"
	ElvuiL.option_skin_recount = "Recount"
	ElvuiL.option_skin_skada = "Skada"
	ElvuiL.option_hookkleright = "Forzar a DEX que la barra sea posicionada arriba a la derecha del marco de chat"

	-- combat text
	ElvuiL.option_combattext = "Texto de combate"
	ElvuiL.option_combattext_showoverheal = "Mostrar sobresanación"
	ElvuiL.option_combattext_fontsize = "Tamaño de la fuente"
	ElvuiL.option_combattext_showhots = "Mostrar sanación en el tiempo"

	-- classtimer
	ElvuiL.option_classtimer = "Class Timer"
	ElvuiL.option_classtimer_enable = "Activar Classtimer"
	ElvuiL.option_classtimer_bar_height = "Anchura de la barra"
	ElvuiL.option_classtimer_bar_spacing = "Espaciado entre barras"
	ElvuiL.option_classtimer_icon_position = "Posición el icono (0-Izquierda,1-Derecha,2-Izquierda fuera,3-Derecha fuera)"
	ElvuiL.option_classtimer_layout = "Estilo (1-5)"
	ElvuiL.option_classtimer_showspark = "Mostrar chispa"
	ElvuiL.option_classtimer_cast_suparator = "Separador de lanzamiento"
	ElvuiL.option_classtimer_classcolor = "Color de clase"
	ElvuiL.option_classtimer_debuffcolor = "Color de la barra de perjuicios"
	ElvuiL.option_classtimer_buffcolor = "Color de la barra de beneficios"
	ElvuiL.option_classtimer_proccolor = "Color de la barra de abalorios/proc"

	-- datatext
	ElvuiL.option_datatext = "Textos de datos"
	ElvuiL.option_datatext_24h = "Activar tiempo en 24h"
	ElvuiL.option_datatext_localtime = "Usar la hora local en vez de la del serviodr"
	ElvuiL.option_datatext_bg = "Activar las estadísticas en los campos de batalla"
	ElvuiL.option_datatext_guild = "Posición de la hermandad (0 para desactivar)"
	ElvuiL.option_datatext_mem = "Posición de la memoria (0 para desactivar)"
	ElvuiL.option_datatext_bags = "Posición de las bolas (0 para desactivar)"
	ElvuiL.option_datatext_fontsize = "Tamaño de la fuente"
	ElvuiL.option_datatext_system = "Posición de la latencia y los FPS (0 para desactivar)"
	ElvuiL.option_datatext_friend = "Posición de los amigos (0 para desactivar)"
	ElvuiL.option_datatext_time = "Posición de la hora (0 para desactivar)"
	ElvuiL.option_datatext_gold = "Posición del oro (0 para desactivar)"
	ElvuiL.option_datatext_dur = "Posición de la durabilidad (0 for disabled)"
	ElvuiL.option_datatext_stat1 = "Posición de la estadística 1"
	ElvuiL.option_datatext_stat2 = "Posición de la estadística 2"
	ElvuiL.option_datatext_dps = "Posicion de Daño por segundo"
	ElvuiL.option_datatext_hps = "Posicion de Curas por Segundo"

	-- auras
	ElvuiL.option_auras = "Auras"
	ElvuiL.option_auras_minimapauras = "Auras al lado del minimapa"
	ElvuiL.option_auras_arenadebuffs = "Mostras únicamente auras importantes dentro de arenas/campos de batalla"
	ElvuiL.option_auras_auratimer = "Activar el tiempo en las auras"
	ElvuiL.option_auras_targetaura = "Activar las auras del objetivo"
	ElvuiL.option_auras_focusdebuff = "Activar las auras del foco"
	ElvuiL.option_auras_playeraura = "Mostrar auras en el cuadro del jugador"
	ElvuiL.option_auras_aurascale = "Escala del texto de las auras"
	ElvuiL.option_auras_totdebuffs = "Activar los perjuicios en el ToT"
	ElvuiL.option_auras_playershowonlydebuffs = "Mostras perjuicios en el marco de jugador únicamente (requiere activar mostrar auras)"
	ElvuiL.option_auras_playerdebuffsonly = "Mostras solamente tus perjuicios/CCs en el objetivo \n (auraFilter.lua para configurar)"
	ElvuiL.option_auras_RaidUnitBuffWatch = "Activar visor de beneficios en los marcos de banda"
	ElvuiL.option_auras_playtarbuffperrow = "Cantidad de Perjucios y Beneficios en una linea del marco de Jugador/Objetivo"
	ElvuiL.option_auras_smallbuffperrow = "Cantidad de Perjucios y Beneficios en una linea del marco de Objetivo de Objetivo y Foco"
	ElvuiL.option_auras_buffindicatorsize = "Tamaño del icono del Indicador de Beneficios en el marco de Banda o Grups"
	-- raidframes
	ElvuiL.option_raidframes = "Marcos de banda"
	ElvuiL.option_raidframes_enable = "Activar marcos de banda"
	ElvuiL.option_raidframes_gridonly = "Usar el formato de 25 miembros en grupo"
	ElvuiL.option_raidframes_healcomm = "Activar HealComm (sólo en el estilo de sanadores)"
	ElvuiL.option_raidframes_boss = "Activar los marcos de los jefes"
	ElvuiL.option_raidframes_hpvertical = "Mostrar la barra de vida vertical en el Grid (sólo en el estilo de sanadores)"
	ElvuiL.option_raidframes_enablerange = "Activar advertencia de rango en los marcos de banda/grupo"
	ElvuiL.option_raidframes_range = "Alpha de las unidades fuera de rango en banda/grupo"
	ElvuiL.option_raidframes_maintank = "Activar tanque principal"
	ElvuiL.option_raidframes_mainassist = "Activar asistente principal"
	ElvuiL.option_raidframes_playerparty = "Mostrarse así mismo en grupo"
	ElvuiL.option_raidframes_hidenonmana = "Mostrar la barra de poder sólo en las unidades que usen maná (no en los marcos de grupo)"
	ElvuiL.option_raidframes_fontsize = "Tamaño de la fuenta en los marcos de banda"
	ElvuiL.option_raidframes_scale = "Escala de los marcos de banda (en decimales ej: 0.96)"
	ElvuiL.option_raidframes_disableblizz = "Desactivar los marcos de banda/grupo por defecto de Blizzard"
 	ElvuiL.option_raidframes_griddps = "Muestra el diseño de DPS en diseño de celdas en vez de el diseño de barras vertical (Solo en Banda).."
	ElvuiL.option_raidframes_partytarget = "Muestra los Objetivos de los Miembros del Grupo (Solo DPS)"

	-- castbar
	ElvuiL.option_castbar = "Barra de lanzamiento"
	ElvuiL.option_castbar_nointerruptcolor = "Color de la barra de lanzamiento si no se puede interrumpir"
	ElvuiL.option_castbar_castbarcolor = "Color de la barra de lanzamiento"
	ElvuiL.option_castbar_castbar = "Activar barra de lanzamiento"
	ElvuiL.option_castbar_latency = "Mostrar la latencia en la barra de lanzamiento"
	ElvuiL.option_castbar_icon = "Mostrar iconos en la barra de lanzamiento"
	ElvuiL.option_castbar_castermode = "Activar una barra de lanzamiento mayor (recomendada para casters)"
	ElvuiL.option_castbar_classcolor = "Colorear la barra de lanzamiento según el color de clase"

	-- unit frames
	ElvuiL.option_unitframes_unitframes = "Marcos de unidad"
	ElvuiL.option_unitframes_healthcolor = "Color de las barras de vida"
	ElvuiL.option_unitframes_combatfeedback = "Texto de comabate para el jugador y el objetivo"
	ElvuiL.option_unitframes_totalhpmp = "Mostrar vida/poder total"
	ElvuiL.option_unitframes_aurawatch = "Mostrar los beneficios en las esquinas"
	ElvuiL.option_unitframes_saveperchar = "Guarda la posición de los marcos para cada personaje"
	ElvuiL.option_unitframes_playeraggro = "Mostrar alerta de amenaza en uno mismo"
	ElvuiL.option_unitframes_smooth = "Activar barras suaves"
	ElvuiL.option_unitframes_portrait = "Activar retratos en los marcos de jugador y objetivo"
	ElvuiL.option_unitframes_enable = "Activar los marcos de unidades Elvui"
	ElvuiL.option_unitframes_enemypower = "Activar la barra de poder (maná, ira...) sólo en el jugador"
	ElvuiL.option_unitframes_raidaggro = "Mostrar alerta de amenaza"
	ElvuiL.option_unitframes_symbol = "Mostrar símbolos en banda/grupo"
	ElvuiL.option_unitframes_threatbar = "Activar barra de amenaza"
	ElvuiL.option_unitframes_focus = "Activar marco de foco"
	ElvuiL.option_unitframes_manalow = "Indicador de maná bajo"
	ElvuiL.option_unitframes_classcolor = "Colorear los marcos de unidad con el color de la clase"
	ElvuiL.option_unitframes_SwingBar = "Activar barra de swing (sólo para el estilo DPS)"
	ElvuiL.option_unitframes_DebuffHighlight = "Colorear marcos según el color del perjuicio si es disipable"
	ElvuiL.option_unitframes_mendpet = "Mostrar la barra de Aliviar Mascota en el marco de mascota (sólo para el estilo DPS)"
	ElvuiL.option_unitframes_fontsize = "Tamaño de la fuente"
	ElvuiL.option_unitframes_unitframes_poweroffset = "Compensación de la barra de poder dentro del marco de unidad (0 para no usar compensación)"
	ElvuiL.option_unitframes_classbar = "Activar la barra de clase (Totems, Runas, poder sagrado, almas, Eclipse)"
	ElvuiL.option_unitframes_healthbackdropcolor = "Color de fondo de la barra de vida para todas las unidades"
	ElvuiL.option_unitframes_healthcolorbyvalue = "Colorear las Barras de Vida por la cantidad que queda de vida."
	ElvuiL.option_unitframes_combat = "Ocultar Marcos de Unidad mientras no estás en combate."
	ElvuiL.option_unitframes_pettarget = "Mostrar el Objetivo de la Mascota (Solo DPS)"
	ElvuiL.option_raidframes_partytarget = "Mostrar objetivo de los miembros de grupo (Solo DPS)"
	
	 -- frame sizes
	ElvuiL.option_framesizes = "Tamaño de los marcos de unidad"
	ElvuiL.option_framesizes_playtarwidth = "Ancho del marco de Jugador/Objetivo"
	ElvuiL.option_framesizes_playtarheight = "Alto del marco de Jugador/Objetivo"
	ElvuiL.option_framesizes_smallwidth = "Ancho del marco de Objetivo del Objetivo/Foco/Objetivo del Foco/Mascota"
	ElvuiL.option_framesizes_smallheight = "Alto del marco de Objetivo del Objetivo/Foco/Objetivo del Foco/Mascota"
	ElvuiL.option_framesizes_arenabosswidth = "Ancho del marco de Arena/Jefes"
	ElvuiL.option_framesizes_arenabossheight = "Alto del marco de Arena/Jefes"
	ElvuiL.option_framesizes_assisttankwidth = "Ancho del marco de Tanque Principal/Asistente"
	ElvuiL.option_framesizes_assisttankheight = "Alto del marco de Tanque Principal/Asistente"

	-- loot
	ElvuiL.option_loot = "Despojar"
	ElvuiL.option_loot_enableloot = "Enable loot window Habilitar la ventana de Despojar."
	ElvuiL.option_loot_autogreed = "Habilitar la Auto-Codicia para objetos verdes con mas Ilvl"
	ElvuiL.option_loot_enableroll = "Habilitar la ventana de Tirar Dados."

	-- tooltip
	ElvuiL.option_tooltip = "Botín"
	ElvuiL.option_tooltip_enable = "Activar tooltip"
	ElvuiL.option_tooltip_hidecombat = "Ocultar el tooltip inferior derecho en combate"
	ElvuiL.option_tooltip_hidebutton = "Ocultar el tooltip en las barras de acción"
	ElvuiL.option_tooltip_hideuf = "Ocultar el tooltip en los marcos de unidades"
	ElvuiL.option_tooltip_cursor = "Adjuntar el tooltip al puntero"
	ElvuiL.option_tooltip_combatraid = "Ocultar el tooltip sólo durante un combate de banda"
	ElvuiL.option_tooltip_colorreaction = "Colorear el borde y la barra de vida del tooltip según la reacción"
	ElvuiL.option_tooltip_xOfs = "Compensación en el eje X del tooltip (-x = Izquierda, +x = Derecha)"
	ElvuiL.option_tooltip_yOfs = "Compensación en el eje Ydel tooltip (-y = Izquierda, +y = Arriba)"
	ElvuiL.option_tooltip_itemid = "Mostrar ID de Objeto"
	ElvuiL.option_tooltip_whotargetting = "Muestra quien está marcando la unidad que está en tu grupo/banda."
	
	-- others
	ElvuiL.option_others = "Otros"
	ElvuiL.option_others_bg = "Activar la liberación automática del cadáver en los campos de batalla"
	ElvuiL.option_others_autosell = "Vender la basura automáticamente"
	ElvuiL.option_others_autorepair = "Reparar automáticamente los objetos"
	ElvuiL.option_others_autoinvite = "Aceptar las invitaciones de amigos y miembros de hermandad automáticamente"
	ElvuiL.option_others_enablemap = "Activar el mapa"
	ElvuiL.option_others_errorhide = "Ocultar los errores (textos en rojo) que aparecen en mitad de la pantalla"
	ElvuiL.option_others_spincam = "Girar la cámara cuando se está AUS"
	ElvuiL.option_others_bagenable = "Unir todas las bolsas del inventario en una"

	-- reminder
	ElvuiL.option_reminder = "Advertencia de auras"
	ElvuiL.option_reminder_enable = "Activar las advertencias de auras para el jugador"
	ElvuiL.option_reminder_sound = "Activar el sonido de alerta"
	ElvuiL.option_reminder_RaidBuffReminder = "Activar la barra de recordatorio de auras (frascos, comidas...) debajo del minimapa"

	-- action bar
	ElvuiL.option_actionbar = "Barras de acción"
	ElvuiL.option_actionbar_hidess = "Ocultar la barra de cambio de forma y/o barra de tótems"
	ElvuiL.option_actionbar_showgrid = "Mostrar siempre la cuadrícula en las barras de acción"
	ElvuiL.option_actionbar_enable = "Activar las barras de acción Elvui"
	ElvuiL.option_actionbar_rb = "Activar la barra de acción derecha al pasar el ratón"
	ElvuiL.option_actionbar_hk = "Mostrar los atajos en los botones"
	ElvuiL.option_actionbar_ssmo = "Mostrar la barra de cambio de forma y/o totems al pasar el ratón"
	ElvuiL.option_actionbar_bottompetbar = "Posicionar la barra de mascota bajo la barra principal de acción, la barra de acción principal se desplazará hacia arriba"
	ElvuiL.option_actionbar_buttonsize = "Tamaño de los botones de la barra principal"
	ElvuiL.option_actionbar_buttonspacing = "Espacio entre los botones de la barra principal"
	ElvuiL.option_actionbar_petbuttonsize = "Tamaño de los botones de la barra de mascota/estancia"
	ElvuiL.option_actionbar_swaptopbottombar = "Intercambia la Barra de Acciones de Lugar."
	ElvuiL.option_actionbar_macrotext = "Muestra el Marco de texto de las Barras de Acción"
	ElvuiL.option_actionbar_verticalstance = "Barras de estancias en Vertical"
	ElvuiL.option_actionbar_microbar = "Mostrar Microbarra (Menú)"
	ElvuiL.option_actionbar_mousemicro = "Mostrar Microbarra al pasar el Ratón"
	ElvuiL.option_actionbar_macrotext = "Mostrar texto de macro en la barra de acciones"
	
	-- arena
	ElvuiL.option_arena = "Arena"
	ElvuiL.option_arena_st = "Activar seguimiento de hechizos del enemigo en arenas"
	ElvuiL.option_arena_uf = "Activar los marcos de arena"

	-- cooldowns
	ElvuiL.option_cooldown = "Cooldowns"
	ElvuiL.option_cooldown_enable = "Activar el tiempo de enfriamiento en los botones"
	ElvuiL.option_cooldown_th = "Cambiar de color el número cuando queda X tiempo"
	ElvuiL.option_cooldown_expiringcolor = "Color de expiración"
	ElvuiL.option_cooldown_secondscolor = "Color de los segundos"
	ElvuiL.option_cooldown_minutescolor = "Color de los minutos"
	ElvuiL.option_cooldown_hourscolor = "Color de las horas"
	ElvuiL.option_cooldown_dayscolor = "Color de los días"

	-- chat
	ElvuiL.option_chat = "Chat"
	ElvuiL.option_chat_bubbles = "Burbujas de chat skineadas (encima de las cabezas)"
	ElvuiL.option_chat_enable = "Activar el chat Elvui"
	ElvuiL.option_chat_whispersound = "Reproducir sonido cuando se recibe un privado"
	ElvuiL.option_chat_chatwidth = "Anchura del chat (horizontal)"
	ElvuiL.option_chat_backdrop = "Mostrar fondo en el chat"
	ElvuiL.option_chat_chatheight = "Altura del chat"
	ElvuiL.option_chat_fadeoutofuse = "Ocultar chat cuando no está en uso"
	ElvuiL.option_chat_sticky = "Fijar algunas pestañas del chat cuando se edita"
	ElvuiL.option_chat_combathide = "Deslizar chat durante el combate ('Left', 'Right', 'Both', o 'NONE')"
	ElvuiL.option_chat_rightchat = "Mostrar ventana derecha del Chat."

	-- buttons
	ElvuiL.option_button_reset = "Reiniciar interfaz"
	ElvuiL.option_button_load = "Aplicar cambios"
	ElvuiL.option_button_close = "Cerrar"
	ElvuiL.option_setsavedsetttings = "Guardar opciones por personje"
	ElvuiL.option_resetchar = "¿Seguro que desea reiniciar las opcioens de este personaje a las por defecto?"
	ElvuiL.option_resetall = "¿Seguro que desea reiniciar TODAS las opciones a las por defecto?"
	ElvuiL.option_perchar = "¿Seguro que desea cambiar la configuración 'por personaje'?"
	ElvuiL.option_makeselection = "Tiene que seleccionar una opción antes de seguir con la configuración."
end