local E, L, V, P, G = unpack(select(2, ...)); --Import: Engine, Locales, PrivateDB, ProfileDB, GlobalDB
local LSM = E.Libs.LSM

LSM:Register("background","ElvUI Blank", [[Interface\BUTTONS\WHITE8X8]])
LSM:Register("border", "ElvUI GlowBorder", [[Interface\AddOns\ElvUI\Media\Textures\GlowTex]])
LSM:Register("font", "Continuum Medium", [[Interface\AddOns\ElvUI\Media\Fonts\Continuum_Medium.ttf]])
LSM:Register("font","Die Die Die!", [[Interface\AddOns\ElvUI\Media\Fonts\DieDieDie.ttf]])
LSM:Register("font","Action Man", [[Interface\AddOns\ElvUI\Media\Fonts\Action_Man.ttf]])
LSM:Register("font", "Expressway", [[Interface\AddOns\ElvUI\Media\Fonts\Expressway.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font","PT Sans Narrow", [[Interface\AddOns\ElvUI\Media\Fonts\PT_Sans_Narrow.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Homespun", [[Interface\AddOns\ElvUI\Media\Fonts\Homespun.ttf]],LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("sound", "Awww Crap", [[Interface\AddOns\ElvUI\Media\Sounds\AwwCrap.ogg]])
LSM:Register("sound", "BBQ Ass", [[Interface\AddOns\ElvUI\Media\Sounds\BbqAss.ogg]])
LSM:Register("sound", "Big Yankie Devil", [[Interface\AddOns\ElvUI\Media\Sounds\YankieBangBang.ogg]])
LSM:Register("sound", "Dumb Shit", [[Interface\AddOns\ElvUI\Media\Sounds\DumbShit.ogg]])
LSM:Register("sound", "Mama Weekends", [[Interface\AddOns\ElvUI\Media\Sounds\MamaWeekends.ogg]])
LSM:Register("sound", "Runaway Fast", [[Interface\AddOns\ElvUI\Media\Sounds\RunFast.ogg]])
LSM:Register("sound", "Stop Running", [[Interface\AddOns\ElvUI\Media\Sounds\StopRunningSlimeBall.ogg]])
LSM:Register("sound","Warning", [[Interface\AddOns\ElvUI\Media\Sounds\Warning.ogg]])
LSM:Register("sound","Whisper Alert", [[Interface\AddOns\ElvUI\Media\Sounds\Whisper.ogg]])
LSM:Register("statusbar","ElvUI Gloss", [[Interface\AddOns\ElvUI\Media\Textures\NormTex]])
LSM:Register("statusbar","ElvUI Norm", [[Interface\AddOns\ElvUI\Media\Textures\NormTex2]])
LSM:Register("statusbar","Minimalist", [[Interface\AddOns\ElvUI\Media\Textures\Minimalist]])
LSM:Register("statusbar","ElvUI Blank", [[Interface\BUTTONS\WHITE8X8]])
LSM:Register("statusbar","Melli", [[Interface\AddOns\ElvUI\Media\Textures\Melli]])
