local E, L, P, G = unpack(select(2, ...)); --Inport: Engine, Locales, ProfileDB, GlobalDB

--UnitFrame
E.DF["global"]['unitframe'] = {
	['Primary'] = {
		['player'] = {
			['enable'] = true,
			['width'] = 260,
			['height'] = 55,
			['lowmana'] = 30,
			['combatfade'] = false,
			['healPrediction'] = true,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'TOPRIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = true,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 15,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,
			},
			['altpower'] = {
				['enable'] = true,
				['width'] = 260,
				['height'] = 18,
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['portrait'] = {
				['enable'] = false,
				['width'] = 45,
				['overlay'] = false,
				['camDistanceScale'] = 1,
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['attachTo'] = 'DEBUFFS',
				['anchorPoint'] = 'TOPLEFT',
				['fontsize'] = 10,
				['showPlayerOnly'] = true,
				['useFilter'] = 'TurtleBuffs',
				['durationLimit'] = 900,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMRIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPRIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},
			['castbar'] = {
				['enable'] = true,
				['snaptoab'] = true,	-- Position the player castbar above actionbar 1 and size it automatically. This disables the 'width' option.
				['width'] = 260,
				['height'] = 20,
				['icon'] = false,
				['latency'] = true,
				['color'] = { r = .66,g = .66,b = .66 },
				['interruptcolor'] = { r = 0.78, g = 0.25, b = 0.25 },
				['xOffset'] = 0,
				['yOffset'] = 0,
				['format'] = 'CURRENTMAX',
				["ticks"] = true,
				['spark'] = true,
			},
			['classbar'] = {
				['enable'] = true,
				['fill'] = 'spaced',
				['height'] = 8,
			},
		},	
		['target'] = {
			['enable'] = true,
			['width'] = 260,
			['height'] = 55,
			['healPrediction'] = true,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'TOPRIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = true,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 15,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['portrait'] = {
				['enable'] = false,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 1,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 8,
				['numrows'] = 2,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMLEFT',						
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 8,
				['numrows'] = 2,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPLEFT',
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'BOTTOMLEFT',
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',	
				['durationLimit'] = 0,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 260,
				['height'] = 15,
				['icon'] = false,
				['color'] = { r = .66,g = .66,b = .66 },
				['interruptcolor'] = { r = 0.78, g = 0.25, b = 0.25 },
				['xOffset'] = 0,
				['yOffset'] = 86,
				['format'] = 'REMAINING',
				['spark'] = true,
			},	
			['combobar'] = {
				['enable'] = true,
				['fill'] = 'spaced',
				['height'] = 10,
			},				
		},
		['targettarget'] = {
			['enable'] = true,
			['width'] = 130,
			['height'] = 50,
			['health'] = {
				['text'] = false,
				['text_format'] = 'current-percent',
				['position'] = 'RIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 10,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,					
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'CENTER',
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 5,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPRIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMRIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},			
		},
		['focus'] = {
			['enable'] = true,
			['width'] = 200,
			['height'] = 40,
			['healPrediction'] = true,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'TOPRIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 10,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPLEFT',
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'BOTTOMLEFT',
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},	
			['castbar'] = {
				['enable'] = true,
				['width'] = 200,
				['height'] = 15,
				['icon'] = false,
				['color'] = { r = .66,g = .66,b = .66 },
				['interruptcolor'] = { r = 0.78, g = 0.25, b = 0.25 },
				['xOffset'] = 0,
				['yOffset'] = 65,
				['format'] = 'REMAINING',
				['spark'] = true,
			},					
		},	
		['focustarget'] = {
			['enable'] = true,
			['width'] = 150,
			['height'] = 40,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'TOPRIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 10,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 6,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 6,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPLEFT',
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'BOTTOMLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},			
		},				
		['pet'] = {
			['enable'] = true,
			['width'] = 130,
			['height'] = 35,
			['healPrediction'] = true,
			['health'] = {
				['text'] = false,
				['text_format'] = 'current-percent',
				['position'] = 'TOPRIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 5,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPRIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMRIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},			
		},
		['pettarget'] = {
			['enable'] = false,
			['width'] = 130,
			['height'] = 25,
			['health'] = {
				['text'] = false,
				['text_format'] = 'current-percent',
				['position'] = 'RIGHT',
			},
			['power'] = {
				['enable'] = false,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = true,					
			},
			['name'] = {
				['enable'] = true,
				['position'] = 'CENTER',
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 7,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 5,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'TOPRIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'BOTTOMRIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},			
		},	
		['boss'] = {
			['enable'] = true,
			['growthDirection'] = 'DOWN',
			['width'] = 200,
			['height'] = 45,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'TOPRIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = true,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},
			['portrait'] = {
				['enable'] = false,
				['width'] = 35,
				['overlay'] = false,
				['camDistanceScale'] = 1,
			},				
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 8,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMRIGHT',
				['attachTo'] = 'DEBUFFS',
				['anchorPoint'] = 'TOPRIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 8,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = true,
				['useFilter'] = '',	
				['durationLimit'] = 0,
			},	
			['castbar'] = {
				['enable'] = true,
				['width'] = 200,
				['height'] = 15,
				['icon'] = true,
				['color'] = { r = .66,g = .66,b = .66 },
				['interruptcolor'] = { r = 0.78, g = 0.25, b = 0.25 },
				['format'] = 'REMAINING',
				['spark'] = true,
			},					
		},	
		['arena'] = {
			['enable'] = true,
			['growthDirection'] = 'UP',
			['pvpTrinket'] = true,
			['width'] = 240,
			['height'] = 45,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'RIGHT',
			},
			['power'] = {
				['enable'] = true,
				['text'] = true,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,					
			},			
			['name'] = {
				['enable'] = true,
				['position'] = 'CENTER',
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'RIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'TurtleBuffs',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'LEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'CCDebuffs',	
				['durationLimit'] = 0,
			},	
			['castbar'] = {
				['enable'] = true,
				['width'] = 240,
				['height'] = 15,
				['icon'] = true,
				['color'] = { r = .66,g = .66,b = .66 },
				['interruptcolor'] = { r = 0.78, g = 0.25, b = 0.25 },
				['format'] = 'REMAINING',
				['spark'] = true,
			},					
		},
		['party'] = {
			['enable'] = false,
			['visibility'] = "[@raid6,exists] hide;show",
			['point'] = 'TOP', --Requires ReloadUI()
			['maxColumns'] = 1,
			['unitsPerColumn'] = 5,
			['columnSpacing'] = 3,
			['xOffset'] = 0,
			['yOffset'] = -3,
			['groupBy'] = 'GROUP',
			["showParty"] = true,
			["showRaid"] = true,
			["showSolo"] = false,
			["showPlayer"] = true,
			['healPrediction'] = false,
			['columnAnchorPoint'] = "TOP",
			['width'] = 180,
			['height'] = 43,
			['health'] = {
				['text'] = true,
				['text_format'] = 'current-percent',
				['position'] = 'RIGHT',
				['orientation'] = 'HORIZONTAL',
			},
			['power'] = {
				['enable'] = true,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},			
			['name'] = {
				['enable'] = true,
				['position'] = 'LEFT',
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'RIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'LEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',	
				['durationLimit'] = 0,
			},	
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 6,
				['fontsize'] = 8,
				['colorIcons'] = true,
			},
			['roleIcon'] = {
				['enable'] = true,
				['position'] = 'BOTTOMRIGHT',
			},							
			['petsGroup'] = {
				['enable'] = false,
				['width'] = 100,
				['height'] = 22,
				['initialAnchor'] = 'TOPRIGHT',
				['anchorPoint'] = 'TOPLEFT',
				['xOffset'] = -1,
				['yOffset'] = 0,
			},
			['targetsGroup'] = {
				['enable'] = false,
				['width'] = 100,
				['height'] = 22,
				['initialAnchor'] = 'TOPRIGHT',
				['anchorPoint'] = 'TOPLEFT',
				['xOffset'] = -1,
				['yOffset'] = 0,
			},				
		},
		['raid625'] = {
			['enable'] = true,
			['visibility'] = '[@raid26,exists] hide;show',
			['point'] = 'LEFT',
			['maxColumns'] = 5,
			['unitsPerColumn'] = 5,
			['columnSpacing'] = 3,
			['xOffset'] = 3,
			['yOffset'] = -3,
			['groupBy'] = 'GROUP',
			["showParty"] = true,
			["showRaid"] = true,
			["showSolo"] = false,
			["showPlayer"] = true,
			['healPrediction'] = false,
			['columnAnchorPoint'] = "TOP",
			['width'] = 73,
			['height'] = 44,
			['health'] = {
				['text'] = false,
				['text_format'] = 'deficit',
				['position'] = 'BOTTOM',
				['orientation'] = 'HORIZONTAL',
			},
			['power'] = {
				['enable'] = true,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 8,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},			
			['name'] = {
				['enable'] = true,
				['position'] = 'TOP',
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'RIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 2,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'LEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = 'DebuffBlacklist',	
				['durationLimit'] = 0,
			},	
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 6,
				['fontsize'] = 8,
				['colorIcons'] = true,
			},
			['rdebuffs'] = {
				['enable'] = false,
				['fontsize'] = 10,
				['size'] = 26,
			},
			['roleIcon'] = {
				['enable'] = true,
				['position'] = 'BOTTOMRIGHT',
			},					
		},					
		['raid2640'] = {
			['enable'] = true,
			['visibility'] = '[@raid26,noexists] hide;show',
			['point'] = 'LEFT',
			['maxColumns'] = 8,
			['unitsPerColumn'] = 5,
			['columnSpacing'] = 3,
			['xOffset'] = 3,
			['yOffset'] = -3,
			['groupBy'] = 'GROUP',
			["showParty"] = true,
			["showRaid"] = true,
			["showSolo"] = false,
			["showPlayer"] = true,
			['healPrediction'] = false,
			['columnAnchorPoint'] = "TOP",
			['width'] = 73,
			['height'] = 36,
			['health'] = {
				['text'] = true,
				['text_format'] = 'deficit',
				['position'] = 'BOTTOM',
				['orientation'] = 'HORIZONTAL',
			},
			['power'] = {
				['enable'] = false,
				['text'] = false,
				['text_format'] = 'current',	
				['width'] = 'fill',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,					
			},			
			['name'] = {
				['enable'] = true,
				['position'] = 'TOP',
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'RIGHT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',		
				['durationLimit'] = 0,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['growth-x'] = 'RIGHT',
				['growth-y'] = 'DOWN',
				['initialAnchor'] = 'LEFT',
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',					
				['fontsize'] = 10,
				['showPlayerOnly'] = false,
				['useFilter'] = '',	
				['durationLimit'] = 0,
			},	
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 6,
				['fontsize'] = 8,
				['colorIcons'] = true,
			},			
		},	
		['tank'] = {
			['enable'] = true,
			['width'] = 120,
			['height'] = 28,
		},	
		['assist'] = {
			['enable'] = true,
			['width'] = 120,
			['height'] = 28,
		},					
	},
	['Secondary'] = {
		['target'] = {
			['buffs'] = {
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMRIGHT',
				['anchorPoint'] = 'TOPRIGHT',
			},
			['debuffs'] = {
				['numrows'] = 1,
				['growth-x'] = 'LEFT',
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMRIGHT',
				['anchorPoint'] = 'TOPRIGHT',
			},
			['castbar'] = {
				['yOffset'] = 0,
			},			
		},
		['targettarget'] = {
			['height'] = 35,			
		},
		['focus'] = {
			['buffs'] = {
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['anchorPoint'] = 'TOPLEFT',
			},
			['debuffs'] = {
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['anchorPoint'] = 'TOPLEFT',
			},
			['castbar'] = {
				['yOffset'] = 65,
			},
		},	
		['focustarget'] = {
			['buffs'] = {
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['anchorPoint'] = 'TOPLEFT',
			},
			['debuffs'] = {
				['growth-y'] = 'UP',
				['initialAnchor'] = 'BOTTOMLEFT',
				['anchorPoint'] = 'TOPLEFT',
			},
		},
		['boss'] = {
			['growthDirection'] = 'UP',				
		},	
		['arena'] = {
			['width'] = 200,
			['castbar'] = {
				['width'] = 200,
			},					
		},
		['party'] = {
			['point'] = 'LEFT',
			['xOffset'] = 1,
			['healPrediction'] = true,
			["columnAnchorPoint"] = "LEFT",
			["width"] = 80,
			["height"] = 52,
			['health'] = {
				["text_format"] = "deficit",
				["position"] = "BOTTOM",
				['orientation'] = 'VERTICAL',
			},
			['name'] = {
				["position"] = "TOP",
			},
			['debuffs'] = {
				["anchorPoint"] = "BOTTOMLEFT",
				["initialAnchor"] = "TOPLEFT",
				['useFilter'] = 'DebuffBlacklist',		
			},
			['petsGroup'] = {
				['enable'] = true,
				['width'] = 80,
				['initialAnchor'] = 'BOTTOM',
				['anchorPoint'] = 'TOP',
				['xOffset'] = 0,
				['yOffset'] = 1,
			},		
			['targetsGroup'] = {
				['enable'] = false,
				['width'] = 80,
				['initialAnchor'] = 'BOTTOM',
				['anchorPoint'] = 'TOP',
				['xOffset'] = 0,
				['yOffset'] = 1,
			},					
		},
		['raid625'] = {
			['healPrediction'] = true,
		},					
		['raid2640'] = {
			['healPrediction'] = true,			
		},					
		["positions"] = {
			["ElvUF_Player"] = "BOTTOMLEFTUIParent464230",
			["ElvUF_Target"] = "BOTTOMRIGHTUIParent-464230",
			["ElvUF_Raid2640"] = "BOTTOMUIParent0170",
			["ElvUF_Raid625"] = "BOTTOMUIParent0170",
			["ElvUF_TargetTarget"] = "BOTTOMRIGHTElvUF_Target0150",
			["ElvUF_Focus"] = "BOTTOMLEFTElvUF_Player0150",
			["ElvUF_FocusTarget"] = "BOTTOMLEFTElvUF_Focus0150",
			["ElvUF_Party"] = "BOTTOMUIParent0170",
			["ElvUF_Pet"] = "BOTTOMLEFTUIParent464151",
			["ElvUF_Boss1"] = "BOTTOMLEFTUIParent30250",
			["ElvUF_Boss2"] = "BOTTOMLEFTUIParent30375",
			["ElvUF_Boss3"] = "BOTTOMLEFTUIParent30500",
			["ElvUF_Boss4"] = "BOTTOMLEFTUIParent30625",
			["ElvUF_Tank"] = "LEFTUIParent30350",
		},			
	},
}

--Actionbar
E.DF["global"]["actionbar"] = {
	['Primary'] = {
		['bar1'] = {
			['enabled'] = true,
			['buttons'] = 12,
			['mouseover'] = false,
			['buttonsPerRow'] = 12,
			['point'] = 'BOTTOMLEFT',
			['backdrop'] = true,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,		
			['paging'] = {
				["DRUID"] = "[bonusbar:1,nostealth] 7; [bonusbar:1,stealth] 8; [bonusbar:2] 8; [bonusbar:3] 9; [bonusbar:4] 10;",
				["WARRIOR"] = "[bonusbar:1] 7; [bonusbar:2] 8; [bonusbar:3] 9;",
				["PRIEST"] = "[bonusbar:1] 7;",
				["ROGUE"] = "[bonusbar:1] 7; [form:3] 7;",	
			},
			['visibility'] = "",
		},
		['bar2'] = {
			['enabled'] = false,
			['mouseover'] = false,
			['buttons'] = 12,
			['buttonsPerRow'] = 12,
			['point'] = 'BOTTOMLEFT',
			['backdrop'] = false,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,		
			['paging'] = {},
			['visibility'] = "[vehicleui] hide;show",
		},
		['bar3'] = {
			['enabled'] = true,
			['mouseover'] = false,
			['buttons'] = 6,
			['buttonsPerRow'] = 6,
			['point'] = 'BOTTOMLEFT',
			['backdrop'] = true,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,
			['paging'] = {},
			['visibility'] = "[vehicleui] hide;show",
		},
		['bar4'] = {
			['enabled'] = true,
			['mouseover'] = false,
			['buttons'] = 12,
			['buttonsPerRow'] = 1,
			['point'] = 'TOPRIGHT',
			['backdrop'] = true,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,
			['paging'] = {},
			['visibility'] = "[vehicleui] hide;show",
		},
		['bar5'] = {
			['enabled'] = true,
			['mouseover'] = false,
			['buttons'] = 6,
			['buttonsPerRow'] = 6,
			['point'] = 'BOTTOMLEFT',
			['backdrop'] = true,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,
			['paging'] = {},
			['visibility'] = "[vehicleui] hide;show",
		},
		['barPet'] = {
			['enabled'] = true,
			['mouseover'] = false,
			['buttons'] = NUM_PET_ACTION_SLOTS,
			['buttonsPerRow'] = 1,
			['point'] = 'TOPRIGHT',
			['backdrop'] = true,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,
			['visibility'] = "[pet,novehicleui,nobonusbar:5] show;hide",
		},
		['barShapeShift'] = {
			['enabled'] = true,
			['mouseover'] = false,
			['buttonsPerRow'] = NUM_SHAPESHIFT_SLOTS,
			['buttons'] = NUM_SHAPESHIFT_SLOTS,
			['point'] = 'TOPLEFT',
			['backdrop'] = false,
			['heightMult'] = 1,
			['widthMult'] = 1,
			["buttonsize"] = 30,
			["buttonspacing"] = 4,
		},
		['barTotem'] = {
			['enabled'] = true,
			['mouseover'] = false,
		},
	},
};