if GetLocale() == "deDE" then
	-- general
	TukuiL.option_general = "Allgemeines"
	TukuiL.option_general_uiscale = "Automatische UI Skalierung"
	TukuiL.option_general_multisample = "Multisample Schutz (Saubere 1px Ränder)"
	TukuiL.option_general_customuiscale = "Interface Skalierung (falls automatische Skalierung deaktiviert ist)"
	TukuiL.option_general_recountscript = "Recount anzeigen (0-aus, 1-Kampf, 2-außerhalb des Kampfes)"
	TukuiL.option_general_embedright = "Addon in den rechten unterem Chat (Recount, Omen, Skada)"
	TukuiL.option_general_classtheme = "Rahmenfarbe nach Klasse anpassen"
	TukuiL.option_general_minimalistic = "Make UI look more minimalistic"
		
	--Media
	TukuiL.option_media = "Media"
	TukuiL.option_media_font = "Font file path for main font"
	TukuiL.option_media_uffont = "Font file path for UnitFrame fonts"
	TukuiL.option_media_dmgfont = "Font file path for DMG Text font (Requires Restart)"
	TukuiL.option_media_normTex = "Texture file path for unitframe Health/Power texture"
	TukuiL.option_media_glowTex = "Texture file path for glow texture"
	TukuiL.option_media_bubbleTex = "Texture file path for combo point texture (Nameplates)"
	TukuiL.option_media_blank = "Texture file path for main UI Texture"
	TukuiL.option_media_bordercolor = "Color of non-unitframe borders"
	TukuiL.option_media_altbordercolor = "Color of unitframe borders"
	TukuiL.option_media_backdropcolor = "Color of backdrop on all frames"
	TukuiL.option_media_backdropfadecolor = "Color of faded backdrop on certain faded frames"
	TukuiL.option_media_buttonhover = "Texture file path for Button Hover texture on actionbuttons"
	TukuiL.option_media_valuecolor = "Color of Datatext values"
	TukuiL.option_media_raidicons = "Texture file path for raid icons"
	TukuiL.option_media_whisper = "Sound file path for whisper sound"
	TukuiL.option_media_warning = "Sound file path for warning sound"

	-- nameplate
	TukuiL.option_nameplates = "Namensplaketten"
	TukuiL.option_nameplates_enable = "Aktiviere Namensplaketten"
	TukuiL.option_nameplates_enhancethreat = "Aktiviere Bedrohungsanzeige, anpassung an deine Rolle: \n Tank -Grün (aggro) Rot (sicher) DPS - Grün (sicher) Rot (aggro)"
	TukuiL.option_nameplates_showhealth = "Zeige Leben auf den Namensplaketten"
	TukuiL.option_nameplates_showcombo = "Zeige Kombopunkte auf den Namensplaketten"
	 
	TukuiL.option_skin = "Addon Skins"
	TukuiL.option_skin_arkinventory = "Ark Inventory"
	TukuiL.option_skin_dxe = "Deus Vox Encounters"
	TukuiL.option_skin_omen = "Omen"
	TukuiL.option_skin_pallypower = "PallyPower"
	TukuiL.option_skin_qbar = "Qbar"
	TukuiL.option_skin_quartz = "Quartz"
	TukuiL.option_skin_recount = "Recount"
	TukuiL.option_skin_sexycooldown = "Sexy Cooldown"
	TukuiL.option_skin_skada = "Skada"
	TukuiL.option_skin_clcret = "CLCRet"
	
	-- combat text
	TukuiL.option_combattext = "Kampftext"
	TukuiL.option_combattext_showoverheal = "Zeige Überheilung"
	TukuiL.option_combattext_fontsize = "Schriftgröße"
	TukuiL.option_combattext_showhots = "Zeige Heilung über Zeit"
	 
	-- classtimer
	TukuiL.option_classtimer = "Classtimer"
	TukuiL.option_classtimer_enable = "Aktiviert den Classtimer"
	TukuiL.option_classtimer_bar_height = "Leisten Höhe"
	TukuiL.option_classtimer_bar_spacing = "Leisten Abstand"
	TukuiL.option_classtimer_icon_position = "Symbol Position (0-Links,1-Rechts,2-Außen Links,3-Außen Rechts)"
	TukuiL.option_classtimer_layout = "Layout (1-4)"
	TukuiL.option_classtimer_showspark = "Zeige Funke"
	TukuiL.option_classtimer_cast_suparator = "Zauber Seperator"
	TukuiL.option_classtimer_classcolor = "Aktiviert den klassenfarbigen Classtimer"
	TukuiL.option_classtimer_debuffcolor = "Farbe der Debuff Leiste"
	TukuiL.option_classtimer_buffcolor = "Farbe der Buff Leiste"
	TukuiL.option_classtimer_proccolor = "Trinket/Proc Leisten Farbe"
	 
	-- raid buff reminder
	TukuiL.option_raidbuffreminder = "Raid Buff Erinnerung"
	TukuiL.option_raidbuffreminder_enable = "Aktiviere Raid Buff Erinnerung"
	TukuiL.option_raidbuffreminder_alwaysshow_watch = "Immer anzeigen auch außerhalb einer Instanz"
	TukuiL.option_raidbuffreminder_raidbuff_yOffset = "Y-Position des Frames"
	TukuiL.option_raidbuffreminder_buff_fadealpha = "Verblassen lassen wenn alle Buffs vorhanden"
	 
	-- datatext
	TukuiL.option_datatext = "Infotext"
	TukuiL.option_datatext_24h = "Aktiviere 24-Stunden Zeitanzeige"
	TukuiL.option_datatext_localtime = "Zeige Lokale Zeit, anstelle von Server Zeit"
	TukuiL.option_datatext_bg = "Aktiviere Schlachtfeld Anzeige"
	TukuiL.option_datatext_hps = "Heilung pro Sekunde Position"
	TukuiL.option_datatext_guild = "Gilde Position"
	TukuiL.option_datatext_arp = "Rüstungsdurchschlag Position"
	TukuiL.option_datatext_mem = "Speichernutzung Position"
	TukuiL.option_datatext_bags = "Taschen Position"
	TukuiL.option_datatext_fontsize = "Schriftgröße des Textes"
	TukuiL.option_datatext_system = "Latenz und FPS Position"
	TukuiL.option_datatext_armor = "Rüstung Position"
	TukuiL.option_datatext_avd = "Vermeidung Position)"
	TukuiL.option_datatext_power = "Zaubermacht/Angriffskraft Position"
	TukuiL.option_datatext_haste = "Tempowertung Position"
	TukuiL.option_datatext_friend = "Freunde Position"
	TukuiL.option_datatext_time = "Zeit Position"
	TukuiL.option_datatext_gold = "Gold Position"
	TukuiL.option_datatext_dps = "Schaden pro Sekunde Position"
	TukuiL.option_datatext_crit = "Crit in % Position"
	TukuiL.option_datatext_dur = "Haltbarkeit Position"
	TukuiL.option_datatext_stat1 = "Stat 1 für deine momentane Skillung"
	TukuiL.option_datatext_stat2 = "Stat 2 für deine momentane Skillung"
	TukuiL.option_datatext_loc = "Standort Position"
	TukuiL.option_datatext_tps = "Bedrohung pro Sekunde Position"
	 
	-- auras
	TukuiL.option_auras = "Stärkungszauber"
	TukuiL.option_auras_minimapauras = "Aktiviere Buffs an der Minimap"
	TukuiL.option_auras_arenadebuffs = "Zeige nur wichtige Debuffs in der Arena und im Raid"
	TukuiL.option_auras_auratimer = "Aktiviere Dauer auf Stärkungs- und Schwächungszaubern"
	TukuiL.option_auras_targetaura = "Aktiviere Stärkungs- und Schwächungszauber auf dem Ziel"
	TukuiL.option_auras_focusdebuff = "Aktiviere Schwächungszauber auf Fokusziel"
	TukuiL.option_auras_playeraura = "Aktiviere alternativen Stärkungs-/Schwächungszauber-Modus für Spieler"
	TukuiL.option_auras_aurascale = "Text-Skalierung auf  Stärkungs-/Schwächungszaubern"
	TukuiL.option_auras_totdebuffs = "Ziel vom Ziel Schwächungszauber anzeigen"
	TukuiL.option_auras_playershowonlydebuffs = "Aktiviere alternativen Schwächungszauber-Modus für Spieler (Alternativer Stärkungs-/Schwächungszauber-Modus für Spieler muss aktiv sein)"
	TukuiL.option_auras_playerdebuffsonly = "Zeige nur  Schwächungszauber auf dem Ziel (auraFilter.lua zum bearbeiten)"
	TukuiL.option_auras_RaidUnitBuffWatch = "Aktiviere die Anzeige für Stärkungszauber auf den Raidframes"
	 
	-- raidframes
	TukuiL.option_raidframes = "Raidframes"
	TukuiL.option_raidframes_enable = "Aktiviere Raidframes"
	TukuiL.option_raidframes_gridonly = "Aktiviere Grid Raidanzeige für die Gruppe"
	TukuiL.option_raidframes_healcomm = "Aktiviere HealComm (Nur Heiler Layout)"
	TukuiL.option_raidframes_boss = "Aktiviere Boss Unitframes"
	TukuiL.option_raidframes_hpvertical = "Zeige Lebensleiste vertikal für das Grid-Layout"
	TukuiL.option_raidframes_enablerange = "Aktivere Reichweite auf Raidframes"
	TukuiL.option_raidframes_range = "Transparenz der Schlachtzug- und Gruppenfenster wenn außer Reichweite"
	TukuiL.option_raidframes_maintank = "Main Tank Anzeige aktivieren"
	TukuiL.option_raidframes_mainassist = "Main Assist Anzeige aktivieren"
	TukuiL.option_raidframes_NoGridDps = "Vertikal 25man DPS Layout"
	TukuiL.option_raidframes_CenterHealLayout = "Aktiviere das Heiler Layout in der Mitte des Bildschirms"
	TukuiL.option_raidframes_playerparty = "Zeige sich selbst in der Gruppe"
	TukuiL.option_raidframes_hidenonmana = "Manaleiste nur anzeigen wenn Spieler Mana besitzt"
	TukuiL.option_raidframes_fontsize = "Schriftgröße für Raidframes"
	 
	-- castbar
	TukuiL.option_castbar = "Zauberleiste"
	TukuiL.option_castbar_nointerruptcolor = "Farbe wenn Zauber nicht unterbrechbar ist"
	TukuiL.option_castbar_castbarcolor = "Farbe für die Zauberleiste"
	TukuiL.option_castbar_castbar = "Aktiviere Zauberleiste"
	TukuiL.option_castbar_latency = "Zeige Latenz auf der Zauberleiste"
	TukuiL.option_castbar_icon = "Zeige Icons auf der Zauberleiste"
	TukuiL.option_castbar_castermode = "Aktiviere längere Zauberleiste für Zauberklassen"
	TukuiL.option_castbar_classcolor = "Aktiviert die klassenfarbige Zauberleiste"
	 
	-- unit frames
	TukuiL.option_unitframes_unitframes = "Unitframes"
	TukuiL.option_unitframes_healthcolor = "Farbe der Lebensleiste"
	TukuiL.option_unitframes_combatfeedback = "Kampfmeldungen auf Spieler und Ziel"
	TukuiL.option_unitframes_runebar = "Aktiviere Runenleiste für Todesritter"
	TukuiL.option_unitframes_totembar = "Aktiviere Totemleiste für Schamanen"
	TukuiL.option_unitframes_totalhpmp = "Zeige gesamtes Leben/Mana an"
	TukuiL.option_unitframes_aurawatch = "Aktiviere PvE Überwachung von Stärkungs- und Schwächungszaubern (nur Grid)"
	TukuiL.option_unitframes_saveperchar = "Positionen der Unitframes pro Charakter speichern"
	TukuiL.option_unitframes_wstimer = "Aktiviere Geschwächte Seele Timer (nur Priester)"
	TukuiL.option_unitframes_playeraggro = "Aktiviere Bedrohungsanzeige"
	TukuiL.option_unitframes_smooth = "Aktiviere flüssigere Leistenänderungen"
	TukuiL.option_unitframes_portrait = "Zeige Portrait für Spieler und Ziel an"
	TukuiL.option_unitframes_enable = "Aktiviere Tukui Unitframes"
	TukuiL.option_unitframes_wstarget = "Aktiviere Geschwächte Seele Timer auf dem Ziel (nur Priester)"
	TukuiL.option_unitframes_enemypower = "Zeige Mana nur bei Gegnern an"
	TukuiL.option_unitframes_wsplayer = "Aktiviere Geschwächte Seele Timer auf Spieler (nur Priester)"
	TukuiL.option_unitframes_raidaggro = "Aktiviere Bedrohungsanzeige des Schlachtzugs/Gruppe"
	TukuiL.option_unitframes_symbol = "Zeige Symbole auf Schlachtzug- und Gruppenfenster"
	TukuiL.option_unitframes_threatbar = "Aktiviere Bedrohungsleiste"
	TukuiL.option_unitframes_focus = "Aktiviere Fokus Ziel"
	TukuiL.option_unitframes_manahigh = "Hohes Mana Indikator (für Jäger)"
	TukuiL.option_unitframes_manalow = "Wenig Mana Indikator (Für alle Mana Klassen)"
	TukuiL.option_unitframes_classcolor = "Aktiviert die klassenfarbigen Unitframes"
	TukuiL.option_unitframes_ComboHideOOC = "Verstecke Combobar außerhalb des Kampfes"
	TukuiL.option_unitframes_ComboHideNoEnergy = "Verstecke Combobar wenn keine Energie vorhanden ist"
	TukuiL.option_unitframes_SwingBar = "Aktiviere Schlagtimer (Nur DPS Layout)"
	TukuiL.option_unitframes_DebuffHighlight = "Aktiviert die Hervorhebung der Schwächungszauber für die Unitframes"
	TukuiL.option_unitframes_fontsize = "Schriftgröße der Unitframes"
	 
	-- loot
	TukuiL.option_loot = "Beute"
	TukuiL.option_loot_enableloot = "Aktiviere Beutefenster"
	TukuiL.option_loot_autogreed = "Aktiviere automatisch-Gier würfeln für grüne Gegenstände (falls max. Level erreicht)"
	TukuiL.option_loot_enableroll = "Aktiviere Würfelfenster"
	 
	-- tooltip
	TukuiL.option_tooltip = "Tooltip"
	TukuiL.option_tooltip_enable = "Aktiviere Tooltip"
	TukuiL.option_tooltip_hidecombat = "Verstecke unteren rechten Tooltip im Kampf"
	TukuiL.option_tooltip_hidebutton = "Verstecke Tooltips auf Aktionsleisten"
	TukuiL.option_tooltip_hideuf = "Verstecke Tooltips auf Unitframes"
	TukuiL.option_tooltip_cursor = "Tooltip am Mauszeiger anzeigen"
	TukuiL.option_tooltip_combatraid = "Verstecke Tooltip im Kampf während des Raids"
	TukuiL.option_tooltip_colorreaction = "Tooltip Rand/Gesundheits Farbe nach Reaktion"
	TukuiL.option_tooltip_xOfs = "X-Richtung des Tooltips (-x = Links, +x = Rechts)"
	TukuiL.option_tooltip_yOfs = "Y-Richtung des Tooltips (-y = Unten, +y = Oben)"
	 
	-- others
	TukuiL.option_others = "Sonstiges"
	TukuiL.option_others_bg = "Aktiviere automisches Freilassen im Schlachtfeld"
	TukuiL.option_others_autosell = "Automatisch graue Items verkaufen"
	TukuiL.option_others_autorepair = "Automatisch reparieren"
	TukuiL.option_others_autoinvite = "Einladungen von Freunden & Gildenmitgliedern automatisch annehmen"
	TukuiL.option_others_enablemap = "Aktiviere Karte"
	TukuiL.option_others_questmovable = "Bewegbares Quest-Beobachtungsfenster"
	TukuiL.option_others_errorhide = "Verstecke rote Meldungen in der Mitte des Bildschirms"
	TukuiL.option_others_totembardirection = "Aufbau der Totemleiste (UP/DOWN)"
	TukuiL.option_others_portals = "Aktiviert das Portal Menü (Nur für Magier)"
	TukuiL.option_others_spincam = "Aktiviert die Spincam"
	TukuiL.option_others_bagenable = "Aktiviere All-in-one Tasche"
	TukuiL.option_others_soulbag = "Zeige Seelentasche als Hexenmeister"
	 
	-- reminder
	TukuiL.option_reminder = "Aura Warnung"
	TukuiL.option_reminder_enable = "Aktiviere Aura Warnung für Spieler"
	TukuiL.option_reminder_sound = "Aktiviere Sound für Aura Warnung"
	 
	-- action bar
	TukuiL.option_actionbar = "Aktionsleisten"
	TukuiL.option_actionbar_hidess = "Verstecke Gestaltenwandler- oder Totemleiste"
	TukuiL.option_actionbar_showgrid = "Rahmen auf Aktionsleisten immer anzeigen"
	TukuiL.option_actionbar_enable = "Aktiviere Tukui Aktionsleisten"
	TukuiL.option_actionbar_rb = "Aktiviere Mouseover für rechte Aktionsleisten"
	TukuiL.option_actionbar_hk = "Zeige Tastenbelegung auf den Buttons"
	TukuiL.option_actionbar_ssmo = "Gestaltenwandler- oder Totemleiste nur bei Mouseover anzeigen"
	TukuiL.option_actionbar_rbn = "Anzahl der Aktionsleisten unten (1 oder 2))"
	TukuiL.option_actionbar_rbn2 = "Anzahl der Aktionsleisten unten (1, 1.5, oder 2)"
	TukuiL.option_actionbar_rn = "Anzahl der Aktionsleisten rechts (1, 2 oder 3"
	TukuiL.option_actionbar_splitbar = "Aktviert die geteilte Leiste um die untere Aktionsleiste"
	 
	-- arena
	TukuiL.option_arena = "Arena"
	TukuiL.option_arena_st = "Aktiviere Tracker gegnerischer Zauber"
	TukuiL.option_arena_uf = "Aktiviere Tukui Arena Unitframes"
	 
	-- cooldowns
	TukuiL.option_cooldown = "Abklingzeiten"
	TukuiL.option_cooldown_enable = "Aktiviere Abklingzeiten"
	TukuiL.option_cooldown_th = "Färbe Anzeige der Abklingzeiten ab Wert X nach Ablauffarbe"
	TukuiL.option_cooldown_expiringcolor = "Ablauf Farbe"
	TukuiL.option_cooldown_secondscolor = "Sekunden Farbe"
	TukuiL.option_cooldown_minutescolor = "Minuten Farbe"
	TukuiL.option_cooldown_hourscolor = "Stunden Farbe"
	TukuiL.option_cooldown_dayscolor = "Tag Farbe"
	 
	-- chat
	TukuiL.option_chat = "Geselligkeit"
	TukuiL.option_chat_enable = "Aktiviere Tukui Chat"
	TukuiL.option_chat_whispersound = "Beim Empfang von Flüsternachrichten Ton abspielen"
	TukuiL_option_chat_chatwidth = "Breite der Chatfenster"
	TukuiL_option_chat_backdrop = "Aktiviere Hintergrund des Chatfensters"
	TukuiL_option_chat_chatheight = "Höhe der Chat Fenster"
	TukuiL_option_chat_fadeoutofuse = "Chat Text verblassen lassen"
	TukuiL_option_chat_sticky = "Sticky some chat channels when opening new chat edit"
	
	-- buttons
	TukuiL.option_button_reset = "Zurücksetzen"
	TukuiL.option_button_load = "Anwenden"
	TukuiL.option_button_close = "Schließen"
	TukuiL.option_setsavedsetttings = "Einstellungen für diesen Charakter"
	TukuiL.option_resetchar = "Bist du sicher das du die Einstellungen für diesen Charakter auf Standart zurücksetzen willst?"
	TukuiL.option_resetall = "Bist du sicher das du alle Einstellungen auf Standart zurücksetzen willst?"
	TukuiL_option_perchar = "Bist du sicher das du zur Einstellung für diesen Charakter wechseln willst'?"
	TukuiL_option_makeselection = "Sie müssen erst eine Auswahl treffen bevor Sie mit den Einstellungen fortfahren können."

end