if GetLocale() == "koKR" then
	-- 일반
	TukuiL.option_general = "일반"
	TukuiL.option_general_uiscale = "자동으로 UI크기를 조절"
	TukuiL.option_general_multisample = "멀티샘플링 1배 유지를 사용 (깨끗한 1px 선)"
	TukuiL.option_general_customuiscale = "UI크기 설정 (자동조절이 꺼져 있을 때)"
	TukuiL.option_general_embedright = "우측 대화창에 애드온 끼워넣기를 사용 (Recount, Omen, Skada)"
	TukuiL.option_general_classtheme = "직업색상 테마를 사용"
	TukuiL.option_general_autocustomlagtolerance = "블리자드의 주문 예약 시간 설정을 당신의 지연시간에 맞게 자동으로 설정"
 
	--미디어
	TukuiL.option_media = "미디어"
	TukuiL.option_media_font = "주된 글꼴 파일의 위치"
	TukuiL.option_media_uffont = "개체창 글꼴 파일의 위치"
	TukuiL.option_media_dmgfont = "피해량 글꼴 파일의 위치 (재시작 필요)"
	TukuiL.option_media_normTex = "바 텍스쳐 파일의 위치"
	TukuiL.option_media_glowTex = "글로우 텍스쳐 파일의 위치"
	TukuiL.option_media_bubbleTex = "연계점수 텍스쳐 파일의 위치 (이름표)"
	TukuiL.option_media_blank = "UI 텍스쳐 파일의 위치"
	TukuiL.option_media_bordercolor = "선 색상"
	TukuiL.option_media_altbordercolor = "개체창 선 색상"
	TukuiL.option_media_backdropcolor = "모든 창 배경 색상"
	TukuiL.option_media_backdropfadecolor = "사라지는 창 배경 색상"
	TukuiL.option_media_buttonhover = "행동단축 버튼에 커서가 위치해 있을 때 텍스쳐 파일의 위치"
	TukuiL.option_media_valuecolor = "정보글자 값 색상"
	TukuiL.option_media_raidicons = "전술 목표 아이콘 텍스쳐 파일의 위치"
	TukuiL.option_media_whisper = "귓속말 소리 파일의 위치"
	TukuiL.option_media_warning = "경고 소리 파일의 위치"
	TukuiL.option_media_glossy = "빛나는 바 텍스쳐 파일의 위치"
 
	-- 이름표
	TukuiL.option_nameplates = "이름표"
	TukuiL.option_nameplates_enable = "이름표를 사용"
	TukuiL.option_nameplates_enhancethreat = "위협수준 기능 사용, 당신의 역할에 따라 자동적으로 변경됨"
	TukuiL.option_nameplates_showhealth = "생명력을 표시"
	TukuiL.option_nameplates_combat = "전투 중에만 표시"
 
	-- 애드온 스킨
	TukuiL.option_skin = "애드온 스킨"
	TukuiL.option_skin_dxe = "Deus Vox Encounters"
	TukuiL.option_skin_omen = "Omen"
	TukuiL.option_skin_recount = "Recount"
	TukuiL.option_skin_skada = "Skada"
 
	-- 전투메세지
	TukuiL.option_combattext = "전투메세지"
	TukuiL.option_combattext_showoverheal = "초과 치유량을 표시"
	TukuiL.option_combattext_fontsize = "글꼴크기"
	TukuiL.option_combattext_showhots = "Hots 표시"
 
	-- 클래스타이머
	TukuiL.option_classtimer = "클래스타이머"
	TukuiL.option_classtimer_enable = "클래스타이머를 사용"
	TukuiL.option_classtimer_bar_height = "바 높이"
	TukuiL.option_classtimer_bar_spacing = "바 간격"
	TukuiL.option_classtimer_icon_position = "아이콘 위치 (0-좌측,1-우측,2-좌측 바깥쪽,3-우측 바깥쪽)"
	TukuiL.option_classtimer_layout = "배열 (1-5)"
	TukuiL.option_classtimer_showspark = "스파크를 표시"
	TukuiL.option_classtimer_cast_suparator = "시전 분리기를 표시"
	TukuiL.option_classtimer_classcolor = "직업색상을 사용"
	TukuiL.option_classtimer_debuffcolor = "약화 효과 바 색상"
	TukuiL.option_classtimer_buffcolor = "강화 효과 바 색상"
	TukuiL.option_classtimer_proccolor = "장신구/발동기 바 색상"
 
	-- 정보글자
	TukuiL.option_datatext = "정보글자"
	TukuiL.option_datatext_24h = "24시간으로 표시"
	TukuiL.option_datatext_localtime = "서버시간 대신 지역시간으로 표시"
	TukuiL.option_datatext_bg = "전장정보을 표시"
	TukuiL.option_datatext_guild = "접속 중인 길드원의 수 (0은 사용하지 않음)"
	TukuiL.option_datatext_mem = "메모리 사용량 (0은 사용하지 않음)"
	TukuiL.option_datatext_bags = "소지품 여유공간 (0은 사용하지 않음)"
	TukuiL.option_datatext_fontsize = "정보글자 글꼴크기"
	TukuiL.option_datatext_system = "초당 프레임 수와 지연시간 (0은 사용하지 않음)"
	TukuiL.option_datatext_friend = "접속 중인 친구의 수 (0은 사용하지 않음)"
	TukuiL.option_datatext_time = "시간 (0은 사용하지 않음)"
	TukuiL.option_datatext_gold = "보유 중인 골드 (0은 사용하지 않음)"
	TukuiL.option_datatext_dur = "장비의 내구도 (0은 사용하지 않음)"
	TukuiL.option_datatext_stat1 = "당신 역할에 대한 능력치 1"
	TukuiL.option_datatext_stat2 = "당신 역할에 대한 능력치 2"
	TukuiL.option_datatext_dps = "초당 피해량 (0은 사용하지 않음)"
	TukuiL.option_datatext_hps = "초당 치유량 (0은 사용하지 않음)"
 
	-- 강화 및 약화 효과
	TukuiL.option_auras = "강화 및 약화 효과"
	TukuiL.option_auras_minimapauras = "미니맵 옆에 강화 및 약화 효과를 표시"
	TukuiL.option_auras_arenadebuffs = "공격대창 및 파티창에 중요한 약화 효과만 표시"
	TukuiL.option_auras_auratimer = "강화 및 약화 효과 타이머를 사용"
	TukuiL.option_auras_targetaura = "대상창에 강화 및 약화 효과를 표시"
	TukuiL.option_auras_focusdebuff = "주시대상창에 약화 효과를 표시"
	TukuiL.option_auras_playeraura = "플레이어창에 강화 및 약화 효과를 표시"
	TukuiL.option_auras_aurascale = "강화 및 약화 효과의 글꼴크기"
	TukuiL.option_auras_totdebuffs = "대상의 대상창에 강화 및 약화 효과를 표시"
	TukuiL.option_auras_playershowonlydebuffs = "플레이어창에 약화 효과만 표시 (플레이어창에 강화 및 약화 효과를 표시 설정을 사용해야함)"
	TukuiL.option_auras_playerdebuffsonly = "대상창에 당신의 약화 효과만 표시  (auraFilter.lua에서 설정)"
	TukuiL.option_auras_RaidUnitBuffWatch = "공격대창에 강화 효과를 표시"
	TukuiL.option_auras_playtarbuffperrow = "플레이어/대상 창의 강화 및 약화 효과 개수"
	TukuiL.option_auras_smallbuffperrow = "대상의 대상/주시대상 창의 강화 및 약화 효과 개수"
 
	-- 공격대창
	TukuiL.option_raidframes = "공격대창"
	TukuiL.option_raidframes_enable = "공격대창을 사용"
	TukuiL.option_raidframes_gridonly = "파티일 때 25인 공격대창으로 표시"
	TukuiL.option_raidframes_healcomm = "HealComm 기능을 사용 (힐러용 공격대창)"
	TukuiL.option_raidframes_boss = "우두머리 개체창을 사용"
	TukuiL.option_raidframes_hpvertical = "생명력 바가 세로로 줄어듬 (힐러용 공격대창)"
	TukuiL.option_raidframes_enablerange = "공격대창에 거리를 표시"
	TukuiL.option_raidframes_range = "거리에 따른 투명도 설정"
	TukuiL.option_raidframes_maintank = "방어 전담창을 사용"
	TukuiL.option_raidframes_mainassist = "지원공격 전담창을 사용"
	TukuiL.option_raidframes_playerparty = "파티창에 플레이어를 표시"
	TukuiL.option_raidframes_hidenonmana = "마나를 사용하는 직업만 마나 바를 표시 (파티창에서는 불가능)"
	TukuiL.option_raidframes_fontsize = "공격대창의 글꼴크기"
	TukuiL.option_raidframes_scale = "공격대창의 크기"
	TukuiL.option_raidframes_disableblizz = "블리자드 기본 파티창 및 공격대창을 비활성화"
 
	-- 시전바
	TukuiL.option_castbar = "시전바"
	TukuiL.option_castbar_nointerruptcolor = "방해받지 않을 때 바의 색"
	TukuiL.option_castbar_castbarcolor = "시전바 색상"
	TukuiL.option_castbar_castbar = "시전바를 사용"
	TukuiL.option_castbar_latency = "시전바에 지연시간을 표시"
	TukuiL.option_castbar_icon = "시전바에 아이콘을 표시"
	TukuiL.option_castbar_castermode = "캐스터를 위한 큰 시전바를 사용"
	TukuiL.option_castbar_classcolor = "직업색상 테마를 사용"
 
	-- 개체창
	TukuiL.option_unitframes_unitframes = "개체창"
	TukuiL.option_unitframes_healthcolor = "생명력 바 색상"
	TukuiL.option_unitframes_combatfeedback = "생명력 바에 피해량 및 치유량을 표시"
	TukuiL.option_unitframes_totalhpmp = "생명력, 마나 등을 '현재|전체'로 표시"
	TukuiL.option_unitframes_aurawatch = "모서리에 강화 효과를 표시"
	TukuiL.option_unitframes_saveperchar = "개체창의 위치를 캐릭터별로 저장"
	TukuiL.option_unitframes_playeraggro = "위협수준이 증가하면 강조"
	TukuiL.option_unitframes_smooth = "부드러운 바를 사용"
	TukuiL.option_unitframes_portrait = "초상화를 표시"
	TukuiL.option_unitframes_enable = "Tukui 개체창을 사용"
	TukuiL.option_unitframes_enemypower = "플레이어창에만 파워 바를 표시"
	TukuiL.option_unitframes_raidaggro = "위협수준이 높은 공격대원을 강조"
	TukuiL.option_unitframes_symbol = "전술 목표 아이콘을 표시"
	TukuiL.option_unitframes_threatbar = "위협수준 바를 사용"
	TukuiL.option_unitframes_focus = "주시대상의 대상을 표시"
	TukuiL.option_unitframes_manalow = "마나가 낮으면 경고"
	TukuiL.option_unitframes_classcolor = "직업색상 테마를 사용"
	TukuiL.option_unitframes_SwingBar = "공격속도 바를 사용 (딜러/탱커용 개체창)"
	TukuiL.option_unitframes_DebuffHighlight = "약화 효과에 의한 개체창 색상 변경을 사용"
	TukuiL.option_unitframes_mendpet = "펫창에 고쳐진 펫 단축바를 표시(?) (딜러/탱커용 개체창)"
	TukuiL.option_unitframes_fontsize = "글꼴크기"
	TukuiL.option_unitframes_unitframes_poweroffset = "파워바 오프셋 (0은 오프셋 없음)"
	TukuiL.option_unitframes_classbar = "직업 바를 사용"
	TukuiL.option_unitframes_healthbackdropcolor = "생명령 바의 배경 색상"
 	TukuiL.option_unitframes_healthcolorbyvalue = "Color Healthbars by Health Remaining"
	TukuiL.option_unitframes_combat = "Fade unitframes while not in-combat"
	
	-- 창 크기
	TukuiL.option_framesizes = "개체창 크기"
	TukuiL.option_framesizes_playtarwidth = "플레이어/대상 창 너비"
	TukuiL.option_framesizes_playtarheight = "플레이어/대상 창 높이"
	TukuiL.option_framesizes_smallwidth = "대상의 대상/주시대상/주시대상의 대상/소환수 창 너비"
	TukuiL.option_framesizes_smallheight = "대상의 대상/주시대상/주시대상의 대상/소환수 창 높이"
	TukuiL.option_framesizes_arenabosswidth = "투기장/우두머리 창 너비"
	TukuiL.option_framesizes_arenabossheight = "투기장/우두머리 창 높이"
	TukuiL.option_framesizes_assisttankwidth = "방어/지원공격 전담 창 너비"
	TukuiL.option_framesizes_assisttankheight = "방어/지원공격 전담 창 높이"
 
	-- 전리품
	TukuiL.option_loot = "전리품"
	TukuiL.option_loot_enableloot = "전리품 획득창을 사용"
	TukuiL.option_loot_autogreed = "자동차비 또는 자동마출을 사용 (80레벨)"
	TukuiL.option_loot_enableroll = "주사위창을 사용"
 
	-- 툴팁
	TukuiL.option_tooltip = "툴팁"
	TukuiL.option_tooltip_enable = "툴팁을 사용"
	TukuiL.option_tooltip_hidecombat = "전투 중에 툴팁을 숨김"
	TukuiL.option_tooltip_hidebutton = "행동 단축버튼의 툴팁을 숨김"
	TukuiL.option_tooltip_hideuf = "개체창의 툴팁을 숨김"
	TukuiL.option_tooltip_cursor = "커서 위치에 툴팁을 표시"
	TukuiL.option_tooltip_combatraid = "공격대 중에만 전투 중에 툴팁을 숨김"
	TukuiL.option_tooltip_colorreaction = "툴팁 선과 생명력 바 색상"
	TukuiL.option_tooltip_xOfs = "툴팁의 X 좌표 (-x = 좌측으로, +x = 우측으로)"
	TukuiL.option_tooltip_yOfs = "툴팁의 Y 좌표 (-y = 아래로, +y = 위로)"
	TukuiL.option_tooltip_itemid = "Display Item ID"
	
	-- 기타
	TukuiL.option_others = "기타"
	TukuiL.option_others_bg = "전장에서 자동부활을 사용"
	TukuiL.option_others_autosell = "불필요한 아이템 자동판매를 사용"
	TukuiL.option_others_autorepair = "자동수리를 사용"
	TukuiL.option_others_autoinvite = "길드원이나 친구의 초대에 대한 자동수락을 사용"
	TukuiL.option_others_enablemap = "세계지도를 사용"
	TukuiL.option_others_errorhide = "화면 중앙의 오류메세지를 숨김"
	TukuiL.option_others_spincam = "자리 비움일 때 자동 시야 움직임을 사용"
	TukuiL.option_others_bagenable = "단일가방을 사용"
 
	-- 경고
	TukuiL.option_reminder = "강화 효과 추적"
	TukuiL.option_reminder_enable = "직업 강화 효과 추적을 사용"
	TukuiL.option_reminder_sound = "직업 강화 효과 경고소리를 사용"
	TukuiL.option_reminder_RaidBuffReminder = "공격대 강화 효과 추적을 사용"
 
	-- 행동 단축바
	TukuiL.option_actionbar = "행동 단축바"
	TukuiL.option_actionbar_hidess = "특수 기술 단축바를 숨김"
	TukuiL.option_actionbar_showgrid = "빈 행동 단축버튼를 표시"
	TukuiL.option_actionbar_enable = "행동 단축바를 사용"
	TukuiL.option_actionbar_rb = "커서가 위치할 때만 우측 단축바를 표시"
	TukuiL.option_actionbar_hk = "단축키를 표시"
	TukuiL.option_actionbar_ssmo = "커서가 위치할 때만 특수 기술 단축바를 표시"
	TukuiL.option_actionbar_rbn = "하단 단축바 줄의 수 (1, 2)"
	TukuiL.option_actionbar_rbn2 = "하단 단축바 줄의 수 (1, 1.5, 2)"
	TukuiL.option_actionbar_rn = "우측 단축바 줄의 수"
	TukuiL.option_actionbar_splitbar = "스플릿 단축바를 사용"
	TukuiL.option_actionbar_bottompetbar = "펫 기술 단축바를 하단 단축바 아래에 표시"
	TukuiL.option_actionbar_buttonsize = "행동 단축버튼의 크기"
	TukuiL.option_actionbar_buttonspacing = "행동 단축버튼의 간격"
	TukuiL.option_actionbar_petbuttonsize = "특수 기술 단축버튼의 크기"
	TukuiL.option_actionbar_petbuttonspacing = "특수 기술 단축버튼의 간격"
	TukuiL.option_actionbar_swaptopbottombar = "Swap the top and bottom actionbar positions"
	
	-- 투기장
	TukuiL.option_arena = "투기장"
	TukuiL.option_arena_st = "상대 플레이어 주문 추적을 사용"
	TukuiL.option_arena_uf = "투기장 상대 플레이어창을 사용"
 
	-- 재사용 대기시간
	TukuiL.option_cooldown = "재사용 대기시간"
	TukuiL.option_cooldown_enable = "재사용 대기시간 문자를 사용"
	TukuiL.option_cooldown_th = "몇 초 이하일 때 강조할지 설정"
	TukuiL.option_cooldown_expiringcolor = "소수점 색상"
	TukuiL.option_cooldown_secondscolor = "초 색상"
	TukuiL.option_cooldown_minutescolor = "분 색상"
	TukuiL.option_cooldown_hourscolor = "시간 색상"
	TukuiL.option_cooldown_dayscolor = "일 색상"
 
	-- 대화창
	TukuiL.option_chat = "대화창"
	TukuiL.option_chat_bubbles = "대화창 버블 스킨을 사용"
	TukuiL.option_chat_enable = "대화창을 사용"
	TukuiL.option_chat_whispersound = "귓속말 알림 소리를 사용"
	TukuiL_option_chat_chatwidth = "대화창의 너비"
	TukuiL_option_chat_backdrop = "대화창 배경을 사용"
	TukuiL_option_chat_chatheight = "대화창의 높이"
	TukuiL_option_chat_fadeoutofuse = "사라지지 않는 대화를 사용"
	TukuiL_option_chat_sticky = "몇 대화 채널에 글을 쓸 때 새로운 입력창을 사용"
 
	-- 버튼
	TukuiL.option_button_reset = "초기화"
	TukuiL.option_button_load = "적용"
	TukuiL.option_button_close = "닫기"
	TukuiL.option_setsavedsetttings = "캐릭터별로 저장"
	TukuiL.option_resetchar = "해당 캐릭터의 설정을 기본 설정으로 초기화하시겠습니까?"
	TukuiL.option_resetall = "모든 캐릭터의 설정을 기본 설정으로 초기화하시겠습니까?"
	TukuiL_option_perchar = "설정을 캐릭터별로 저장하시겠습니까?"
	TukuiL_option_makeselection = "계속하기전에 선택을 해야합니다."
end