if GetLocale() == "zhTW" then
	-- general
	TukuiL.option_general = "一般"
	TukuiL.option_general_uiscale = "自動調整UI比例"
	TukuiL.option_general_multisample = "多重採樣保護"
	TukuiL.option_general_customuiscale = "UI比例 (限用於自動調整關閉時)"
	TukuiL.option_general_recountscript = "顯示Recount設定(0-關閉, 1-戰鬥時顯示, 2-非戰鬥時顯示)"
	TukuiL.option_general_embedright = "將插件綁定於右邊對話框架(Recount, Omen, Skada)"
	TukuiL.option_general_classtheme = "框架使用職業顏色"
	TukuiL.option_general_minimalistic = "使UI看起來更加簡化"
	 
	--Media
	TukuiL.option_media = "Media"
	TukuiL.option_media_font = "Font file path for main font"
	TukuiL.option_media_uffont = "Font file path for UnitFrame fonts"
	TukuiL.option_media_dmgfont = "Font file path for DMG Text font (Requires Restart)"
	TukuiL.option_media_normTex = "Texture file path for unitframe Health/Power texture"
	TukuiL.option_media_glowTex = "Texture file path for glow texture"
	TukuiL.option_media_bubbleTex = "Texture file path for combo point texture (Nameplates)"
	TukuiL.option_media_blank = "Texture file path for main UI Texture"
	TukuiL.option_media_bordercolor = "Color of non-unitframe borders"
	TukuiL.option_media_altbordercolor = "Color of unitframe borders"
	TukuiL.option_media_backdropcolor = "Color of backdrop on all frames"
	TukuiL.option_media_backdropfadecolor = "Color of faded backdrop on certain faded frames"
	TukuiL.option_media_buttonhover = "Texture file path for Button Hover texture on actionbuttons"
	TukuiL.option_media_valuecolor = "Color of Datatext values"
	TukuiL.option_media_raidicons = "Texture file path for raid icons"
	TukuiL.option_media_whisper = "Sound file path for whisper sound"
	TukuiL.option_media_warning = "Sound file path for warning sound"

	-- nameplate
	TukuiL.option_nameplates = "名條"
	TukuiL.option_nameplates_enable = "開啟名條"
	TukuiL.option_nameplates_enhancethreat = "開啟仇恨模式, 依照你的角色決定: \n 坦克 - 綠色 (獲得仇恨) 紅色 (失去仇恨) DPS - 綠色 (失去仇恨) 紅色 (獲得仇恨)"
	TukuiL.option_nameplates_showhealth = "於名條上顯示生命文字"
	TukuiL.option_nameplates_showcombo = "於目標名條上顯示連擊點"
 
	TukuiL.option_skin = "插件皮膚化"
	TukuiL.option_skin_arkinventory = "Ark Inventory"
	TukuiL.option_skin_dxe = "Deus Vox Encounters"
	TukuiL.option_skin_omen = "Omen"
	TukuiL.option_skin_pallypower = "PallyPower"
	TukuiL.option_skin_qbar = "Qbar"
	TukuiL.option_skin_quartz = "Quartz"
	TukuiL.option_skin_recount = "Recount"
	TukuiL.option_skin_sexycooldown = "Sexy Cooldown"
	TukuiL.option_skin_skada = "Skada"
	TukuiL.option_skin_clcret = "CLCRet"
 
	-- combat text
	TukuiL.option_combattext = "戰鬥文字"
	TukuiL.option_combattext_showoverheal = "顯示過量治療"
	TukuiL.option_combattext_fontsize = "文字大小"
	TukuiL.option_combattext_showhots = "顯示HOTs"
 
	-- classtimer
	TukuiL.option_classtimer = "Class Timer"
	TukuiL.option_classtimer_enable = "開啟Classtimer插件"
	TukuiL.option_classtimer_bar_height = "計時條高度"
	TukuiL.option_classtimer_bar_spacing = "計時條間距"
	TukuiL.option_classtimer_icon_position = "圖示位置 (0-左邊,1-右邊,2-外面左邊,3-外面右邊)"
	TukuiL.option_classtimer_layout = "配置(1-4)"
	TukuiL.option_classtimer_showspark = "顯示火花"
	TukuiL.option_classtimer_cast_suparator = "施法間距"
	TukuiL.option_classtimer_classcolor = "職業上色"
	TukuiL.option_classtimer_debuffcolor = "DEBUFF計時條顏色"
	TukuiL.option_classtimer_buffcolor = "BUFF計時條顏色"
	TukuiL.option_classtimer_proccolor = "效果發動計時條顏色"
 
	-- raid buff reminder
	TukuiL.option_raidbuffreminder = "團隊BUFF提醒"
	TukuiL.option_raidbuffreminder_enable = "開啟團隊BUFF提醒"
	TukuiL.option_raidbuffreminder_alwaysshow_watch = "永遠顯示, 不勾選時只會於副本中啟動"
	TukuiL.option_raidbuffreminder_raidbuff_yOffset = "Y-軸位置調整"
	TukuiL.option_raidbuffreminder_buff_fadealpha = "擁有BUFF時淡出濃度"
 
	-- merchant
	TukuiL.option_merchant = "商人"
 
	TukuiL.option_bags = "背包"
	TukuiL.option_others_bagenable = "開啟整合背包"
	TukuiL.option_others_soulbag = "術士, 顯示靈魂包"
 
	-- datatext
	TukuiL.option_datatext = "訊息文字"
	TukuiL.option_datatext_24h = "開啟24小時制"
	TukuiL.option_datatext_localtime = "使用當地時間"
	TukuiL.option_datatext_bg = "開啟戰場資訊"
	TukuiL.option_datatext_hps = "HPS (0 - 關閉)"
	TukuiL.option_datatext_guild = "公會訊息 (0 - 關閉)"
	TukuiL.option_datatext_arp = "破甲 (0 - 關閉)"
	TukuiL.option_datatext_mem = "記憶體用量 (0 - 關閉)"
	TukuiL.option_datatext_bags = "背包 (0 - 關閉)"
	TukuiL.option_datatext_fontsize = "訊息文字大小"
	TukuiL.option_datatext_system = "延遲及FPS (0 - 關閉)"
	TukuiL.option_datatext_armor = "護甲值 (0 - 關閉)"
	TukuiL.option_datatext_avd = "閃躲值 (0 - 關閉)"
	TukuiL.option_datatext_power = "攻強/法傷位置 , 依職業天賦自動調整顯示訊息 (0 - 關閉)"
	TukuiL.option_datatext_haste = "加速 (0 - 關閉)"
	TukuiL.option_datatext_friend = "好友 (0 - 關閉)"
	TukuiL.option_datatext_time = "時間 (0 - 關閉)"
	TukuiL.option_datatext_gold = "金錢 (0 - 關閉)"
	TukuiL.option_datatext_dps = "DPS (0 - 關閉)"
	TukuiL.option_datatext_crit = "致命 (0 - 關閉)"
	TukuiL.option_datatext_dur = "耐久值 (0 - 關閉)"
	TukuiL.option_datatext_stat1 = "依職業天賦決定顯示屬性1"
	TukuiL.option_datatext_stat2 = "依職業天賦決定顯示屬性2"
	TukuiL.option_datatext_loc = "地點訊息 (0 - 關閉)"
	TukuiL.option_datatext_tps = "每秒仇恨 (0 - 關閉)"
 
	-- auras
	TukuiL.option_auras = "光環"
	TukuiL.option_auras_minimapauras = "開啟小地圖旁狀態光環"
	TukuiL.option_auras_arenadebuffs = "只在競技場/戰場中顯示重要DEBUFF"
	TukuiL.option_auras_auratimer = "開啟光環時間"
	TukuiL.option_auras_targetaura = "開啟目標光環"
	TukuiL.option_auras_focusdebuff = "開啟專注目標debuffs"
	TukuiL.option_auras_playeraura = "開啟玩家單位視窗光環"
	TukuiL.option_auras_aurascale = "光環文字比例"
	TukuiL.option_auras_totdebuffs = "開啟目標的目標debuffs"
	TukuiL.option_auras_playershowonlydebuffs = "只在玩家單位視窗顯示debuffs (限開啟玩家單位視窗光環下使用)"
	TukuiL.option_auras_playerdebuffsonly = "只顯示玩家DEBUFF於目標單位視窗"
	TukuiL.option_auras_RaidUnitBuffWatch = "開起團隊buff監視"
 
	-- raidframes
	TukuiL.option_raidframes = "團隊單位視窗"
	TukuiL.option_raidframes_enable = "開啟團隊單位視窗"
	TukuiL.option_raidframes_gridonly = "隊伍中使用25人團隊模式視窗"
	TukuiL.option_raidframes_healcomm = "開啟HealComm插件 (限治療配置)"
	TukuiL.option_raidframes_boss = "開啟首領單位視窗"
	TukuiL.option_raidframes_hpvertical = "開啟GRID縱向生命條"
	TukuiL.option_raidframes_enablerange = "開啟團隊/隊伍超出範圍淡出顯示"
	TukuiL.option_raidframes_range = "團隊/隊伍超出範圍淡出濃度"
	TukuiL.option_raidframes_maintank = "開啟主坦單位視窗"
	TukuiL.option_raidframes_mainassist = "開啟主助攻單位視窗"
	TukuiL.option_raidframes_NoGridDps = "縱向25人DPS配置"
	TukuiL.option_raidframes_CenterHealLayout = "將治療配置放在螢幕中間"
	TukuiL.option_raidframes_playerparty = "於隊伍中顯示玩家單位視窗"
	TukuiL.option_raidframes_hidenonmana = "只在單位有能量時顯示能量條"
	TukuiL.option_raidframes_fontsize = "團隊單位視窗文字大小"
	TukuiL.option_raidframes_scale = "團隊單位視窗比例 (用小數 例: 0.96)"
 
	-- castbar
	TukuiL.option_castbar = "施法條"
	TukuiL.option_castbar_nointerruptcolor = "無法中斷法術施法條顏色"
	TukuiL.option_castbar_castbarcolor = "施法條顏色"
	TukuiL.option_castbar_castbar = "開啟施法條"
	TukuiL.option_castbar_latency = "顯示施法延遲"
	TukuiL.option_castbar_icon = "顯示施法條法術圖示"
	TukuiL.option_castbar_castermode = "開啟大型施法條"
	TukuiL.option_castbar_classcolor = "玩家施法條使用職業顏色"
 
	-- unit frames
	TukuiL.option_unitframes_unitframes = "單位視窗"
	TukuiL.option_unitframes_healthcolor = "生命條顏色"
	TukuiL.option_unitframes_combatfeedback = "玩家及目標單位視窗戰鬥回饋"
	TukuiL.option_unitframes_runebar = "開啟死亡騎士符能條"
	TukuiL.option_unitframes_totembar = "開啟薩滿圖騰條"
	TukuiL.option_unitframes_totalhpmp = "顯示總生命/能量值"
	TukuiL.option_unitframes_aurawatch = "開啟Buff監視"
	TukuiL.option_unitframes_saveperchar = "依角色儲存單位視窗位置"
	TukuiL.option_unitframes_wstimer = "開啟虛弱靈魂計時條 (牧師專用)"
	TukuiL.option_unitframes_playeraggro = "開啟玩家仇恨顯示"
	TukuiL.option_unitframes_smooth = "開啟smooth bar插件"
	TukuiL.option_unitframes_portrait = "開啟玩家及目標頭像"
	TukuiL.option_unitframes_enable = "開啟Tukui單位視窗"
	TukuiL.option_unitframes_wstarget = "開啟目標虛弱靈魂計時條 (牧師專用)"
	TukuiL.option_unitframes_enemypower = "開啟只於敵對玩家顯示目標能量值"
	TukuiL.option_unitframes_wsplayer = "開啟玩家虛弱靈魂計時條"
	TukuiL.option_unitframes_raidaggro = "開啟仇恨顯示"
	TukuiL.option_unitframes_symbol = "顯示隊伍/團隊標計"
	TukuiL.option_unitframes_threatbar = "開啟仇恨條"
	TukuiL.option_unitframes_focus = "開啟專注目標"
	TukuiL.option_unitframes_manahigh = "法力過量顯示 (獵人專用)"
	TukuiL.option_unitframes_manalow = "法力過低顯示 (所有法系通用)"
	TukuiL.option_unitframes_classcolor = "依照職業上色單位視窗"
	TukuiL.option_unitframes_ComboHideOOC = "戰鬥外隱藏COMBO條"
	TukuiL.option_unitframes_ComboHideNoEnergy = "沒有能量時隱藏COMBO條"
	TukuiL.option_unitframes_SwingBar = "開啟自動攻擊計時條 (限DPS配置)"
	TukuiL.option_unitframes_DebuffHighlight = "單位視窗依可驅散DEBUFF上色"
	TukuiL.option_unitframes_fontsize = "單位視窗文字大小"
 
	-- loot
	TukuiL.option_loot = "戰利品"
	TukuiL.option_loot_enableloot = "開啟戰力品視窗"
	TukuiL.option_loot_autogreed = "開啟最高等級時自動貪婪綠色等級裝備"
	TukuiL.option_loot_enableroll = "開啟骰裝視窗"
 
	-- tooltip
	TukuiL.option_tooltip = "提示訊息"
	TukuiL.option_tooltip_enable = "開啟提示訊息"
	TukuiL.option_tooltip_hidecombat = "戰鬥中隱藏右下角提示訊息"
	TukuiL.option_tooltip_hidebutton = "隱藏動作條的提示訊息"
	TukuiL.option_tooltip_hideuf = "隱藏單位視窗提示訊息"
	TukuiL.option_tooltip_cursor = "開啟滑鼠旁提示訊息"
	TukuiL.option_tooltip_combatraid = "限於團隊戰鬥中隱藏提示訊息"
	TukuiL.option_tooltip_colorreaction = "提示訊息及生命條依照敵對狀態上色"
	TukuiL.option_tooltip_xOfs = "提示訊息X-軸位子調整 (-x = 左, +x = 右)"
	TukuiL.option_tooltip_yOfs = "提示訊息Y-軸位子調整 (-y = 下, +y = 上)"
 
	-- others
	TukuiL.option_others = "其他"
	TukuiL.option_others_bg = "戰場中自動放魂"
	TukuiL.option_others_autosell = "自動販賣灰色物品"
	TukuiL.option_others_autorepair = "自動修復裝備"
	TukuiL.option_others_autoinvite = "開啟自動邀請及接受邀請 (限好友及公會會員)"
	TukuiL.option_others_enablemap = "開啟Tukui地圖"
	TukuiL.option_others_questmovable = "可移動任務追蹤欄"
	TukuiL.option_others_errorhide = "隱藏螢幕中央錯誤訊息"
	TukuiL.option_others_totembardirection = "圖騰裂開啟方向 (上/下)"
	TukuiL.option_others_portals = "開啟法師傳送門插件"
	TukuiL.option_others_spincam = "AFK時旋轉視角"
	TukuiL.option_others_bagenable = "使用整合背包"
	TukuiL.option_others_soulbag = "顯示靈魂包"
 
	-- reminder
	TukuiL.option_reminder = "光環警告"
	TukuiL.option_reminder_enable = "開啟玩家光環警告"
	TukuiL.option_reminder_sound = "開啟玩家語音光環警告"
 
	-- action bar
	TukuiL.option_actionbar = "動作條"
	TukuiL.option_actionbar_hidess = "隱藏變身及圖騰條"
	TukuiL.option_actionbar_showgrid = "永遠顯示動作條格位"
	TukuiL.option_actionbar_enable = "開啟Tukui動作條"
	TukuiL.option_actionbar_rb = "開啟當滑鼠移動至右方動作條時顯示"
	TukuiL.option_actionbar_hk = "顯示熱鍵文字"
	TukuiL.option_actionbar_ssmo = "開啟當滑鼠移動至變身及圖騰條時顯示"
	TukuiL.option_actionbar_rbn = "底部動作條數量 (1 或 2)"
	TukuiL.option_actionbar_rbn2 = "底部動作條數量 (1, 1.5, 或 2)"
	TukuiL.option_actionbar_rn = "右方動作條數量 (1, 2 或 3)"
	TukuiL.option_actionbar_splitbar = "開啟分割動作條"
 
	-- arena
	TukuiL.option_arena = "競技場"
	TukuiL.option_arena_st = "競技場中開啟敵方法術追蹤"
	TukuiL.option_arena_uf = "開啟競技場單位視窗"
 
	-- cooldowns
	TukuiL.option_cooldown = "冷卻"
	TukuiL.option_cooldown_enable = "開啟按鍵上冷卻倒數文字"
	TukuiL.option_cooldown_th = "倒數文字於X秒後變色"
	TukuiL.option_cooldown_expiringcolor = "倒數到期文字顏色"
	TukuiL.option_cooldown_secondscolor = "秒數文字顏色"
	TukuiL.option_cooldown_minutescolor = "分鐘文字顏色"
	TukuiL.option_cooldown_hourscolor = "小時文字顏色"
	TukuiL.option_cooldown_dayscolor = "天數文字顏色"
 
	-- chat
	TukuiL.option_chat = "對話框"
	TukuiL.option_chat_enable = "開啟Tukui對話框"
	TukuiL.option_chat_whispersound = "收到密語時語音警告"
	TukuiL_option_chat_chatwidth = "對話框寬度"
	TukuiL_option_chat_backdrop = "顯示對話框背景"
	TukuiL_option_chat_chatheight = "對話框高度"
	TukuiL_option_chat_fadeoutofuse = "不使用時對話文字淡出"
	TukuiL_option_chat_sticky = "開啟新對話框時預設某些重要頻道"
 
	-- buttons
	TukuiL.option_button_reset = "重置UI"
	TukuiL.option_button_load = "套用變動"
	TukuiL.option_button_close = "關閉"
	TukuiL.option_setsavedsetttings = "依角色儲存設定"
	TukuiL.option_resetchar = "你確定要將你的角色設定設置成你的預設設定嗎?"
	TukuiL.option_resetall = "你確定要將你所有的設定設置成系統預設嗎?"
	TukuiL_option_perchar = "你確定要開啟或者關閉依角色儲存設定的模式嗎?"
	TukuiL_option_makeselection = "你必需作出選擇才能繼續設定"
end