if TukuiDB.client == "koKR" then
	tukuilocal.datatext_guild = "길드"
	tukuilocal.datatext_noguild = "길드 없음"
	tukuilocal.datatext_bags = "가방: "
	tukuilocal.datatext_friends = "친구"
	tukuilocal.datatext_online = "온라인: "
	tukuilocal.datatext_armor = "내구도"
	tukuilocal.datatext_earned = "수입:"
	tukuilocal.datatext_spent = "지출:"
	tukuilocal.datatext_deficit = "적자:"
	tukuilocal.datatext_profit = "흑자:"
	tukuilocal.datatext_wg = "겨울손아귀 전투시간:"
	tukuilocal.datatext_friendlist = "친구 목록:"
	tukuilocal.datatext_inprogress = "진행 중"
	tukuilocal.datatext_unavailable = "사용 불가능"
	tukuilocal.datatext_playersp = "주문력"
	tukuilocal.datatext_playerap = "전투력"
	tukuilocal.datatext_playerhaste = "가속도"
	tukuilocal.datatext_dps = "dps"
	tukuilocal.datatext_hps = "hps"
	tukuilocal.datatext_playerarp = "방어구 관통력"
	tukuilocal.datatext_session = "세션: "
	tukuilocal.datatext_character = "캐릭터: "
	tukuilocal.datatext_server = "서버: "
	tukuilocal.datatext_totalgold = "전체: "
	tukuilocal.datatext_savedraid = "귀속된 던전"
	tukuilocal.datatext_currency = "화폐:"
	tukuilocal.datatext_fps = " fps & "
	tukuilocal.datatext_ms = " ms"
	tukuilocal.datatext_playercrit = " 치명타율"
	tukuilocal.datatext_playerheal = " 극대화율"
	tukuilocal.datatext_avoidancebreakdown = "회피 내역"
	tukuilocal.datatext_lvl = "레벨"
	tukuilocal.datatext_boss = "우두머리"
	tukuilocal.datatext_miss = "빗맞힘"
	tukuilocal.datatext_dodge = "회피율"
	tukuilocal.datatext_block = "방패 막기"
	tukuilocal.datatext_parry = "무기 막기"
	tukuilocal.datatext_playeravd = "완방: "
	tukuilocal.datatext_servertime = "서버 시간: "
	tukuilocal.datatext_localtime = "지역 시간: "
	tukuilocal.datatext_mitigation = "Mitigation By Level: "
	tukuilocal.datatext_healing = "치유량 : "
	tukuilocal.datatext_damage = "피해량 : "
	tukuilocal.datatext_honor = "명예 점수 : "
	tukuilocal.datatext_killingblows = "결정타 : "
	tukuilocal.datatext_ttstatsfor = "점수 : "
	tukuilocal.datatext_ttkillingblows = "결정타:"
	tukuilocal.datatext_tthonorkills = "명예 승수:"
	tukuilocal.datatext_ttdeaths = "죽은 수:"
	tukuilocal.datatext_tthonorgain = "획득한 명예:"
	tukuilocal.datatext_ttdmgdone = "피해량:"
	tukuilocal.datatext_tthealdone = "치유량:"
	tukuilocal.datatext_basesassaulted = "거점 공격:"
	tukuilocal.datatext_basesdefended = "거점 방어:"
	tukuilocal.datatext_towersassaulted = "경비탑 점령:"
	tukuilocal.datatext_towersdefended = "경비탑 방어:"
	tukuilocal.datatext_flagscaptured = "깃발 쟁탈:"
	tukuilocal.datatext_flagsreturned = "깃발 반환:"
	tukuilocal.datatext_graveyardsassaulted = "무덤 점령:"
	tukuilocal.datatext_graveyardsdefended = "무덤 방어:"
	tukuilocal.datatext_demolishersdestroyed = "파괴한 파괴전차:"
	tukuilocal.datatext_gatesdestroyed = "파괴한 관문:"
	tukuilocal.datatext_totalmemusage = "총 메모리 사용량:"
 
	tukuilocal.Slots = {
	  [1] = {1, "머리", 1000},
	  [2] = {3, "어깨", 1000},
	  [3] = {5, "가슴", 1000},
	  [4] = {6, "허리", 1000},
	  [5] = {9, "손목", 1000},
	  [6] = {10, "손", 1000},
	  [7] = {7, "다리", 1000},
	  [8] = {8, "발", 1000},
	  [9] = {16, "주장비", 1000},
	  [10] = {17, "보조장비", 1000},
	  [11] = {18, "원거리", 1000}
	}
 
	tukuilocal.popup_disableui = "Tukui는 현재 해상도에 최적화되어 있지 않습니다. Tukui를 비활성화하시겠습니까? (다른 해상도로 시도해보려면 취소)"
	tukuilocal.popup_install = "현재 캐릭터는 Tukui를 처음 사용합니다. 행동 단축바, 대화창, 다양한 설정을 위해 UI를 다시 시작하셔야만 합니다."
	tukuilocal.popup_2raidactive = "2개의 공격대 인터페이스가 활성화되어 있습니다. 한 가지만 선택하셔야 합니다."
 
	tukuilocal.merchant_repairnomoney = "수리에 필요한 돈이 충분하지 않습니다!"
	tukuilocal.merchant_repaircost = "모든 아이템이 수리되었습니다: "
	tukuilocal.merchant_trashsell = "불필요한 아이템이 판매되었습니다: "
 
	tukuilocal.goldabbrev = "|cffffd700골|r"
	tukuilocal.silverabbrev = "|cffc7c7cf실|r"
	tukuilocal.copperabbrev = "|cffeda55f코|r"
 
	tukuilocal.error_noerror = "오류가 발견되지 않았습니다."
 
	tukuilocal.unitframes_ouf_offline = "오프라인"
	tukuilocal.unitframes_ouf_dead = "죽음"
	tukuilocal.unitframes_ouf_ghost = "유령"
	tukuilocal.unitframes_ouf_lowmana = "마나 적음"
	tukuilocal.unitframes_ouf_threattext = "현재 대상에 대한 위협수준:"
	tukuilocal.unitframes_ouf_offlinedps = "오프라인"
	tukuilocal.unitframes_ouf_deaddps = "죽음"
	tukuilocal.unitframes_ouf_ghostheal = "유령"
	tukuilocal.unitframes_ouf_deadheal = "죽음"
	tukuilocal.unitframes_ouf_gohawk = "매의 상으로 전환"
	tukuilocal.unitframes_ouf_goviper = "독사의 상으로 전환"
	tukuilocal.unitframes_disconnected = "오프라인"
 
	tukuilocal.tooltip_targetyou = "|cffff4444>>당신<<|r"
 
	tukuilocal.priest_wsdebuff = "약화된 영혼"
	tukuilocal.priest_ifbuff = "내면의 열정"
 
	tukuilocal.bags_noslots = "소지품이 가득 찼습니다."
	tukuilocal.bags_costs = "가격: %.2f 골"
	tukuilocal.bags_buyslots = "가방 보관함을 추가로 구입하시기 위해서는 /bags를 입력해주세요."
	tukuilocal.bags_openbank = "먼저 은행을 열어야 합니다."
	tukuilocal.bags_sort = "열려있는 가방이나 은행에 있는 아이템을 정리합니다."
	tukuilocal.bags_stack = "띄엄띄엄 있는 아이템을 정리합니다."
	tukuilocal.bags_buybankslot = "가방 보관함을 추가로 구입합니다."
	tukuilocal.bags_search = "검색"
	tukuilocal.bags_sortmenu = "분류"
	tukuilocal.bags_sortspecial = "특수물품 분류"
	tukuilocal.bags_stackmenu = "정리"
	tukuilocal.bags_stackspecial = "특수물품 정리"
	tukuilocal.bags_showbags = "가방 보기"
	tukuilocal.bags_sortingbags = "분류 완료."
	tukuilocal.bags_nothingsort= "분류할 것이 없습니다."
	tukuilocal.bags_bids = "사용 중인 가방: "
	tukuilocal.bags_stackend = "재정리 완료."
 
	tukuilocal.chat_invalidtarget = "잘못된 대상"
 
	tukuilocal.mount_wintergrasp = "겨울손아귀"
 
	tukuilocal.playermenu_freeforall = "자유 획득"
	tukuilocal.playermenu_group = "|cff1eff00주사위 굴림|r"
	tukuilocal.playermenu_master = "|cff0070dd담당자 획득|r"
	tukuilocal.playermenu_global_needbeforegreed = "전리품: %s주사위 굴림 (착용자 우선)|r"
	tukuilocal.playermenu_global_freeforall = "전리품: %s자유 획득|r"
	tukuilocal.playermenu_global_group = "전리품: %s주사위 굴림|r"
	tukuilocal.playermenu_global_master = "전리품: %s담당자 획득|r"
	tukuilocal.playermenu_normal = "5인 (|cffffff50일반|r)"
	tukuilocal.playermenu_heroic = "5인 (|cffff5050영웅|r)"
	tukuilocal.playermenu_raid10 = "10인 (|cffffff50일반|r)"
	tukuilocal.playermenu_raid25 = "25인 (|cffffff50일반|r)"
	tukuilocal.playermenu_raid10h = "10인 (|cffff5050영웅|r)"
	tukuilocal.playermenu_raid25h = "25인 (|cffff5050영웅|r)"
 
	tukuilocal.core_autoinv_enable = "자동초대 활성화: 초대"
	tukuilocal.core_autoinv_enable_c = "자동초대 활성화: "
	tukuilocal.core_autoinv_disable = "자동초대 비활성화"
	tukuilocal.core_wf_unlock = "임무 추적기 잠금 해제"
	tukuilocal.core_wf_lock = "임무 추적기 잠금"
	tukuilocal.core_welcome1 = "|cffC495DDTukui|r를 사용해주셔서 감사합니다. 버전 "
	tukuilocal.core_welcome2 = " "
 
	tukuilocal.core_uihelp1 = "|cff00ff00일반적인 명령어|r"
	tukuilocal.core_uihelp2 = "|cffFF0000/tracker|r - Tukui 투기장 애드온 - 가벼운 투기장 애드온입니다."
	tukuilocal.core_uihelp3 = "|cffFF0000/rl|r - UI를 재시작합니다."
	tukuilocal.core_uihelp4 = "|cffFF0000/gm|r - 도움 요청(지식 열람실, GM 요청하기) 창을 엽니다."
	tukuilocal.core_uihelp5 = "|cffFF0000/frame|r - 커서가 위치한 창의 이름을 보여줍니다. (lua 편집 시 매우 유용)"
	tukuilocal.core_uihelp6 = "|cffFF0000/heal|r - 힐러용 공격대 인터페이스를 사용합니다."
	tukuilocal.core_uihelp7 = "|cffFF0000/dps|r - 딜러/탱커용 공격대 인터페이스를 사용합니다."
	tukuilocal.core_uihelp8 = "|cffFF0000/uf|r - 개체창을 이동할 수 있습니다."
	tukuilocal.core_uihelp9 = "|cffFF0000/bags|r - 분류, 정리, 가방 보관함을 추가 구입을 할 수 있습니다."
	tukuilocal.core_uihelp10 = "|cffFF0000/resetui|r - Tukui의 설정을 초기화합니다."
	tukuilocal.core_uihelp11 = "|cffFF0000/rd|r - 공격대를 해체합니다."
	tukuilocal.core_uihelp12 = "|cffFF0000/wf|r - 임무 추적기를 이동할 수 있습니다."
	tukuilocal.core_uihelp13 = "|cffFF0000/mss|r - 특수 기술 단축바를 이동할 수 있습니다."
	tukuilocal.core_uihelp15 = "|cffFF0000/ainv|r - 자동초대 기능을 사용합니다. '/ainv 단어'를 입력하여 해당 단어가 들어간 귓속말이 올 경우 자동으로 초대를 합니다."
	tukuilocal.core_uihelp14 = "(위로 올리십시오 ...)"
 
	tukuilocal.symbol_CLEAR = "초기화"
	tukuilocal.symbol_SKULL = "해골"
	tukuilocal.symbol_CROSS = "가위표"
	tukuilocal.symbol_SQUARE = "네모"
	tukuilocal.symbol_MOON = "달"
	tukuilocal.symbol_TRIANGLE = "세모"
	tukuilocal.symbol_DIAMOND = "다이아몬드"
	tukuilocal.symbol_CIRCLE = "동그라미"
	tukuilocal.symbol_STAR = "별"
 
	tukuilocal.bind_combat = "전투 중엔 단축키를 지정할 수 없습니다."
	tukuilocal.bind_saved = "새로 지정한 모든 단축키가 저장되었습니다."
	tukuilocal.bind_discard = "새로 지정한 모든 단축키가 저장되지 않았습니다."
	tukuilocal.bind_instruct = "커서가 위치한 단축버튼에 단축키를 지정할 수 있습니다. 오른쪽 클릭으로 해당 단축버튼의 단축키를 초기화할 수 있습니다."
	tukuilocal.bind_save = "저장"
	tukuilocal.bind_discardbind = "취소"
 
	tukuilocal.hunter_unhappy = "펫의 만족도가 낮습니다!"
	tukuilocal.hunter_content = "펫의 만족도가 적당합니다!"
	tukuilocal.hunter_happy = "펫의 만족도가 높습니다!"
end